<template><div><p>Cosmos SDK &gt;= 0.42, which is used by the latest <code v-pre>und</code> software, can use State Syncing  from Snapshots to quickly
sync your node from a safe checkpoint. This potentially reduces the sync time to no more than an hour or so, and in
most cases mere minutes.</p>
<p>Setting this up requires a few more steps</p>
<ol>
<li>Run the following command to get the latest block hash and height. For <strong>TestNet</strong>:</li>
</ol>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> -s https://rest-testnet.unification.io/blocks/latest <span class="token operator">|</span> jq <span class="token string">'.|[.block_id.hash,.block.header.height]'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>For <strong>MainNet</strong>:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> -s https://rest.unification.io/blocks/latest <span class="token operator">|</span> jq <span class="token string">'.|[.block_id.hash,.block.header.height]'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Example output:</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code><span class="token punctuation">[</span>
  <span class="token string">"820275B5EE63EDA2923886A01C0B1196A7CE1D96A89FA0D774942999C6698AAC"</span><span class="token punctuation">,</span>
  <span class="token string">"1052423"</span>
<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="2">
<li>Using the output from the above command, configure <code v-pre>[statesync]</code> section in <code v-pre>.und_mainchain/config.toml</code>:</li>
</ol>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">enable</span> <span class="token punctuation">=</span> <span class="token boolean">true</span>
<span class="token key property">rpc_servers</span> <span class="token punctuation">=</span> <span class="token string">"TWO_RPC_NODES"</span>
<span class="token key property">trust_height</span> <span class="token punctuation">=</span> <span class="token number">1052423</span>
<span class="token key property">trust_hash</span> <span class="token punctuation">=</span> <span class="token string">"820275B5EE63EDA2923886A01C0B1196A7CE1D96A89FA0D774942999C6698AAC"</span>
<span class="token key property">trust_period</span> <span class="token punctuation">=</span> <span class="token string">"168h0m0s"</span>
<span class="token key property">discovery_time</span> <span class="token punctuation">=</span> <span class="token string">"30s"</span>
<span class="token key property">temp_dir</span> <span class="token punctuation">=</span> <span class="token string">""</span>
<span class="token key property">chunk_request_timeout</span> <span class="token punctuation">=</span> <span class="token string">"60s"</span>
<span class="token key property">chunk_fetchers</span> <span class="token punctuation">=</span> <span class="token string">"4"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>The <code v-pre>rpc_servers</code> requires two RPC nodes for verification.</p>
<p>For <strong>TestNet</strong>, replace <code v-pre>TWO_RPC_NODES</code> with:</p>
<p><code v-pre>sync1-testnet.unification.io:26657,sync2-testnet.unification.io:26657</code></p>
<p>For <strong>MainNet</strong>:</p>
<p><code v-pre>sync1.unification.io:26657,sync2.unification.io:26657</code></p>
<p>e.g.:</p>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">rpc_servers</span> <span class="token punctuation">=</span> <span class="token string">"sync1.unification.io:26657,sync2.unification.io:26657"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Or any RPC servers of your choice for the target network.</p>
<ol start="3">
<li>Start your node</li>
</ol>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>und start --home<span class="token operator">=</span>/path/to/.und_mainchain
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>you should start seeing the following:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token number">11</span>:53AM INF Discovered new snapshot <span class="token assign-left variable">format</span><span class="token operator">=</span><span class="token number">1</span> <span class="token assign-left variable">hash</span><span class="token operator">=</span><span class="token string">"V0���&amp;�U1�J0�yP4A%�/���GŽ@<span class="token entity" title="\x05">\x05</span>�&lt;�j"</span> <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1051600</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>statesync
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>After a few seconds (or at most, minutes), you should see your node start downloading the blocks:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token number">11</span>:56AM INF received proposal <span class="token assign-left variable">module</span><span class="token operator">=</span>consensus <span class="token assign-left variable">proposal</span><span class="token operator">=</span><span class="token punctuation">{</span><span class="token string">"Type"</span>:32,<span class="token string">"block_id"</span>:<span class="token punctuation">{</span><span class="token string">"hash"</span><span class="token builtin class-name">:</span><span class="token string">"632E122ADDF385954FB8598FEE7D89EB09D7E93746FB36D2F12DECFEB7F07D9E"</span>,<span class="token string">"parts"</span>:<span class="token punctuation">{</span><span class="token string">"hash"</span><span class="token builtin class-name">:</span><span class="token string">"E8246C504B9BC14275874A90C95E6AA035678302AD3BF9269B6F253B04C038BE"</span>,<span class="token string">"total"</span>:1<span class="token punctuation">}</span><span class="token punctuation">}</span>,<span class="token string">"height"</span>:1052494,<span class="token string">"pol_round"</span>:-1,<span class="token string">"round"</span>:0,<span class="token string">"signature"</span><span class="token builtin class-name">:</span><span class="token string">"HYJz0rV7o6bNm7za82sj1Az1rV25qVkLh9Y4s0K95nf86uVq+YmuDIf3LtIP7pDfFEYErxNVyeSplPGh7IVHDQ=="</span>,<span class="token string">"timestamp"</span><span class="token builtin class-name">:</span><span class="token string">"2022-05-19T10:56:03.273030584Z"</span><span class="token punctuation">}</span>
<span class="token number">11</span>:56AM INF received complete proposal block <span class="token assign-left variable">hash</span><span class="token operator">=</span>632E122ADDF385954FB8598FEE7D89EB09D7E93746FB36D2F12DECFEB7F07D9E <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1052494</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>consensus
<span class="token number">11</span>:56AM INF finalizing commit of block <span class="token assign-left variable">hash</span><span class="token operator">=</span>632E122ADDF385954FB8598FEE7D89EB09D7E93746FB36D2F12DECFEB7F07D9E <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1052494</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>consensus <span class="token assign-left variable">num_txs</span><span class="token operator">=</span><span class="token number">0</span> <span class="token assign-left variable">root</span><span class="token operator">=</span>7EC77102840743503BD71FD89F60FD0B912DD0DE27575408B6AD67990CE4A6B8
<span class="token number">11</span>:56AM INF executed block <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1052494</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>state <span class="token assign-left variable">num_invalid_txs</span><span class="token operator">=</span><span class="token number">0</span> <span class="token assign-left variable">num_valid_txs</span><span class="token operator">=</span><span class="token number">0</span>
<span class="token number">11</span>:56AM INF commit synced <span class="token assign-left variable">commit</span><span class="token operator">=</span>436F6D6D697449447B5B3234312031333020323235203834203837203234372031303220323820323435203234382032372032303920313432203133372031303620353920343520323220323020313737203135342032303320323338203136352030203231322034392031383620313638203433203839203233395D3A3130304634457D
<span class="token number">11</span>:56AM INF committed state <span class="token assign-left variable">app_hash</span><span class="token operator">=</span>F182E15457F7661CF5F81BD18E896A3B2D1614B19ACBEEA500D431BAA82B59EF <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1052494</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>state <span class="token assign-left variable">num_txs</span><span class="token operator">=</span><span class="token number">0</span>
<span class="token number">11</span>:56AM INF indexed block <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1052494</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>txindex
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
