<template><div><h2 id="und" tabindex="-1"><a class="header-anchor" href="#und" aria-hidden="true">#</a> und</h2>
<p>Unification Mainchain App</p>
<h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for und
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_add-genesis-account.html">und add-genesis-account</RouterLink>	 - Add a genesis account to genesis.json</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_collect-gentxs.html">und collect-gentxs</RouterLink>	 - Collect genesis txs and output a genesis.json file</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_config.html">und config</RouterLink>	 - Create or query an application CLI configuration file</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_convert.html">und convert</RouterLink>	 - convert between FUND denominations</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_debug.html">und debug</RouterLink>	 - Tool for helping with debugging your application</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_export.html">und export</RouterLink>	 - Export state to JSON</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_gentx.html">und gentx</RouterLink>	 - Generate a genesis tx carrying a self delegation</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_init.html">und init</RouterLink>	 - Initialize private validator, p2p, genesis, and application configuration files</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_keys.html">und keys</RouterLink>	 - Manage your application's keys</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query.html">und query</RouterLink>	 - Querying subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_rollback.html">und rollback</RouterLink>	 - rollback cosmos-sdk and tendermint state by one height</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_rosetta.html">und rosetta</RouterLink>	 - spin up a rosetta server</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_start.html">und start</RouterLink>	 - Run the full node</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_status.html">und status</RouterLink>	 - Query remote node for status</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tendermint.html">und tendermint</RouterLink>	 - Tendermint subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx.html">und tx</RouterLink>	 - Transactions subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_validate-genesis.html">und validate-genesis</RouterLink>	 - validates the genesis file at the default location or at the location passed as an arg</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_version.html">und version</RouterLink>	 - Print the application binary version information</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
