<template><div><h2 id="und-tx-distribution" tabindex="-1"><a class="header-anchor" href="#und-tx-distribution" aria-hidden="true">#</a> und tx distribution</h2>
<p>Distribution transactions subcommands</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und tx distribution [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for distribution
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx.html">und tx</RouterLink>	 - Transactions subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_distribution_fund-community-pool.html">und tx distribution fund-community-pool</RouterLink>	 - Funds the community pool with the specified amount</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_distribution_set-withdraw-addr.html">und tx distribution set-withdraw-addr</RouterLink>	 - change the default withdraw address for rewards associated with an address</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_distribution_withdraw-all-rewards.html">und tx distribution withdraw-all-rewards</RouterLink>	 - withdraw all delegations rewards for a delegator</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_distribution_withdraw-rewards.html">und tx distribution withdraw-rewards</RouterLink>	 - Withdraw rewards from a given delegation address, and optionally withdraw validator commission if the delegation address given is a validator operator</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
