<template><div><h2 id="und-query" tabindex="-1"><a class="header-anchor" href="#und-query" aria-hidden="true">#</a> und query</h2>
<p>Querying subcommands</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und query [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
  -h, --help              help for query
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und.html">und</RouterLink>	 - Unification Mainchain App</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_account.html">und query account</RouterLink>	 - Query for account by address</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_auth.html">und query auth</RouterLink>	 - Querying commands for the auth module</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_authz.html">und query authz</RouterLink>	 - Querying commands for the authz module</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_bank.html">und query bank</RouterLink>	 - Querying commands for the bank module</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_beacon.html">und query beacon</RouterLink>	 - Querying commands for the beacon module</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_block.html">und query block</RouterLink>	 - Get verified data for a the block at given height</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_distribution.html">und query distribution</RouterLink>	 - Querying commands for the distribution module</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_enterprise.html">und query enterprise</RouterLink>	 - Querying commands for the enterprise module</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_evidence.html">und query evidence</RouterLink>	 - Query for evidence by hash or for all (paginated) submitted evidence</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_feegrant.html">und query feegrant</RouterLink>	 - Querying commands for the feegrant module</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_gov.html">und query gov</RouterLink>	 - Querying commands for the governance module</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc.html">und query ibc</RouterLink>	 - Querying commands for the IBC module</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc-transfer.html">und query ibc-transfer</RouterLink>	 - IBC fungible token transfer query subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_params.html">und query params</RouterLink>	 - Querying commands for the params module</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_slashing.html">und query slashing</RouterLink>	 - Querying commands for the slashing module</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_staking.html">und query staking</RouterLink>	 - Querying commands for the staking module</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_supply.html">und query supply</RouterLink>	 - Query the total supply of coins of the chain</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_tendermint-validator-set.html">und query tendermint-validator-set</RouterLink>	 - Get the full tendermint validator set at given height</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_tx.html">und query tx</RouterLink>	 - Query for a transaction by hash, &quot;〈addr〉/〈seq〉&quot; combination or comma-separated signatures in a committed block</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_txs.html">und query txs</RouterLink>	 - Query for paginated transactions that match a set of events</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_upgrade.html">und query upgrade</RouterLink>	 - Querying commands for the upgrade module</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_wrkchain.html">und query wrkchain</RouterLink>	 - Querying commands for the wrkchain module</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
