<template><div><h2 id="und-query-ibc-channel" tabindex="-1"><a class="header-anchor" href="#und-query-ibc-channel" aria-hidden="true">#</a> und query ibc channel</h2>
<p>IBC channel query subcommands</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und query ibc channel [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for channel
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc.html">und query ibc</RouterLink>	 - Querying commands for the IBC module</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_channel_channels.html">und query ibc channel channels</RouterLink>	 - Query all channels</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_channel_client-state.html">und query ibc channel client-state</RouterLink>	 - Query the client state associated with a channel</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_channel_connections.html">und query ibc channel connections</RouterLink>	 - Query all channels associated with a connection</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_channel_end.html">und query ibc channel end</RouterLink>	 - Query a channel end</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_channel_next-sequence-receive.html">und query ibc channel next-sequence-receive</RouterLink>	 - Query a next receive sequence</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_channel_packet-ack.html">und query ibc channel packet-ack</RouterLink>	 - Query a packet acknowledgement</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_channel_packet-commitment.html">und query ibc channel packet-commitment</RouterLink>	 - Query a packet commitment</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_channel_packet-commitments.html">und query ibc channel packet-commitments</RouterLink>	 - Query all packet commitments associated with a channel</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_channel_packet-receipt.html">und query ibc channel packet-receipt</RouterLink>	 - Query a packet receipt</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_channel_unreceived-acks.html">und query ibc channel unreceived-acks</RouterLink>	 - Query all the unreceived acks associated with a channel</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_channel_unreceived-packets.html">und query ibc channel unreceived-packets</RouterLink>	 - Query all the unreceived packets associated with a channel</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
