<template><div><h2 id="und-query-upgrade" tabindex="-1"><a class="header-anchor" href="#und-query-upgrade" aria-hidden="true">#</a> und query upgrade</h2>
<p>Querying commands for the upgrade module</p>
<h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for upgrade
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_query.html">und query</RouterLink>	 - Querying subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_upgrade_applied.html">und query upgrade applied</RouterLink>	 - block header for height at which a completed upgrade was applied</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_upgrade_module_versions.html">und query upgrade module_versions</RouterLink>	 - get the list of module versions</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_upgrade_plan.html">und query upgrade plan</RouterLink>	 - get upgrade plan (if one exists)</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
