<template><div><h2 id="und-tendermint" tabindex="-1"><a class="header-anchor" href="#und-tendermint" aria-hidden="true">#</a> und tendermint</h2>
<p>Tendermint subcommands</p>
<h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for tendermint
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und.html">und</RouterLink>	 - Unification Mainchain App</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tendermint_reset-state.html">und tendermint reset-state</RouterLink>	 - Remove all the data and WAL</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tendermint_show-address.html">und tendermint show-address</RouterLink>	 - Shows this node's tendermint validator consensus address</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tendermint_show-node-id.html">und tendermint show-node-id</RouterLink>	 - Show this node's ID</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tendermint_show-validator.html">und tendermint show-validator</RouterLink>	 - Show this node's tendermint validator info</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tendermint_unsafe-reset-all.html">und tendermint unsafe-reset-all</RouterLink>	 - (unsafe) Remove all the data and WAL, reset this node's validator to genesis state</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tendermint_version.html">und tendermint version</RouterLink>	 - Print tendermint libraries' version</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
