<template><div><h2 id="und-tx-staking" tabindex="-1"><a class="header-anchor" href="#und-tx-staking" aria-hidden="true">#</a> und tx staking</h2>
<p>Staking transaction subcommands</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und tx staking [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for staking
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx.html">und tx</RouterLink>	 - Transactions subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_staking_create-validator.html">und tx staking create-validator</RouterLink>	 - create new validator initialized with a self-delegation to it</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_staking_delegate.html">und tx staking delegate</RouterLink>	 - Delegate liquid tokens to a validator</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_staking_edit-validator.html">und tx staking edit-validator</RouterLink>	 - edit an existing validator account</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_staking_redelegate.html">und tx staking redelegate</RouterLink>	 - Redelegate illiquid tokens from one validator to another</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_staking_unbond.html">und tx staking unbond</RouterLink>	 - Unbond shares from a validator</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
