<template><div><h2 id="und-query-beacon" tabindex="-1"><a class="header-anchor" href="#und-query-beacon" aria-hidden="true">#</a> und query beacon</h2>
<p>Querying commands for the beacon module</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und query beacon [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for beacon
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_query.html">und query</RouterLink>	 - Querying subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_beacon_beacon.html">und query beacon beacon</RouterLink>	 - Query a BEACON for given ID</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_beacon_params.html">und query beacon params</RouterLink>	 - Query the current Beacon parameters</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_beacon_search.html">und query beacon search</RouterLink>	 - Query all BEACONs with optional filters</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_beacon_storage.html">und query beacon storage</RouterLink>	 - Query a BEACON for given ID to retrieve storage info</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_beacon_timestamp.html">und query beacon timestamp</RouterLink>	 - Query a BEACON for given ID and timestamp ID to retrieve recorded timestamp</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
