<template><div><h2 id="und-keys" tabindex="-1"><a class="header-anchor" href="#und-keys" aria-hidden="true">#</a> und keys</h2>
<p>Manage your application's keys</p>
<h3 id="synopsis" tabindex="-1"><a class="header-anchor" href="#synopsis" aria-hidden="true">#</a> Synopsis</h3>
<p>Keyring management commands. These keys may be in any format supported by the
Tendermint crypto library and can be used by light-clients, full nodes, or any other application
that needs to sign with a private key.</p>
<p>The keyring supports the following backends:</p>
<pre><code>os          Uses the operating system's default credentials store.
file        Uses encrypted file-based keystore within the app's configuration directory.
            This keyring will request a password each time it is accessed, which may occur
            multiple times in a single command resulting in repeated password prompts.
kwallet     Uses KDE Wallet Manager as a credentials management application.
pass        Uses the pass command line utility to store and retrieve keys.
test        Stores keys insecurely to disk. It does not prompt for a password to be unlocked
            and it should be use only for testing purposes.
</code></pre>
<p>kwallet and pass backends depend on external tools. Refer to their respective documentation for more
information:
KWallet     https://github.com/KDE/kwallet
pass        https://www.passwordstore.org/</p>
<p>The pass backend requires GnuPG: https://gnupg.org/</p>
<h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help                     help for keys
      --home string              The application home directory (default "/home/hodge/.und_mainchain")
      --keyring-backend string   Select keyring's backend (os|file|test) (default "os")
      --keyring-dir string       The client Keyring directory; if omitted, the default 'home' directory will be used
      --output string            Output format (text|json) (default "text")
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und.html">und</RouterLink>	 - Unification Mainchain App</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_keys_add.html">und keys add</RouterLink>	 - Add an encrypted private key (either newly generated or recovered), encrypt it, and save to 〈name〉 file</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_keys_delete.html">und keys delete</RouterLink>	 - Delete the given keys</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_keys_export.html">und keys export</RouterLink>	 - Export private keys</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_keys_import.html">und keys import</RouterLink>	 - Import private keys into the local keybase</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_keys_list.html">und keys list</RouterLink>	 - List all keys</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_keys_migrate.html">und keys migrate</RouterLink>	 - Migrate keys from the legacy (db-based) Keybase</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_keys_mnemonic.html">und keys mnemonic</RouterLink>	 - Compute the bip39 mnemonic for some input entropy</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_keys_parse.html">und keys parse</RouterLink>	 - Parse address from hex to bech32 and vice versa</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_keys_show.html">und keys show</RouterLink>	 - Retrieve key information by name or address</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
