<template><div><h2 id="und-rosetta" tabindex="-1"><a class="header-anchor" href="#und-rosetta" aria-hidden="true">#</a> und rosetta</h2>
<p>spin up a rosetta server</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und rosetta [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --addr string         the address rosetta will bind to (default ":8080")
      --blockchain string   the blockchain type (default "app")
      --grpc string         the app gRPC endpoint (default "localhost:9090")
  -h, --help                help for rosetta
      --network string      the network name (default "network")
      --offline             run rosetta only with construction API
      --retries int         the number of retries that will be done before quitting (default 5)
      --tendermint string   the tendermint rpc endpoint, without tcp:// (default "localhost:26657")
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und.html">und</RouterLink>	 - Unification Mainchain App</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
