<template><div><h2 id="und-tendermint-unsafe-reset-all" tabindex="-1"><a class="header-anchor" href="#und-tendermint-unsafe-reset-all" aria-hidden="true">#</a> und tendermint unsafe-reset-all</h2>
<p>(unsafe) Remove all the data and WAL, reset this node's validator to genesis state</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und tendermint unsafe-reset-all [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help             help for unsafe-reset-all
      --keep-addr-book   keep the address book intact
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_tendermint.html">und tendermint</RouterLink>	 - Tendermint subcommands</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
