<template><div><h2 id="und-debug" tabindex="-1"><a class="header-anchor" href="#und-debug" aria-hidden="true">#</a> und debug</h2>
<p>Tool for helping with debugging your application</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und debug [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for debug
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und.html">und</RouterLink>	 - Unification Mainchain App</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_debug_addr.html">und debug addr</RouterLink>	 - Convert an address between hex and bech32</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_debug_pubkey.html">und debug pubkey</RouterLink>	 - Decode a pubkey from proto JSON</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_debug_raw-bytes.html">und debug raw-bytes</RouterLink>	 - Convert raw bytes output (eg. [10 21 13 255]) to hex</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
