<template><div><h2 id="und-validate-genesis" tabindex="-1"><a class="header-anchor" href="#und-validate-genesis" aria-hidden="true">#</a> und validate-genesis</h2>
<p>validates the genesis file at the default location or at the location passed as an arg</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und validate-genesis [file] [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for validate-genesis
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und.html">und</RouterLink>	 - Unification Mainchain App</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
