<template><div><h2 id="und-debug-raw-bytes" tabindex="-1"><a class="header-anchor" href="#und-debug-raw-bytes" aria-hidden="true">#</a> und debug raw-bytes</h2>
<p>Convert raw bytes output (eg. [10 21 13 255]) to hex</p>
<h3 id="synopsis" tabindex="-1"><a class="header-anchor" href="#synopsis" aria-hidden="true">#</a> Synopsis</h3>
<p>Convert raw-bytes to hex.</p>
<p>Example:
$ und debug raw-bytes [72 101 108 108 111 44 32 112 108 97 121 103 114 111 117 110 100]</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und debug raw-bytes [raw-bytes] [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for raw-bytes
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_debug.html">und debug</RouterLink>	 - Tool for helping with debugging your application</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
