<template><div><h2 id="und-query-wrkchain" tabindex="-1"><a class="header-anchor" href="#und-query-wrkchain" aria-hidden="true">#</a> und query wrkchain</h2>
<p>Querying commands for the wrkchain module</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und query wrkchain [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for wrkchain
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_query.html">und query</RouterLink>	 - Querying subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_wrkchain_block.html">und query wrkchain block</RouterLink>	 - Query a WRKChain for given ID and block height to retrieve recorded hashes for that block</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_wrkchain_params.html">und query wrkchain params</RouterLink>	 - Query the current WRKChain parameters</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_wrkchain_search.html">und query wrkchain search</RouterLink>	 - Query all WRKChains with optional filters</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_wrkchain_storage.html">und query wrkchain storage</RouterLink>	 - Query a WrkChain for given ID to retrieve storage info</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_wrkchain_wrkchain.html">und query wrkchain wrkchain</RouterLink>	 - Query a WRKChain for given ID</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
