<template><div><h2 id="und-query-gov" tabindex="-1"><a class="header-anchor" href="#und-query-gov" aria-hidden="true">#</a> und query gov</h2>
<p>Querying commands for the governance module</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und query gov [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for gov
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_query.html">und query</RouterLink>	 - Querying subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_gov_deposit.html">und query gov deposit</RouterLink>	 - Query details of a deposit</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_gov_deposits.html">und query gov deposits</RouterLink>	 - Query deposits on a proposal</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_gov_param.html">und query gov param</RouterLink>	 - Query the parameters (voting|tallying|deposit) of the governance process</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_gov_params.html">und query gov params</RouterLink>	 - Query the parameters of the governance process</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_gov_proposal.html">und query gov proposal</RouterLink>	 - Query details of a single proposal</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_gov_proposals.html">und query gov proposals</RouterLink>	 - Query proposals with optional filters</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_gov_proposer.html">und query gov proposer</RouterLink>	 - Query the proposer of a governance proposal</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_gov_tally.html">und query gov tally</RouterLink>	 - Get the tally of a proposal vote</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_gov_vote.html">und query gov vote</RouterLink>	 - Query details of a single vote</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_gov_votes.html">und query gov votes</RouterLink>	 - Query votes on a proposal</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
