<template><div><h2 id="und-query-enterprise-orders" tabindex="-1"><a class="header-anchor" href="#und-query-enterprise-orders" aria-hidden="true">#</a> und query enterprise orders</h2>
<p>Query Enterprise FUND purchase orders with optional filters</p>
<h3 id="synopsis" tabindex="-1"><a class="header-anchor" href="#synopsis" aria-hidden="true">#</a> Synopsis</h3>
<p>Query for a all paginated Enterprise FUND purchase orders that match optional filters:</p>
<p>Example:
$ und query enterprise orders --status (raised|accept|reject|complete)
$ und query enterprise orders --purchaser und1chknpc8nf2tmj5582vhlvphnjyekc9ypspx5ay
$ und query enterprise orders --page=2 --limit=100</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und query enterprise orders [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --count-total        count total number of records in purchase orders to query for
      --height int         Use a specific height to query state at (this can error if the node is pruning state)
  -h, --help               help for orders
      --limit uint         pagination limit of purchase orders to query for (default 100)
      --node string        &amp;#9001;host&amp;#9002;:&amp;#9001;port&amp;#9002; to Tendermint RPC interface for this chain (default "tcp://localhost:26657")
      --offset uint        pagination offset of purchase orders to query for
  -o, --output string      Output format (text|json) (default "text")
      --page uint          pagination page of purchase orders to query for. This sets offset to a multiple of limit (default 1)
      --page-key string    pagination page-key of purchase orders to query for
      --purchaser string   (optional) filter purchase orders raised by address
      --reverse            results are sorted in descending order
      --status string      (optional) filter purchase orders by status, status: raised/accept/reject/complete
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_enterprise.html">und query enterprise</RouterLink>	 - Querying commands for the enterprise module</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
