<template><div><h2 id="und-tx" tabindex="-1"><a class="header-anchor" href="#und-tx" aria-hidden="true">#</a> und tx</h2>
<p>Transactions subcommands</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und tx [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
  -h, --help              help for tx
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und.html">und</RouterLink>	 - Unification Mainchain App</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_authz.html">und tx authz</RouterLink>	 - Authorization transactions subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_bank.html">und tx bank</RouterLink>	 - Bank transaction subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_beacon.html">und tx beacon</RouterLink>	 - Beacon transaction subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_broadcast.html">und tx broadcast</RouterLink>	 - Broadcast transactions generated offline</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_crisis.html">und tx crisis</RouterLink>	 - Crisis transactions subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_decode.html">und tx decode</RouterLink>	 - Decode a binary encoded transaction string</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_distribution.html">und tx distribution</RouterLink>	 - Distribution transactions subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_encode.html">und tx encode</RouterLink>	 - Encode transactions generated offline</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_enterprise.html">und tx enterprise</RouterLink>	 - Enterprise FUND transaction subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_evidence.html">und tx evidence</RouterLink>	 - Evidence transaction subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_feegrant.html">und tx feegrant</RouterLink>	 - Feegrant transactions subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_gov.html">und tx gov</RouterLink>	 - Governance transactions subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_ibc.html">und tx ibc</RouterLink>	 - IBC transaction subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_ibc-transfer.html">und tx ibc-transfer</RouterLink>	 - IBC fungible token transfer transaction subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_multisign.html">und tx multisign</RouterLink>	 - Generate multisig signatures for transactions generated offline</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_multisign-batch.html">und tx multisign-batch</RouterLink>	 - Assemble multisig transactions in batch from batch signatures</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_sign.html">und tx sign</RouterLink>	 - Sign a transaction generated offline</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_sign-batch.html">und tx sign-batch</RouterLink>	 - Sign transaction batch files</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_slashing.html">und tx slashing</RouterLink>	 - Slashing transaction subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_staking.html">und tx staking</RouterLink>	 - Staking transaction subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_validate-signatures.html">und tx validate-signatures</RouterLink>	 - validate transactions signatures</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_vesting.html">und tx vesting</RouterLink>	 - Vesting transaction subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_vesting.html">und tx vesting</RouterLink>	 - Vesting transaction subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_wrkchain.html">und tx wrkchain</RouterLink>	 - WRKChain transaction subcommands</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
