<template><div><h2 id="und-query-wrkchain-search" tabindex="-1"><a class="header-anchor" href="#und-query-wrkchain-search" aria-hidden="true">#</a> und query wrkchain search</h2>
<p>Query all WRKChains with optional filters</p>
<h3 id="synopsis" tabindex="-1"><a class="header-anchor" href="#synopsis" aria-hidden="true">#</a> Synopsis</h3>
<p>Query for all paginated WRKChains that match optional filters:</p>
<p>Example:
$ und query wrkchain search --moniker wrkchain1
$ und query wrkchain search --owner und1chknpc8nf2tmj5582vhlvphnjyekc9ypspx5ay
$ und query wrkchain search --page=2 --limit=100</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und query wrkchain search [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --height int       Use a specific height to query state at (this can error if the node is pruning state)
  -h, --help             help for search
      --moniker string   (optional) filter wrkchains by name
      --node string      &amp;#9001;host&amp;#9002;:&amp;#9001;port&amp;#9002; to Tendermint RPC interface for this chain (default "tcp://localhost:26657")
  -o, --output string    Output format (text|json) (default "text")
      --owner string     (optional) filter wrkchains by owner address
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_wrkchain.html">und query wrkchain</RouterLink>	 - Querying commands for the wrkchain module</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
