<template><div><h2 id="und-query-enterprise" tabindex="-1"><a class="header-anchor" href="#und-query-enterprise" aria-hidden="true">#</a> und query enterprise</h2>
<p>Querying commands for the enterprise module</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und query enterprise [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for enterprise
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_query.html">und query</RouterLink>	 - Querying subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_enterprise_account.html">und query enterprise account</RouterLink>	 - get data about an address - locked, unlocked and total FUND</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_enterprise_ent-supply.html">und query enterprise ent-supply</RouterLink>	 - get eFUND data, including locked, unlocked and chain total supply</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_enterprise_locked.html">und query enterprise locked</RouterLink>	 - get locked FUND for an address</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_enterprise_order.html">und query enterprise order</RouterLink>	 - get a purchase order by ID</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_enterprise_orders.html">und query enterprise orders</RouterLink>	 - Query Enterprise FUND purchase orders with optional filters</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_enterprise_params.html">und query enterprise params</RouterLink>	 - Query the current enterprise FUND parameters</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_enterprise_spent.html">und query enterprise spent</RouterLink>	 - get spent eFUND for an address</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_enterprise_total-locked.html">und query enterprise total-locked</RouterLink>	 - Query the current total locked enterprise FUND</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_enterprise_total-spent.html">und query enterprise total-spent</RouterLink>	 - Query the current total spent eFUND</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_enterprise_total-unlocked.html">und query enterprise total-unlocked</RouterLink>	 - Query the current total unlocked und in circulation</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_enterprise_whitelist.html">und query enterprise whitelist</RouterLink>	 - get addresses whitelisted for raising enterprise purchase orders</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_enterprise_whitelisted.html">und query enterprise whitelisted</RouterLink>	 - check if given address is whitelested for purchase orders</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
