<template><div><h2 id="und-query-bank" tabindex="-1"><a class="header-anchor" href="#und-query-bank" aria-hidden="true">#</a> und query bank</h2>
<p>Querying commands for the bank module</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und query bank [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for bank
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_query.html">und query</RouterLink>	 - Querying subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_bank_balances.html">und query bank balances</RouterLink>	 - Query for account balances by address</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_bank_denom-metadata.html">und query bank denom-metadata</RouterLink>	 - Query the client metadata for coin denominations</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_bank_total.html">und query bank total</RouterLink>	 - Query the total supply of coins of the chain</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
