<template><div><h2 id="und-tx-wrkchain" tabindex="-1"><a class="header-anchor" href="#und-tx-wrkchain" aria-hidden="true">#</a> und tx wrkchain</h2>
<p>WRKChain transaction subcommands</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und tx wrkchain [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for wrkchain
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx.html">und tx</RouterLink>	 - Transactions subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_wrkchain_purchase_storage.html">und tx wrkchain purchase_storage</RouterLink>	 - purchase more in-state storage for a WrkChain</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_wrkchain_record.html">und tx wrkchain record</RouterLink>	 - record a WRKChain's block hashes</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_wrkchain_register.html">und tx wrkchain register</RouterLink>	 - register a new WRKChain</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
