<template><div><h2 id="und-query-ibc-client" tabindex="-1"><a class="header-anchor" href="#und-query-ibc-client" aria-hidden="true">#</a> und query ibc client</h2>
<p>IBC client query subcommands</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und query ibc client [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for client
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc.html">und query ibc</RouterLink>	 - Querying commands for the IBC module</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_client_consensus-state.html">und query ibc client consensus-state</RouterLink>	 - Query the consensus state of a client at a given height</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_client_consensus-state-heights.html">und query ibc client consensus-state-heights</RouterLink>	 - Query the heights of all consensus states of a client.</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_client_consensus-states.html">und query ibc client consensus-states</RouterLink>	 - Query all the consensus states of a client.</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_client_header.html">und query ibc client header</RouterLink>	 - Query the latest header of the running chain</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_client_params.html">und query ibc client params</RouterLink>	 - Query the current ibc client parameters</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_client_self-consensus-state.html">und query ibc client self-consensus-state</RouterLink>	 - Query the self consensus state for this chain</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_client_state.html">und query ibc client state</RouterLink>	 - Query a client state</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_client_states.html">und query ibc client states</RouterLink>	 - Query all available light clients</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_client_status.html">und query ibc client status</RouterLink>	 - Query client status</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
