<template><div><h2 id="und-tx-beacon" tabindex="-1"><a class="header-anchor" href="#und-tx-beacon" aria-hidden="true">#</a> und tx beacon</h2>
<p>Beacon transaction subcommands</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und tx beacon [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for beacon
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx.html">und tx</RouterLink>	 - Transactions subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_beacon_purchase_storage.html">und tx beacon purchase_storage</RouterLink>	 - purchase more in-state storage for a BEACON</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_beacon_record.html">und tx beacon record</RouterLink>	 - record a BEACON's timestamp hash</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_beacon_register.html">und tx beacon register</RouterLink>	 - register a new BEACON</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
