<template><div><h2 id="und-debug-addr" tabindex="-1"><a class="header-anchor" href="#und-debug-addr" aria-hidden="true">#</a> und debug addr</h2>
<p>Convert an address between hex and bech32</p>
<h3 id="synopsis" tabindex="-1"><a class="header-anchor" href="#synopsis" aria-hidden="true">#</a> Synopsis</h3>
<p>Convert an address between hex encoding and bech32.</p>
<p>Example:
$ und debug addr cosmos1e0jnq2sun3dzjh8p2xq95kk0expwmd7shwjpfg</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und debug addr [address] [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for addr
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_debug.html">und debug</RouterLink>	 - Tool for helping with debugging your application</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
