<template><div><h2 id="und-query-distribution" tabindex="-1"><a class="header-anchor" href="#und-query-distribution" aria-hidden="true">#</a> und query distribution</h2>
<p>Querying commands for the distribution module</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und query distribution [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for distribution
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_query.html">und query</RouterLink>	 - Querying subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_distribution_commission.html">und query distribution commission</RouterLink>	 - Query distribution validator commission</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_distribution_community-pool.html">und query distribution community-pool</RouterLink>	 - Query the amount of coins in the community pool</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_distribution_params.html">und query distribution params</RouterLink>	 - Query distribution params</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_distribution_rewards.html">und query distribution rewards</RouterLink>	 - Query all distribution delegator rewards or rewards from a particular validator</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_distribution_slashes.html">und query distribution slashes</RouterLink>	 - Query distribution validator slashes</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_distribution_validator-outstanding-rewards.html">und query distribution validator-outstanding-rewards</RouterLink>	 - Query distribution outstanding (un-withdrawn) rewards for a validator and all their delegations</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
