<template><div><h2 id="und-query-staking" tabindex="-1"><a class="header-anchor" href="#und-query-staking" aria-hidden="true">#</a> und query staking</h2>
<p>Querying commands for the staking module</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und query staking [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for staking
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_query.html">und query</RouterLink>	 - Querying subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_staking_delegation.html">und query staking delegation</RouterLink>	 - Query a delegation based on address and validator address</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_staking_delegations.html">und query staking delegations</RouterLink>	 - Query all delegations made by one delegator</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_staking_delegations-to.html">und query staking delegations-to</RouterLink>	 - Query all delegations made to one validator</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_staking_historical-info.html">und query staking historical-info</RouterLink>	 - Query historical info at given height</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_staking_params.html">und query staking params</RouterLink>	 - Query the current staking parameters information</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_staking_pool.html">und query staking pool</RouterLink>	 - Query the current staking pool values</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_staking_redelegation.html">und query staking redelegation</RouterLink>	 - Query a redelegation record based on delegator and a source and destination validator address</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_staking_redelegations.html">und query staking redelegations</RouterLink>	 - Query all redelegations records for one delegator</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_staking_redelegations-from.html">und query staking redelegations-from</RouterLink>	 - Query all outgoing redelegatations from a validator</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_staking_unbonding-delegation.html">und query staking unbonding-delegation</RouterLink>	 - Query an unbonding-delegation record based on delegator and validator address</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_staking_unbonding-delegations.html">und query staking unbonding-delegations</RouterLink>	 - Query all unbonding-delegations records for one delegator</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_staking_unbonding-delegations-from.html">und query staking unbonding-delegations-from</RouterLink>	 - Query all unbonding delegatations from a validator</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_staking_validator.html">und query staking validator</RouterLink>	 - Query a validator</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_staking_validators.html">und query staking validators</RouterLink>	 - Query for all validators</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
