<template><div><h2 id="und-tx-authz" tabindex="-1"><a class="header-anchor" href="#und-tx-authz" aria-hidden="true">#</a> und tx authz</h2>
<p>Authorization transactions subcommands</p>
<h3 id="synopsis" tabindex="-1"><a class="header-anchor" href="#synopsis" aria-hidden="true">#</a> Synopsis</h3>
<p>Authorize and revoke access to execute transactions on behalf of your address</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und tx authz [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for authz
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx.html">und tx</RouterLink>	 - Transactions subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_authz_exec.html">und tx authz exec</RouterLink>	 - execute tx on behalf of granter account</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_authz_grant.html">und tx authz grant</RouterLink>	 - Grant authorization to an address</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_authz_revoke.html">und tx authz revoke</RouterLink>	 - revoke authorization</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
