<template><div><h2 id="und-query-authz" tabindex="-1"><a class="header-anchor" href="#und-query-authz" aria-hidden="true">#</a> und query authz</h2>
<p>Querying commands for the authz module</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und query authz [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for authz
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_query.html">und query</RouterLink>	 - Querying subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_authz_grants.html">und query authz grants</RouterLink>	 - query grants for a granter-grantee pair and optionally a msg-type-url</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_authz_grants-by-grantee.html">und query authz grants-by-grantee</RouterLink>	 - query authorization grants granted to a grantee</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_authz_grants-by-granter.html">und query authz grants-by-granter</RouterLink>	 - query authorization grants granted by granter</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
