<template><div><h2 id="und-tx-gov" tabindex="-1"><a class="header-anchor" href="#und-tx-gov" aria-hidden="true">#</a> und tx gov</h2>
<p>Governance transactions subcommands</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und tx gov [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for gov
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx.html">und tx</RouterLink>	 - Transactions subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_gov_deposit.html">und tx gov deposit</RouterLink>	 - Deposit tokens for an active proposal</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_gov_submit-proposal.html">und tx gov submit-proposal</RouterLink>	 - Submit a proposal along with an initial deposit</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_gov_vote.html">und tx gov vote</RouterLink>	 - Vote for an active proposal, options: yes/no/no_with_veto/abstain</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_gov_weighted-vote.html">und tx gov weighted-vote</RouterLink>	 - Vote for an active proposal, options: yes/no/no_with_veto/abstain</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
