<template><div><h2 id="und-tx-ibc-client" tabindex="-1"><a class="header-anchor" href="#und-tx-ibc-client" aria-hidden="true">#</a> und tx ibc client</h2>
<p>IBC client transaction subcommands</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und tx ibc client [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for client
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_ibc.html">und tx ibc</RouterLink>	 - IBC transaction subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_ibc_client_create.html">und tx ibc client create</RouterLink>	 - create new IBC client</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_ibc_client_misbehaviour.html">und tx ibc client misbehaviour</RouterLink>	 - submit a client misbehaviour</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_ibc_client_update.html">und tx ibc client update</RouterLink>	 - update existing client with a header</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_tx_ibc_client_upgrade.html">und tx ibc client upgrade</RouterLink>	 - upgrade an IBC client</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
