<template><div><h2 id="und-query-ibc" tabindex="-1"><a class="header-anchor" href="#und-query-ibc" aria-hidden="true">#</a> und query ibc</h2>
<p>Querying commands for the IBC module</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>und query ibc [flags]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options" tabindex="-1"><a class="header-anchor" href="#options" aria-hidden="true">#</a> Options</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  -h, --help   help for ibc
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="options-inherited-from-parent-commands" tabindex="-1"><a class="header-anchor" href="#options-inherited-from-parent-commands" aria-hidden="true">#</a> Options inherited from parent commands</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>      --chain-id string   The network chain ID
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="see-also" tabindex="-1"><a class="header-anchor" href="#see-also" aria-hidden="true">#</a> SEE ALSO</h3>
<ul>
<li><RouterLink to="/mainchain/software/und_cmd/und_query.html">und query</RouterLink>	 - Querying subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_channel.html">und query ibc channel</RouterLink>	 - IBC channel query subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_client.html">und query ibc client</RouterLink>	 - IBC client query subcommands</li>
<li><RouterLink to="/mainchain/software/und_cmd/und_query_ibc_connection.html">und query ibc connection</RouterLink>	 - IBC connection query subcommands</li>
</ul>
<h6 id="auto-generated-by-spf13-cobra-on-22-jul-2022" tabindex="-1"><a class="header-anchor" href="#auto-generated-by-spf13-cobra-on-22-jul-2022" aria-hidden="true">#</a> Auto generated by spf13/cobra on 22-Jul-2022</h6>
</div></template>
