export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":""},["/index.html","/index.md"]],
  ["v-06696840","/mainchain/",{"title":"Unification Mainchain Documentation"},["/mainchain/index.html","/mainchain/README.md"]],
  ["v-744af1f9","/ooo/",{"title":"OoO Introduction"},["/ooo/index.html","/ooo/README.md"]],
  ["v-e872d3de","/ooo/contracts.html",{"title":"OoO Contract Addresses"},["/ooo/contracts","/ooo/contracts.md"]],
  ["v-e587b0a0","/ooo/providers.html",{"title":"OoO Providers"},["/ooo/providers","/ooo/providers.md"]],
  ["v-744e20ef","/vor/",{"title":"VOR Introduction"},["/vor/index.html","/vor/README.md"]],
  ["v-df0d42f2","/vor/contracts.html",{"title":"VOR Contract Addresses"},["/vor/contracts","/vor/contracts.md"]],
  ["v-dc221fb4","/vor/providers.html",{"title":"VOR Provider Oracles"},["/vor/providers","/vor/providers.md"]],
  ["v-2a733602","/mainchain/developers/third-party.html",{"title":"Third Party Tool Development"},["/mainchain/developers/third-party","/mainchain/developers/third-party.md"]],
  ["v-4c5a9a8f","/mainchain/examples/beacon.html",{"title":"BEACON Example"},["/mainchain/examples/beacon","/mainchain/examples/beacon.md"]],
  ["v-346b4f8e","/mainchain/examples/enterprise-fund.html",{"title":"Enterprise FUND Example"},["/mainchain/examples/enterprise-fund","/mainchain/examples/enterprise-fund.md"]],
  ["v-40615c9e","/mainchain/examples/transactions.html",{"title":"Sending Simple Transactions"},["/mainchain/examples/transactions","/mainchain/examples/transactions.md"]],
  ["v-48f400a2","/mainchain/examples/wrkchain.html",{"title":"WRKChain Example"},["/mainchain/examples/wrkchain","/mainchain/examples/wrkchain.md"]],
  ["v-7b931a06","/mainchain/introduction/about-mainchain.html",{"title":"What is Mainchain?"},["/mainchain/introduction/about-mainchain","/mainchain/introduction/about-mainchain.md"]],
  ["v-7f40a1d8","/mainchain/introduction/delegators.html",{"title":"Introduction to Delegators and Staking"},["/mainchain/introduction/delegators","/mainchain/introduction/delegators.md"]],
  ["v-3762959f","/mainchain/introduction/denomination.html",{"title":"Native Coin Denomination nund"},["/mainchain/introduction/denomination","/mainchain/introduction/denomination.md"]],
  ["v-9d2a2132","/mainchain/introduction/faqs.html",{"title":"Frequently Asked Questions"},["/mainchain/introduction/faqs","/mainchain/introduction/faqs.md"]],
  ["v-6b381e81","/mainchain/introduction/fees-and-gas.html",{"title":"Fees and Gas"},["/mainchain/introduction/fees-and-gas","/mainchain/introduction/fees-and-gas.md"]],
  ["v-9332c188","/mainchain/introduction/genesis-settings.html",{"title":"Genesis Settings & Parameters"},["/mainchain/introduction/genesis-settings","/mainchain/introduction/genesis-settings.md"]],
  ["v-0eee3dcc","/mainchain/introduction/total-supply.html",{"title":"Total Supply"},["/mainchain/introduction/total-supply","/mainchain/introduction/total-supply.md"]],
  ["v-2b23033a","/mainchain/introduction/validators.html",{"title":"Introduction to Validators"},["/mainchain/introduction/validators","/mainchain/introduction/validators.md"]],
  ["v-32e1f5b8","/mainchain/migrations/1-ibc_upgrade.html",{"title":"Network Upgrade: 1-ibc"},["/mainchain/migrations/1-ibc_upgrade","/mainchain/migrations/1-ibc_upgrade.md"]],
  ["v-7e07762a","/mainchain/migrations/",{"title":"Introduction"},["/mainchain/migrations/index.html","/mainchain/migrations/README.md"]],
  ["v-f7bc7116","/mainchain/migrations/cosmovisor.html",{"title":"Using Cosmovisor with und: Quick Start"},["/mainchain/migrations/cosmovisor","/mainchain/migrations/cosmovisor.md"]],
  ["v-1ee54343","/mainchain/networks/become-validator.html",{"title":"Becoming a Validator"},["/mainchain/networks/become-validator","/mainchain/networks/become-validator.md"]],
  ["v-ecf30038","/mainchain/networks/join-network.html",{"title":"Run a Full Node & Join a Public Network"},["/mainchain/networks/join-network","/mainchain/networks/join-network.md"]],
  ["v-481c0b7c","/mainchain/networks/participation.html",{"title":"Non-Validator Participation"},["/mainchain/networks/participation","/mainchain/networks/participation.md"]],
  ["v-99cec34e","/mainchain/partials/download-genesis.html",{"title":""},["/mainchain/partials/download-genesis","/mainchain/partials/download-genesis.md"]],
  ["v-a36735fe","/mainchain/partials/gas-price.html",{"title":""},["/mainchain/partials/gas-price","/mainchain/partials/gas-price.md"]],
  ["v-589c5fa7","/mainchain/partials/install-und-binary.html",{"title":""},["/mainchain/partials/install-und-binary","/mainchain/partials/install-und-binary.md"]],
  ["v-000378e7","/mainchain/partials/seed-nodes.html",{"title":""},["/mainchain/partials/seed-nodes","/mainchain/partials/seed-nodes.md"]],
  ["v-e1f4fbec","/mainchain/partials/statesync.html",{"title":""},["/mainchain/partials/statesync","/mainchain/partials/statesync.md"]],
  ["v-766f6899","/mainchain/partials/systemd-service.html",{"title":""},["/mainchain/partials/systemd-service","/mainchain/partials/systemd-service.md"]],
  ["v-12de09de","/mainchain/software/accounts-wallets.html",{"title":"Accounts and Wallets"},["/mainchain/software/accounts-wallets","/mainchain/software/accounts-wallets.md"]],
  ["v-97f28e92","/mainchain/software/installation.html",{"title":"Installing the Mainchain Software"},["/mainchain/software/installation","/mainchain/software/installation.md"]],
  ["v-e1379e12","/mainchain/software/light-client-rpc.html",{"title":"Light Client/REST"},["/mainchain/software/light-client-rpc","/mainchain/software/light-client-rpc.md"]],
  ["v-26cce1b3","/mainchain/software/run-und-as-service.html",{"title":"Running und as a background service"},["/mainchain/software/run-und-as-service","/mainchain/software/run-und-as-service.md"]],
  ["v-32d82b14","/mainchain/software/und-mainchain-app-config-ref.html",{"title":"app.toml Reference"},["/mainchain/software/und-mainchain-app-config-ref","/mainchain/software/und-mainchain-app-config-ref.md"]],
  ["v-4c018a44","/mainchain/software/und-mainchain-client-config-ref.html",{"title":"client.toml Reference"},["/mainchain/software/und-mainchain-client-config-ref","/mainchain/software/und-mainchain-client-config-ref.md"]],
  ["v-3d9d62a2","/mainchain/software/und-mainchain-config-ref.html",{"title":"config.toml Reference"},["/mainchain/software/und-mainchain-config-ref","/mainchain/software/und-mainchain-config-ref.md"]],
  ["v-183bb382","/ooo/api/Router.html",{"title":"OoO Router smart contract"},["/ooo/api/Router","/ooo/api/Router.md"]],
  ["v-7ce6f7ec","/ooo/guide/",{"title":"OoO Complete Deployment Guide"},["/ooo/guide/index.html","/ooo/guide/README.md"]],
  ["v-54565cfb","/ooo/guide/implementation.html",{"title":"OoO Implementation & Integration Guide"},["/ooo/guide/implementation","/ooo/guide/implementation.md"]],
  ["v-e26fe41a","/ooo/guide/interaction.html",{"title":"OoO Contract Initialisation and Data Request Guide"},["/ooo/guide/interaction","/ooo/guide/interaction.md"]],
  ["v-a5541eca","/ooo/guide/ooo_api.html",{"title":"OoO Data API Guide"},["/ooo/guide/ooo_api","/ooo/guide/ooo_api.md"]],
  ["v-d2b20410","/ooo/guide/quickstart.html",{"title":"OoO Quickstart"},["/ooo/guide/quickstart","/ooo/guide/quickstart.md"]],
  ["v-865252f8","/vor/api/VOR.html",{"title":"VOR"},["/vor/api/VOR","/vor/api/VOR.md"]],
  ["v-3f199b46","/vor/api/VORConsumerBase.html",{"title":"VORConsumerBase"},["/vor/api/VORConsumerBase","/vor/api/VORConsumerBase.md"]],
  ["v-6f4c893e","/vor/api/VORCoordinator.html",{"title":"VORCoordinator"},["/vor/api/VORCoordinator","/vor/api/VORCoordinator.md"]],
  ["v-4413c79a","/vor/api/VORRequestIDBase.html",{"title":"VORRequestIDBase"},["/vor/api/VORRequestIDBase","/vor/api/VORRequestIDBase.md"]],
  ["v-5c8e90ee","/vor/demos/",{"title":"VOR Demos"},["/vor/demos/index.html","/vor/demos/README.md"]],
  ["v-defff836","/vor/demos/nft_demo.html",{"title":"VOR NFT Competition Demo"},["/vor/demos/nft_demo","/vor/demos/nft_demo.md"]],
  ["v-628c9662","/vor/guide/",{"title":"VOR Complete Deployment Guide"},["/vor/guide/index.html","/vor/guide/README.md"]],
  ["v-e8141256","/vor/guide/advanced.html",{"title":"Advanced topics"},["/vor/guide/advanced","/vor/guide/advanced.md"]],
  ["v-2178cec5","/vor/guide/implementation.html",{"title":"VOR Full implementation example"},["/vor/guide/implementation","/vor/guide/implementation.md"]],
  ["v-e083ff2e","/vor/guide/interaction.html",{"title":"VOR Interacting with the DnD example"},["/vor/guide/interaction","/vor/guide/interaction.md"]],
  ["v-ee220b0e","/vor/guide/oracle.html",{"title":"VOR Running an Oracle"},["/vor/guide/oracle","/vor/guide/oracle.md"]],
  ["v-128de4c2","/vor/guide/quickstart.html",{"title":"VOR Quickstart"},["/vor/guide/quickstart","/vor/guide/quickstart.md"]],
  ["v-21123740","/mainchain/guides/cloud/install-aws.html",{"title":"AWS 101"},["/mainchain/guides/cloud/install-aws","/mainchain/guides/cloud/install-aws.md"]],
  ["v-77150ece","/mainchain/guides/cloud/install-gc.html",{"title":"Google Cloud 101"},["/mainchain/guides/cloud/install-gc","/mainchain/guides/cloud/install-gc.md"]],
  ["v-2e25e873","/mainchain/networks/devnet/local-devnet-docker.html",{"title":"3-Node Docker DevNet"},["/mainchain/networks/devnet/local-devnet-docker","/mainchain/networks/devnet/local-devnet-docker.md"]],
  ["v-ec779924","/mainchain/networks/devnet/single-node-devnet.html",{"title":"Single Node DevNet"},["/mainchain/networks/devnet/single-node-devnet","/mainchain/networks/devnet/single-node-devnet.md"]],
  ["v-0fcc9b30","/ooo/api/examples/DemoConsumer.html",{"title":"OoO Data Consumer Demo"},["/ooo/api/examples/DemoConsumer","/ooo/api/examples/DemoConsumer.md"]],
  ["v-0eb95038","/ooo/api/examples/DemoConsumer2.html",{"title":"OoO Data Consumer Demo"},["/ooo/api/examples/DemoConsumer2","/ooo/api/examples/DemoConsumer2.md"]],
  ["v-3029ebcc","/ooo/api/lib/ConsumerBase.html",{"title":"OoO ConsumerBase smart contract"},["/ooo/api/lib/ConsumerBase","/ooo/api/lib/ConsumerBase.md"]],
  ["v-4ea75ff6","/ooo/api/lib/RequestIdBase.html",{"title":"OoO RequestIdBase"},["/ooo/api/lib/RequestIdBase","/ooo/api/lib/RequestIdBase.md"]],
  ["v-1b032db5","/vor/api/dev/BlockhashStore.html",{"title":"BlockhashStore"},["/vor/api/dev/BlockhashStore","/vor/api/dev/BlockhashStore.md"]],
  ["v-b35bd402","/mainchain/software/und_cmd/und.html",{"title":""},["/mainchain/software/und_cmd/und","/mainchain/software/und_cmd/und.md"]],
  ["v-75ba0bfc","/mainchain/software/und_cmd/und_add-genesis-account.html",{"title":""},["/mainchain/software/und_cmd/und_add-genesis-account","/mainchain/software/und_cmd/und_add-genesis-account.md"]],
  ["v-5a4ef652","/mainchain/software/und_cmd/und_collect-gentxs.html",{"title":""},["/mainchain/software/und_cmd/und_collect-gentxs","/mainchain/software/und_cmd/und_collect-gentxs.md"]],
  ["v-406a0932","/mainchain/software/und_cmd/und_config.html",{"title":""},["/mainchain/software/und_cmd/und_config","/mainchain/software/und_cmd/und_config.md"]],
  ["v-2bba740b","/mainchain/software/und_cmd/und_convert.html",{"title":""},["/mainchain/software/und_cmd/und_convert","/mainchain/software/und_cmd/und_convert.md"]],
  ["v-68ee46aa","/mainchain/software/und_cmd/und_debug.html",{"title":""},["/mainchain/software/und_cmd/und_debug","/mainchain/software/und_cmd/und_debug.md"]],
  ["v-1e686577","/mainchain/software/und_cmd/und_debug_addr.html",{"title":""},["/mainchain/software/und_cmd/und_debug_addr","/mainchain/software/und_cmd/und_debug_addr.md"]],
  ["v-e1d143f4","/mainchain/software/und_cmd/und_debug_pubkey.html",{"title":""},["/mainchain/software/und_cmd/und_debug_pubkey","/mainchain/software/und_cmd/und_debug_pubkey.md"]],
  ["v-4acb8184","/mainchain/software/und_cmd/und_debug_raw-bytes.html",{"title":""},["/mainchain/software/und_cmd/und_debug_raw-bytes","/mainchain/software/und_cmd/und_debug_raw-bytes.md"]],
  ["v-7afa2000","/mainchain/software/und_cmd/und_export.html",{"title":""},["/mainchain/software/und_cmd/und_export","/mainchain/software/und_cmd/und_export.md"]],
  ["v-6f0f71ca","/mainchain/software/und_cmd/und_gentx.html",{"title":""},["/mainchain/software/und_cmd/und_gentx","/mainchain/software/und_cmd/und_gentx.md"]],
  ["v-29a9f2e4","/mainchain/software/und_cmd/und_init.html",{"title":""},["/mainchain/software/und_cmd/und_init","/mainchain/software/und_cmd/und_init.md"]],
  ["v-1011cf00","/mainchain/software/und_cmd/und_keys.html",{"title":""},["/mainchain/software/und_cmd/und_keys","/mainchain/software/und_cmd/und_keys.md"]],
  ["v-b2a03b44","/mainchain/software/und_cmd/und_keys_add.html",{"title":""},["/mainchain/software/und_cmd/und_keys_add","/mainchain/software/und_cmd/und_keys_add.md"]],
  ["v-dbe50a70","/mainchain/software/und_cmd/und_keys_delete.html",{"title":""},["/mainchain/software/und_cmd/und_keys_delete","/mainchain/software/und_cmd/und_keys_delete.md"]],
  ["v-580f4a5f","/mainchain/software/und_cmd/und_keys_export.html",{"title":""},["/mainchain/software/und_cmd/und_keys_export","/mainchain/software/und_cmd/und_keys_export.md"]],
  ["v-2c7a390e","/mainchain/software/und_cmd/und_keys_import.html",{"title":""},["/mainchain/software/und_cmd/und_keys_import","/mainchain/software/und_cmd/und_keys_import.md"]],
  ["v-235d1635","/mainchain/software/und_cmd/und_keys_list.html",{"title":""},["/mainchain/software/und_cmd/und_keys_list","/mainchain/software/und_cmd/und_keys_list.md"]],
  ["v-6e2e2ed8","/mainchain/software/und_cmd/und_keys_migrate.html",{"title":""},["/mainchain/software/und_cmd/und_keys_migrate","/mainchain/software/und_cmd/und_keys_migrate.md"]],
  ["v-62bde791","/mainchain/software/und_cmd/und_keys_mnemonic.html",{"title":""},["/mainchain/software/und_cmd/und_keys_mnemonic","/mainchain/software/und_cmd/und_keys_mnemonic.md"]],
  ["v-3524720c","/mainchain/software/und_cmd/und_keys_parse.html",{"title":""},["/mainchain/software/und_cmd/und_keys_parse","/mainchain/software/und_cmd/und_keys_parse.md"]],
  ["v-0a3ee194","/mainchain/software/und_cmd/und_keys_show.html",{"title":""},["/mainchain/software/und_cmd/und_keys_show","/mainchain/software/und_cmd/und_keys_show.md"]],
  ["v-2f329b56","/mainchain/software/und_cmd/und_query.html",{"title":""},["/mainchain/software/und_cmd/und_query","/mainchain/software/und_cmd/und_query.md"]],
  ["v-4e41fbb0","/mainchain/software/und_cmd/und_query_account.html",{"title":""},["/mainchain/software/und_cmd/und_query_account","/mainchain/software/und_cmd/und_query_account.md"]],
  ["v-1c395255","/mainchain/software/und_cmd/und_query_auth.html",{"title":""},["/mainchain/software/und_cmd/und_query_auth","/mainchain/software/und_cmd/und_query_auth.md"]],
  ["v-920b6bb2","/mainchain/software/und_cmd/und_query_auth_account.html",{"title":""},["/mainchain/software/und_cmd/und_query_auth_account","/mainchain/software/und_cmd/und_query_auth_account.md"]],
  ["v-ca529e90","/mainchain/software/und_cmd/und_query_auth_accounts.html",{"title":""},["/mainchain/software/und_cmd/und_query_auth_accounts","/mainchain/software/und_cmd/und_query_auth_accounts.md"]],
  ["v-8bb79750","/mainchain/software/und_cmd/und_query_auth_params.html",{"title":""},["/mainchain/software/und_cmd/und_query_auth_params","/mainchain/software/und_cmd/und_query_auth_params.md"]],
  ["v-2d2acaba","/mainchain/software/und_cmd/und_query_authz.html",{"title":""},["/mainchain/software/und_cmd/und_query_authz","/mainchain/software/und_cmd/und_query_authz.md"]],
  ["v-3e1f2cc6","/mainchain/software/und_cmd/und_query_authz_grants-by-grantee.html",{"title":""},["/mainchain/software/und_cmd/und_query_authz_grants-by-grantee","/mainchain/software/und_cmd/und_query_authz_grants-by-grantee.md"]],
  ["v-544e2cd9","/mainchain/software/und_cmd/und_query_authz_grants-by-granter.html",{"title":""},["/mainchain/software/und_cmd/und_query_authz_grants-by-granter","/mainchain/software/und_cmd/und_query_authz_grants-by-granter.md"]],
  ["v-87d94cce","/mainchain/software/und_cmd/und_query_authz_grants.html",{"title":""},["/mainchain/software/und_cmd/und_query_authz_grants","/mainchain/software/und_cmd/und_query_authz_grants.md"]],
  ["v-5a9f6641","/mainchain/software/und_cmd/und_query_bank.html",{"title":""},["/mainchain/software/und_cmd/und_query_bank","/mainchain/software/und_cmd/und_query_bank.md"]],
  ["v-1132a88a","/mainchain/software/und_cmd/und_query_bank_balances.html",{"title":""},["/mainchain/software/und_cmd/und_query_bank_balances","/mainchain/software/und_cmd/und_query_bank_balances.md"]],
  ["v-b71bfb7e","/mainchain/software/und_cmd/und_query_bank_denom-metadata.html",{"title":""},["/mainchain/software/und_cmd/und_query_bank_denom-metadata","/mainchain/software/und_cmd/und_query_bank_denom-metadata.md"]],
  ["v-2b999d1c","/mainchain/software/und_cmd/und_query_bank_total.html",{"title":""},["/mainchain/software/und_cmd/und_query_bank_total","/mainchain/software/und_cmd/und_query_bank_total.md"]],
  ["v-a051a78e","/mainchain/software/und_cmd/und_query_beacon.html",{"title":""},["/mainchain/software/und_cmd/und_query_beacon","/mainchain/software/und_cmd/und_query_beacon.md"]],
  ["v-96c93414","/mainchain/software/und_cmd/und_query_beacon_beacon.html",{"title":""},["/mainchain/software/und_cmd/und_query_beacon_beacon","/mainchain/software/und_cmd/und_query_beacon_beacon.md"]],
  ["v-a1079c18","/mainchain/software/und_cmd/und_query_beacon_params.html",{"title":""},["/mainchain/software/und_cmd/und_query_beacon_params","/mainchain/software/und_cmd/und_query_beacon_params.md"]],
  ["v-28f50b12","/mainchain/software/und_cmd/und_query_beacon_search.html",{"title":""},["/mainchain/software/und_cmd/und_query_beacon_search","/mainchain/software/und_cmd/und_query_beacon_search.md"]],
  ["v-6112487d","/mainchain/software/und_cmd/und_query_beacon_storage.html",{"title":""},["/mainchain/software/und_cmd/und_query_beacon_storage","/mainchain/software/und_cmd/und_query_beacon_storage.md"]],
  ["v-e72011fc","/mainchain/software/und_cmd/und_query_beacon_timestamp.html",{"title":""},["/mainchain/software/und_cmd/und_query_beacon_timestamp","/mainchain/software/und_cmd/und_query_beacon_timestamp.md"]],
  ["v-7dce6ac8","/mainchain/software/und_cmd/und_query_block.html",{"title":""},["/mainchain/software/und_cmd/und_query_block","/mainchain/software/und_cmd/und_query_block.md"]],
  ["v-0da8a6f9","/mainchain/software/und_cmd/und_query_distribution.html",{"title":""},["/mainchain/software/und_cmd/und_query_distribution","/mainchain/software/und_cmd/und_query_distribution.md"]],
  ["v-78fa0b22","/mainchain/software/und_cmd/und_query_distribution_commission.html",{"title":""},["/mainchain/software/und_cmd/und_query_distribution_commission","/mainchain/software/und_cmd/und_query_distribution_commission.md"]],
  ["v-cc98ff0c","/mainchain/software/und_cmd/und_query_distribution_community-pool.html",{"title":""},["/mainchain/software/und_cmd/und_query_distribution_community-pool","/mainchain/software/und_cmd/und_query_distribution_community-pool.md"]],
  ["v-e661c198","/mainchain/software/und_cmd/und_query_distribution_params.html",{"title":""},["/mainchain/software/und_cmd/und_query_distribution_params","/mainchain/software/und_cmd/und_query_distribution_params.md"]],
  ["v-d42b9f98","/mainchain/software/und_cmd/und_query_distribution_rewards.html",{"title":""},["/mainchain/software/und_cmd/und_query_distribution_rewards","/mainchain/software/und_cmd/und_query_distribution_rewards.md"]],
  ["v-447748cd","/mainchain/software/und_cmd/und_query_distribution_slashes.html",{"title":""},["/mainchain/software/und_cmd/und_query_distribution_slashes","/mainchain/software/und_cmd/und_query_distribution_slashes.md"]],
  ["v-0b9be662","/mainchain/software/und_cmd/und_query_distribution_validator-outstanding-rewards.html",{"title":""},["/mainchain/software/und_cmd/und_query_distribution_validator-outstanding-rewards","/mainchain/software/und_cmd/und_query_distribution_validator-outstanding-rewards.md"]],
  ["v-48897d3c","/mainchain/software/und_cmd/und_query_enterprise.html",{"title":""},["/mainchain/software/und_cmd/und_query_enterprise","/mainchain/software/und_cmd/und_query_enterprise.md"]],
  ["v-d17ec3e4","/mainchain/software/und_cmd/und_query_enterprise_account.html",{"title":""},["/mainchain/software/und_cmd/und_query_enterprise_account","/mainchain/software/und_cmd/und_query_enterprise_account.md"]],
  ["v-3352f4e6","/mainchain/software/und_cmd/und_query_enterprise_ent-supply.html",{"title":""},["/mainchain/software/und_cmd/und_query_enterprise_ent-supply","/mainchain/software/und_cmd/und_query_enterprise_ent-supply.md"]],
  ["v-67d0608d","/mainchain/software/und_cmd/und_query_enterprise_locked.html",{"title":""},["/mainchain/software/und_cmd/und_query_enterprise_locked","/mainchain/software/und_cmd/und_query_enterprise_locked.md"]],
  ["v-7ff8960d","/mainchain/software/und_cmd/und_query_enterprise_order.html",{"title":""},["/mainchain/software/und_cmd/und_query_enterprise_order","/mainchain/software/und_cmd/und_query_enterprise_order.md"]],
  ["v-1cbc3cdc","/mainchain/software/und_cmd/und_query_enterprise_orders.html",{"title":""},["/mainchain/software/und_cmd/und_query_enterprise_orders","/mainchain/software/und_cmd/und_query_enterprise_orders.md"]],
  ["v-7d3f70de","/mainchain/software/und_cmd/und_query_enterprise_params.html",{"title":""},["/mainchain/software/und_cmd/und_query_enterprise_params","/mainchain/software/und_cmd/und_query_enterprise_params.md"]],
  ["v-6ff86fed","/mainchain/software/und_cmd/und_query_enterprise_spent.html",{"title":""},["/mainchain/software/und_cmd/und_query_enterprise_spent","/mainchain/software/und_cmd/und_query_enterprise_spent.md"]],
  ["v-c4ba9df8","/mainchain/software/und_cmd/und_query_enterprise_total-locked.html",{"title":""},["/mainchain/software/und_cmd/und_query_enterprise_total-locked","/mainchain/software/und_cmd/und_query_enterprise_total-locked.md"]],
  ["v-58eeb496","/mainchain/software/und_cmd/und_query_enterprise_total-spent.html",{"title":""},["/mainchain/software/und_cmd/und_query_enterprise_total-spent","/mainchain/software/und_cmd/und_query_enterprise_total-spent.md"]],
  ["v-293a4f8b","/mainchain/software/und_cmd/und_query_enterprise_total-unlocked.html",{"title":""},["/mainchain/software/und_cmd/und_query_enterprise_total-unlocked","/mainchain/software/und_cmd/und_query_enterprise_total-unlocked.md"]],
  ["v-60afdfb4","/mainchain/software/und_cmd/und_query_enterprise_whitelist.html",{"title":""},["/mainchain/software/und_cmd/und_query_enterprise_whitelist","/mainchain/software/und_cmd/und_query_enterprise_whitelist.md"]],
  ["v-46fd93b5","/mainchain/software/und_cmd/und_query_enterprise_whitelisted.html",{"title":""},["/mainchain/software/und_cmd/und_query_enterprise_whitelisted","/mainchain/software/und_cmd/und_query_enterprise_whitelisted.md"]],
  ["v-2083f506","/mainchain/software/und_cmd/und_query_evidence.html",{"title":""},["/mainchain/software/und_cmd/und_query_evidence","/mainchain/software/und_cmd/und_query_evidence.md"]],
  ["v-93e7bd32","/mainchain/software/und_cmd/und_query_feegrant.html",{"title":""},["/mainchain/software/und_cmd/und_query_feegrant","/mainchain/software/und_cmd/und_query_feegrant.md"]],
  ["v-aba2362c","/mainchain/software/und_cmd/und_query_feegrant_grant.html",{"title":""},["/mainchain/software/und_cmd/und_query_feegrant_grant","/mainchain/software/und_cmd/und_query_feegrant_grant.md"]],
  ["v-2a1e0a8a","/mainchain/software/und_cmd/und_query_feegrant_grants-by-grantee.html",{"title":""},["/mainchain/software/und_cmd/und_query_feegrant_grants-by-grantee","/mainchain/software/und_cmd/und_query_feegrant_grants-by-grantee.md"]],
  ["v-404d0a9d","/mainchain/software/und_cmd/und_query_feegrant_grants-by-granter.html",{"title":""},["/mainchain/software/und_cmd/und_query_feegrant_grants-by-granter","/mainchain/software/und_cmd/und_query_feegrant_grants-by-granter.md"]],
  ["v-5ff64332","/mainchain/software/und_cmd/und_query_gov.html",{"title":""},["/mainchain/software/und_cmd/und_query_gov","/mainchain/software/und_cmd/und_query_gov.md"]],
  ["v-19a13668","/mainchain/software/und_cmd/und_query_gov_deposit.html",{"title":""},["/mainchain/software/und_cmd/und_query_gov_deposit","/mainchain/software/und_cmd/und_query_gov_deposit.md"]],
  ["v-e5e566d2","/mainchain/software/und_cmd/und_query_gov_deposits.html",{"title":""},["/mainchain/software/und_cmd/und_query_gov_deposits","/mainchain/software/und_cmd/und_query_gov_deposits.md"]],
  ["v-4c408919","/mainchain/software/und_cmd/und_query_gov_param.html",{"title":""},["/mainchain/software/und_cmd/und_query_gov_param","/mainchain/software/und_cmd/und_query_gov_param.md"]],
  ["v-a34f5ff4","/mainchain/software/und_cmd/und_query_gov_params.html",{"title":""},["/mainchain/software/und_cmd/und_query_gov_params","/mainchain/software/und_cmd/und_query_gov_params.md"]],
  ["v-434d715a","/mainchain/software/und_cmd/und_query_gov_proposal.html",{"title":""},["/mainchain/software/und_cmd/und_query_gov_proposal","/mainchain/software/und_cmd/und_query_gov_proposal.md"]],
  ["v-ce2f2036","/mainchain/software/und_cmd/und_query_gov_proposals.html",{"title":""},["/mainchain/software/und_cmd/und_query_gov_proposals","/mainchain/software/und_cmd/und_query_gov_proposals.md"]],
  ["v-21237218","/mainchain/software/und_cmd/und_query_gov_proposer.html",{"title":""},["/mainchain/software/und_cmd/und_query_gov_proposer","/mainchain/software/und_cmd/und_query_gov_proposer.md"]],
  ["v-087df39a","/mainchain/software/und_cmd/und_query_gov_tally.html",{"title":""},["/mainchain/software/und_cmd/und_query_gov_tally","/mainchain/software/und_cmd/und_query_gov_tally.md"]],
  ["v-5592d5e2","/mainchain/software/und_cmd/und_query_gov_vote.html",{"title":""},["/mainchain/software/und_cmd/und_query_gov_vote","/mainchain/software/und_cmd/und_query_gov_vote.md"]],
  ["v-6160c746","/mainchain/software/und_cmd/und_query_gov_votes.html",{"title":""},["/mainchain/software/und_cmd/und_query_gov_votes","/mainchain/software/und_cmd/und_query_gov_votes.md"]],
  ["v-3d0e8bcf","/mainchain/software/und_cmd/und_query_ibc-transfer.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc-transfer","/mainchain/software/und_cmd/und_query_ibc-transfer.md"]],
  ["v-50be38f4","/mainchain/software/und_cmd/und_query_ibc-transfer_denom-hash.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc-transfer_denom-hash","/mainchain/software/und_cmd/und_query_ibc-transfer_denom-hash.md"]],
  ["v-17551f6b","/mainchain/software/und_cmd/und_query_ibc-transfer_denom-trace.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc-transfer_denom-trace","/mainchain/software/und_cmd/und_query_ibc-transfer_denom-trace.md"]],
  ["v-45d683f4","/mainchain/software/und_cmd/und_query_ibc-transfer_denom-traces.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc-transfer_denom-traces","/mainchain/software/und_cmd/und_query_ibc-transfer_denom-traces.md"]],
  ["v-171af178","/mainchain/software/und_cmd/und_query_ibc-transfer_escrow-address.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc-transfer_escrow-address","/mainchain/software/und_cmd/und_query_ibc-transfer_escrow-address.md"]],
  ["v-d80784c4","/mainchain/software/und_cmd/und_query_ibc-transfer_params.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc-transfer_params","/mainchain/software/und_cmd/und_query_ibc-transfer_params.md"]],
  ["v-60abbbea","/mainchain/software/und_cmd/und_query_ibc.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc","/mainchain/software/und_cmd/und_query_ibc.md"]],
  ["v-72ef66c7","/mainchain/software/und_cmd/und_query_ibc_channel.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_channel","/mainchain/software/und_cmd/und_query_ibc_channel.md"]],
  ["v-7fdb76dc","/mainchain/software/und_cmd/und_query_ibc_channel_channels.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_channel_channels","/mainchain/software/und_cmd/und_query_ibc_channel_channels.md"]],
  ["v-7b72c07d","/mainchain/software/und_cmd/und_query_ibc_channel_client-state.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_channel_client-state","/mainchain/software/und_cmd/und_query_ibc_channel_client-state.md"]],
  ["v-5ae7f81e","/mainchain/software/und_cmd/und_query_ibc_channel_connections.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_channel_connections","/mainchain/software/und_cmd/und_query_ibc_channel_connections.md"]],
  ["v-35868daa","/mainchain/software/und_cmd/und_query_ibc_channel_end.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_channel_end","/mainchain/software/und_cmd/und_query_ibc_channel_end.md"]],
  ["v-eff6cbd6","/mainchain/software/und_cmd/und_query_ibc_channel_next-sequence-receive.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_channel_next-sequence-receive","/mainchain/software/und_cmd/und_query_ibc_channel_next-sequence-receive.md"]],
  ["v-5e6154a8","/mainchain/software/und_cmd/und_query_ibc_channel_packet-ack.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_channel_packet-ack","/mainchain/software/und_cmd/und_query_ibc_channel_packet-ack.md"]],
  ["v-3e2cfd2c","/mainchain/software/und_cmd/und_query_ibc_channel_packet-commitment.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_channel_packet-commitment","/mainchain/software/und_cmd/und_query_ibc_channel_packet-commitment.md"]],
  ["v-0c0b435a","/mainchain/software/und_cmd/und_query_ibc_channel_packet-commitments.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_channel_packet-commitments","/mainchain/software/und_cmd/und_query_ibc_channel_packet-commitments.md"]],
  ["v-70d5f459","/mainchain/software/und_cmd/und_query_ibc_channel_packet-receipt.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_channel_packet-receipt","/mainchain/software/und_cmd/und_query_ibc_channel_packet-receipt.md"]],
  ["v-8ff9f76e","/mainchain/software/und_cmd/und_query_ibc_channel_unreceived-acks.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_channel_unreceived-acks","/mainchain/software/und_cmd/und_query_ibc_channel_unreceived-acks.md"]],
  ["v-733eae54","/mainchain/software/und_cmd/und_query_ibc_channel_unreceived-packets.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_channel_unreceived-packets","/mainchain/software/und_cmd/und_query_ibc_channel_unreceived-packets.md"]],
  ["v-7555d686","/mainchain/software/und_cmd/und_query_ibc_client.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_client","/mainchain/software/und_cmd/und_query_ibc_client.md"]],
  ["v-4c2e4e7c","/mainchain/software/und_cmd/und_query_ibc_client_consensus-state-heights.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_client_consensus-state-heights","/mainchain/software/und_cmd/und_query_ibc_client_consensus-state-heights.md"]],
  ["v-6bb2167e","/mainchain/software/und_cmd/und_query_ibc_client_consensus-state.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_client_consensus-state","/mainchain/software/und_cmd/und_query_ibc_client_consensus-state.md"]],
  ["v-25814d44","/mainchain/software/und_cmd/und_query_ibc_client_consensus-states.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_client_consensus-states","/mainchain/software/und_cmd/und_query_ibc_client_consensus-states.md"]],
  ["v-64561049","/mainchain/software/und_cmd/und_query_ibc_client_header.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_client_header","/mainchain/software/und_cmd/und_query_ibc_client_header.md"]],
  ["v-f7b72620","/mainchain/software/und_cmd/und_query_ibc_client_params.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_client_params","/mainchain/software/und_cmd/und_query_ibc_client_params.md"]],
  ["v-36c288fc","/mainchain/software/und_cmd/und_query_ibc_client_self-consensus-state.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_client_self-consensus-state","/mainchain/software/und_cmd/und_query_ibc_client_self-consensus-state.md"]],
  ["v-32d45d6b","/mainchain/software/und_cmd/und_query_ibc_client_state.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_client_state","/mainchain/software/und_cmd/und_query_ibc_client_state.md"]],
  ["v-cb81f418","/mainchain/software/und_cmd/und_query_ibc_client_states.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_client_states","/mainchain/software/und_cmd/und_query_ibc_client_states.md"]],
  ["v-2eba8bf8","/mainchain/software/und_cmd/und_query_ibc_client_status.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_client_status","/mainchain/software/und_cmd/und_query_ibc_client_status.md"]],
  ["v-3e237e0a","/mainchain/software/und_cmd/und_query_ibc_connection.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_connection","/mainchain/software/und_cmd/und_query_ibc_connection.md"]],
  ["v-bcbf6298","/mainchain/software/und_cmd/und_query_ibc_connection_connections.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_connection_connections","/mainchain/software/und_cmd/und_query_ibc_connection_connections.md"]],
  ["v-3e3d76ee","/mainchain/software/und_cmd/und_query_ibc_connection_end.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_connection_end","/mainchain/software/und_cmd/und_query_ibc_connection_end.md"]],
  ["v-5018ffc4","/mainchain/software/und_cmd/und_query_ibc_connection_path.html",{"title":""},["/mainchain/software/und_cmd/und_query_ibc_connection_path","/mainchain/software/und_cmd/und_query_ibc_connection_path.md"]],
  ["v-aa900f92","/mainchain/software/und_cmd/und_query_params.html",{"title":""},["/mainchain/software/und_cmd/und_query_params","/mainchain/software/und_cmd/und_query_params.md"]],
  ["v-3dd97636","/mainchain/software/und_cmd/und_query_params_subspace.html",{"title":""},["/mainchain/software/und_cmd/und_query_params_subspace","/mainchain/software/und_cmd/und_query_params_subspace.md"]],
  ["v-f2c8e250","/mainchain/software/und_cmd/und_query_slashing.html",{"title":""},["/mainchain/software/und_cmd/und_query_slashing","/mainchain/software/und_cmd/und_query_slashing.md"]],
  ["v-2c406e75","/mainchain/software/und_cmd/und_query_slashing_params.html",{"title":""},["/mainchain/software/und_cmd/und_query_slashing_params","/mainchain/software/und_cmd/und_query_slashing_params.md"]],
  ["v-3679d005","/mainchain/software/und_cmd/und_query_slashing_signing-info.html",{"title":""},["/mainchain/software/und_cmd/und_query_slashing_signing-info","/mainchain/software/und_cmd/und_query_slashing_signing-info.md"]],
  ["v-0b47e69a","/mainchain/software/und_cmd/und_query_slashing_signing-infos.html",{"title":""},["/mainchain/software/und_cmd/und_query_slashing_signing-infos","/mainchain/software/und_cmd/und_query_slashing_signing-infos.md"]],
  ["v-182ac8de","/mainchain/software/und_cmd/und_query_staking.html",{"title":""},["/mainchain/software/und_cmd/und_query_staking","/mainchain/software/und_cmd/und_query_staking.md"]],
  ["v-5724d566","/mainchain/software/und_cmd/und_query_staking_delegation.html",{"title":""},["/mainchain/software/und_cmd/und_query_staking_delegation","/mainchain/software/und_cmd/und_query_staking_delegation.md"]],
  ["v-1395c258","/mainchain/software/und_cmd/und_query_staking_delegations-to.html",{"title":""},["/mainchain/software/und_cmd/und_query_staking_delegations-to","/mainchain/software/und_cmd/und_query_staking_delegations-to.md"]],
  ["v-2bccca52","/mainchain/software/und_cmd/und_query_staking_delegations.html",{"title":""},["/mainchain/software/und_cmd/und_query_staking_delegations","/mainchain/software/und_cmd/und_query_staking_delegations.md"]],
  ["v-f4d4c6e8","/mainchain/software/und_cmd/und_query_staking_historical-info.html",{"title":""},["/mainchain/software/und_cmd/und_query_staking_historical-info","/mainchain/software/und_cmd/und_query_staking_historical-info.md"]],
  ["v-0179fca2","/mainchain/software/und_cmd/und_query_staking_params.html",{"title":""},["/mainchain/software/und_cmd/und_query_staking_params","/mainchain/software/und_cmd/und_query_staking_params.md"]],
  ["v-010ff04e","/mainchain/software/und_cmd/und_query_staking_pool.html",{"title":""},["/mainchain/software/und_cmd/und_query_staking_pool","/mainchain/software/und_cmd/und_query_staking_pool.md"]],
  ["v-1c01788c","/mainchain/software/und_cmd/und_query_staking_redelegation.html",{"title":""},["/mainchain/software/und_cmd/und_query_staking_redelegation","/mainchain/software/und_cmd/und_query_staking_redelegation.md"]],
  ["v-035328b6","/mainchain/software/und_cmd/und_query_staking_redelegations-from.html",{"title":""},["/mainchain/software/und_cmd/und_query_staking_redelegations-from","/mainchain/software/und_cmd/und_query_staking_redelegations-from.md"]],
  ["v-7f1e2cf6","/mainchain/software/und_cmd/und_query_staking_redelegations.html",{"title":""},["/mainchain/software/und_cmd/und_query_staking_redelegations","/mainchain/software/und_cmd/und_query_staking_redelegations.md"]],
  ["v-565307f4","/mainchain/software/und_cmd/und_query_staking_unbonding-delegation.html",{"title":""},["/mainchain/software/und_cmd/und_query_staking_unbonding-delegation","/mainchain/software/und_cmd/und_query_staking_unbonding-delegation.md"]],
  ["v-3a39f802","/mainchain/software/und_cmd/und_query_staking_unbonding-delegations-from.html",{"title":""},["/mainchain/software/und_cmd/und_query_staking_unbonding-delegations-from","/mainchain/software/und_cmd/und_query_staking_unbonding-delegations-from.md"]],
  ["v-3880bab9","/mainchain/software/und_cmd/und_query_staking_unbonding-delegations.html",{"title":""},["/mainchain/software/und_cmd/und_query_staking_unbonding-delegations","/mainchain/software/und_cmd/und_query_staking_unbonding-delegations.md"]],
  ["v-ab3226aa","/mainchain/software/und_cmd/und_query_staking_validator.html",{"title":""},["/mainchain/software/und_cmd/und_query_staking_validator","/mainchain/software/und_cmd/und_query_staking_validator.md"]],
  ["v-14fe5eb4","/mainchain/software/und_cmd/und_query_staking_validators.html",{"title":""},["/mainchain/software/und_cmd/und_query_staking_validators","/mainchain/software/und_cmd/und_query_staking_validators.md"]],
  ["v-4222826e","/mainchain/software/und_cmd/und_query_supply.html",{"title":""},["/mainchain/software/und_cmd/und_query_supply","/mainchain/software/und_cmd/und_query_supply.md"]],
  ["v-2ab02826","/mainchain/software/und_cmd/und_query_tendermint-validator-set.html",{"title":""},["/mainchain/software/und_cmd/und_query_tendermint-validator-set","/mainchain/software/und_cmd/und_query_tendermint-validator-set.md"]],
  ["v-5b2af80e","/mainchain/software/und_cmd/und_query_tx.html",{"title":""},["/mainchain/software/und_cmd/und_query_tx","/mainchain/software/und_cmd/und_query_tx.md"]],
  ["v-25249db4","/mainchain/software/und_cmd/und_query_txs.html",{"title":""},["/mainchain/software/und_cmd/und_query_txs","/mainchain/software/und_cmd/und_query_txs.md"]],
  ["v-48218f99","/mainchain/software/und_cmd/und_query_upgrade.html",{"title":""},["/mainchain/software/und_cmd/und_query_upgrade","/mainchain/software/und_cmd/und_query_upgrade.md"]],
  ["v-dfcc61ca","/mainchain/software/und_cmd/und_query_upgrade_applied.html",{"title":""},["/mainchain/software/und_cmd/und_query_upgrade_applied","/mainchain/software/und_cmd/und_query_upgrade_applied.md"]],
  ["v-b4233fac","/mainchain/software/und_cmd/und_query_upgrade_module_versions.html",{"title":""},["/mainchain/software/und_cmd/und_query_upgrade_module_versions","/mainchain/software/und_cmd/und_query_upgrade_module_versions.md"]],
  ["v-5f162b11","/mainchain/software/und_cmd/und_query_upgrade_plan.html",{"title":""},["/mainchain/software/und_cmd/und_query_upgrade_plan","/mainchain/software/und_cmd/und_query_upgrade_plan.md"]],
  ["v-80da6068","/mainchain/software/und_cmd/und_query_wrkchain.html",{"title":""},["/mainchain/software/und_cmd/und_query_wrkchain","/mainchain/software/und_cmd/und_query_wrkchain.md"]],
  ["v-6c56eebe","/mainchain/software/und_cmd/und_query_wrkchain_block.html",{"title":""},["/mainchain/software/und_cmd/und_query_wrkchain_block","/mainchain/software/und_cmd/und_query_wrkchain_block.md"]],
  ["v-e58019fe","/mainchain/software/und_cmd/und_query_wrkchain_params.html",{"title":""},["/mainchain/software/und_cmd/und_query_wrkchain_params","/mainchain/software/und_cmd/und_query_wrkchain_params.md"]],
  ["v-06b8cc1f","/mainchain/software/und_cmd/und_query_wrkchain_search.html",{"title":""},["/mainchain/software/und_cmd/und_query_wrkchain_search","/mainchain/software/und_cmd/und_query_wrkchain_search.md"]],
  ["v-3bc6a910","/mainchain/software/und_cmd/und_query_wrkchain_storage.html",{"title":""},["/mainchain/software/und_cmd/und_query_wrkchain_storage","/mainchain/software/und_cmd/und_query_wrkchain_storage.md"]],
  ["v-20074016","/mainchain/software/und_cmd/und_query_wrkchain_wrkchain.html",{"title":""},["/mainchain/software/und_cmd/und_query_wrkchain_wrkchain","/mainchain/software/und_cmd/und_query_wrkchain_wrkchain.md"]],
  ["v-61214fe0","/mainchain/software/und_cmd/und_rollback.html",{"title":""},["/mainchain/software/und_cmd/und_rollback","/mainchain/software/und_cmd/und_rollback.md"]],
  ["v-28ce0228","/mainchain/software/und_cmd/und_rosetta.html",{"title":""},["/mainchain/software/und_cmd/und_rosetta","/mainchain/software/und_cmd/und_rosetta.md"]],
  ["v-4917c008","/mainchain/software/und_cmd/und_start.html",{"title":""},["/mainchain/software/und_cmd/und_start","/mainchain/software/und_cmd/und_start.md"]],
  ["v-0a402a82","/mainchain/software/und_cmd/und_status.html",{"title":""},["/mainchain/software/und_cmd/und_status","/mainchain/software/und_cmd/und_status.md"]],
  ["v-6e24723e","/mainchain/software/und_cmd/und_tendermint.html",{"title":""},["/mainchain/software/und_cmd/und_tendermint","/mainchain/software/und_cmd/und_tendermint.md"]],
  ["v-61b0eb2c","/mainchain/software/und_cmd/und_tendermint_reset-state.html",{"title":""},["/mainchain/software/und_cmd/und_tendermint_reset-state","/mainchain/software/und_cmd/und_tendermint_reset-state.md"]],
  ["v-0a8dae71","/mainchain/software/und_cmd/und_tendermint_show-address.html",{"title":""},["/mainchain/software/und_cmd/und_tendermint_show-address","/mainchain/software/und_cmd/und_tendermint_show-address.md"]],
  ["v-69144cdf","/mainchain/software/und_cmd/und_tendermint_show-node-id.html",{"title":""},["/mainchain/software/und_cmd/und_tendermint_show-node-id","/mainchain/software/und_cmd/und_tendermint_show-node-id.md"]],
  ["v-450fd25a","/mainchain/software/und_cmd/und_tendermint_show-validator.html",{"title":""},["/mainchain/software/und_cmd/und_tendermint_show-validator","/mainchain/software/und_cmd/und_tendermint_show-validator.md"]],
  ["v-0282e84e","/mainchain/software/und_cmd/und_tendermint_unsafe-reset-all.html",{"title":""},["/mainchain/software/und_cmd/und_tendermint_unsafe-reset-all","/mainchain/software/und_cmd/und_tendermint_unsafe-reset-all.md"]],
  ["v-3b145d76","/mainchain/software/und_cmd/und_tendermint_version.html",{"title":""},["/mainchain/software/und_cmd/und_tendermint_version","/mainchain/software/und_cmd/und_tendermint_version.md"]],
  ["v-4aad9cb0","/mainchain/software/und_cmd/und_tx.html",{"title":""},["/mainchain/software/und_cmd/und_tx","/mainchain/software/und_cmd/und_tx.md"]],
  ["v-885c9f06","/mainchain/software/und_cmd/und_tx_authz.html",{"title":""},["/mainchain/software/und_cmd/und_tx_authz","/mainchain/software/und_cmd/und_tx_authz.md"]],
  ["v-19fbec45","/mainchain/software/und_cmd/und_tx_authz_exec.html",{"title":""},["/mainchain/software/und_cmd/und_tx_authz_exec","/mainchain/software/und_cmd/und_tx_authz_exec.md"]],
  ["v-a1d36900","/mainchain/software/und_cmd/und_tx_authz_grant.html",{"title":""},["/mainchain/software/und_cmd/und_tx_authz_grant","/mainchain/software/und_cmd/und_tx_authz_grant.md"]],
  ["v-41d62430","/mainchain/software/und_cmd/und_tx_authz_revoke.html",{"title":""},["/mainchain/software/und_cmd/und_tx_authz_revoke","/mainchain/software/und_cmd/und_tx_authz_revoke.md"]],
  ["v-fb1da5b2","/mainchain/software/und_cmd/und_tx_bank.html",{"title":""},["/mainchain/software/und_cmd/und_tx_bank","/mainchain/software/und_cmd/und_tx_bank.md"]],
  ["v-c4d31578","/mainchain/software/und_cmd/und_tx_bank_send.html",{"title":""},["/mainchain/software/und_cmd/und_tx_bank_send","/mainchain/software/und_cmd/und_tx_bank_send.md"]],
  ["v-2a52d19f","/mainchain/software/und_cmd/und_tx_beacon.html",{"title":""},["/mainchain/software/und_cmd/und_tx_beacon","/mainchain/software/und_cmd/und_tx_beacon.md"]],
  ["v-481836b7","/mainchain/software/und_cmd/und_tx_beacon_purchase_storage.html",{"title":""},["/mainchain/software/und_cmd/und_tx_beacon_purchase_storage","/mainchain/software/und_cmd/und_tx_beacon_purchase_storage.md"]],
  ["v-1b2f3c3a","/mainchain/software/und_cmd/und_tx_beacon_record.html",{"title":""},["/mainchain/software/und_cmd/und_tx_beacon_record","/mainchain/software/und_cmd/und_tx_beacon_record.md"]],
  ["v-10b38011","/mainchain/software/und_cmd/und_tx_beacon_register.html",{"title":""},["/mainchain/software/und_cmd/und_tx_beacon_register","/mainchain/software/und_cmd/und_tx_beacon_register.md"]],
  ["v-9f065c24","/mainchain/software/und_cmd/und_tx_broadcast.html",{"title":""},["/mainchain/software/und_cmd/und_tx_broadcast","/mainchain/software/und_cmd/und_tx_broadcast.md"]],
  ["v-124b6080","/mainchain/software/und_cmd/und_tx_crisis.html",{"title":""},["/mainchain/software/und_cmd/und_tx_crisis","/mainchain/software/und_cmd/und_tx_crisis.md"]],
  ["v-b87d885e","/mainchain/software/und_cmd/und_tx_crisis_invariant-broken.html",{"title":""},["/mainchain/software/und_cmd/und_tx_crisis_invariant-broken","/mainchain/software/und_cmd/und_tx_crisis_invariant-broken.md"]],
  ["v-05f30635","/mainchain/software/und_cmd/und_tx_decode.html",{"title":""},["/mainchain/software/und_cmd/und_tx_decode","/mainchain/software/und_cmd/und_tx_decode.md"]],
  ["v-105fb042","/mainchain/software/und_cmd/und_tx_distribution.html",{"title":""},["/mainchain/software/und_cmd/und_tx_distribution","/mainchain/software/und_cmd/und_tx_distribution.md"]],
  ["v-29e3d5b6","/mainchain/software/und_cmd/und_tx_distribution_fund-community-pool.html",{"title":""},["/mainchain/software/und_cmd/und_tx_distribution_fund-community-pool","/mainchain/software/und_cmd/und_tx_distribution_fund-community-pool.md"]],
  ["v-d1961f16","/mainchain/software/und_cmd/und_tx_distribution_set-withdraw-addr.html",{"title":""},["/mainchain/software/und_cmd/und_tx_distribution_set-withdraw-addr","/mainchain/software/und_cmd/und_tx_distribution_set-withdraw-addr.md"]],
  ["v-ec690b02","/mainchain/software/und_cmd/und_tx_distribution_withdraw-all-rewards.html",{"title":""},["/mainchain/software/und_cmd/und_tx_distribution_withdraw-all-rewards","/mainchain/software/und_cmd/und_tx_distribution_withdraw-all-rewards.md"]],
  ["v-984c3e5a","/mainchain/software/und_cmd/und_tx_distribution_withdraw-rewards.html",{"title":""},["/mainchain/software/und_cmd/und_tx_distribution_withdraw-rewards","/mainchain/software/und_cmd/und_tx_distribution_withdraw-rewards.md"]],
  ["v-316cb30d","/mainchain/software/und_cmd/und_tx_encode.html",{"title":""},["/mainchain/software/und_cmd/und_tx_encode","/mainchain/software/und_cmd/und_tx_encode.md"]],
  ["v-2847ffa2","/mainchain/software/und_cmd/und_tx_enterprise.html",{"title":""},["/mainchain/software/und_cmd/und_tx_enterprise","/mainchain/software/und_cmd/und_tx_enterprise.md"]],
  ["v-3b37c11c","/mainchain/software/und_cmd/und_tx_enterprise_process.html",{"title":""},["/mainchain/software/und_cmd/und_tx_enterprise_process","/mainchain/software/und_cmd/und_tx_enterprise_process.md"]],
  ["v-097ed9d0","/mainchain/software/und_cmd/und_tx_enterprise_purchase.html",{"title":""},["/mainchain/software/und_cmd/und_tx_enterprise_purchase","/mainchain/software/und_cmd/und_tx_enterprise_purchase.md"]],
  ["v-be59cacc","/mainchain/software/und_cmd/und_tx_enterprise_whitelist.html",{"title":""},["/mainchain/software/und_cmd/und_tx_enterprise_whitelist","/mainchain/software/und_cmd/und_tx_enterprise_whitelist.md"]],
  ["v-2aa84e28","/mainchain/software/und_cmd/und_tx_evidence.html",{"title":""},["/mainchain/software/und_cmd/und_tx_evidence","/mainchain/software/und_cmd/und_tx_evidence.md"]],
  ["v-ff97f566","/mainchain/software/und_cmd/und_tx_feegrant.html",{"title":""},["/mainchain/software/und_cmd/und_tx_feegrant","/mainchain/software/und_cmd/und_tx_feegrant.md"]],
  ["v-af0c7760","/mainchain/software/und_cmd/und_tx_feegrant_grant.html",{"title":""},["/mainchain/software/und_cmd/und_tx_feegrant_grant","/mainchain/software/und_cmd/und_tx_feegrant_grant.md"]],
  ["v-74e1c560","/mainchain/software/und_cmd/und_tx_feegrant_revoke.html",{"title":""},["/mainchain/software/und_cmd/und_tx_feegrant_revoke","/mainchain/software/und_cmd/und_tx_feegrant_revoke.md"]],
  ["v-6de8ba7e","/mainchain/software/und_cmd/und_tx_gov.html",{"title":""},["/mainchain/software/und_cmd/und_tx_gov","/mainchain/software/und_cmd/und_tx_gov.md"]],
  ["v-31b300c2","/mainchain/software/und_cmd/und_tx_gov_deposit.html",{"title":""},["/mainchain/software/und_cmd/und_tx_gov_deposit","/mainchain/software/und_cmd/und_tx_gov_deposit.md"]],
  ["v-ea259e0e","/mainchain/software/und_cmd/und_tx_gov_submit-proposal.html",{"title":""},["/mainchain/software/und_cmd/und_tx_gov_submit-proposal","/mainchain/software/und_cmd/und_tx_gov_submit-proposal.md"]],
  ["v-1ca538e2","/mainchain/software/und_cmd/und_tx_gov_submit-proposal_cancel-software-upgrade.html",{"title":""},["/mainchain/software/und_cmd/und_tx_gov_submit-proposal_cancel-software-upgrade","/mainchain/software/und_cmd/und_tx_gov_submit-proposal_cancel-software-upgrade.md"]],
  ["v-57f3cf09","/mainchain/software/und_cmd/und_tx_gov_submit-proposal_community-pool-spend.html",{"title":""},["/mainchain/software/und_cmd/und_tx_gov_submit-proposal_community-pool-spend","/mainchain/software/und_cmd/und_tx_gov_submit-proposal_community-pool-spend.md"]],
  ["v-476e853f","/mainchain/software/und_cmd/und_tx_gov_submit-proposal_ibc-upgrade.html",{"title":""},["/mainchain/software/und_cmd/und_tx_gov_submit-proposal_ibc-upgrade","/mainchain/software/und_cmd/und_tx_gov_submit-proposal_ibc-upgrade.md"]],
  ["v-c8dc316c","/mainchain/software/und_cmd/und_tx_gov_submit-proposal_param-change.html",{"title":""},["/mainchain/software/und_cmd/und_tx_gov_submit-proposal_param-change","/mainchain/software/und_cmd/und_tx_gov_submit-proposal_param-change.md"]],
  ["v-d80fd0f8","/mainchain/software/und_cmd/und_tx_gov_submit-proposal_software-upgrade.html",{"title":""},["/mainchain/software/und_cmd/und_tx_gov_submit-proposal_software-upgrade","/mainchain/software/und_cmd/und_tx_gov_submit-proposal_software-upgrade.md"]],
  ["v-04a850ae","/mainchain/software/und_cmd/und_tx_gov_submit-proposal_update-client.html",{"title":""},["/mainchain/software/und_cmd/und_tx_gov_submit-proposal_update-client","/mainchain/software/und_cmd/und_tx_gov_submit-proposal_update-client.md"]],
  ["v-1fbab9c8","/mainchain/software/und_cmd/und_tx_gov_vote.html",{"title":""},["/mainchain/software/und_cmd/und_tx_gov_vote","/mainchain/software/und_cmd/und_tx_gov_vote.md"]],
  ["v-1478a580","/mainchain/software/und_cmd/und_tx_gov_weighted-vote.html",{"title":""},["/mainchain/software/und_cmd/und_tx_gov_weighted-vote","/mainchain/software/und_cmd/und_tx_gov_weighted-vote.md"]],
  ["v-27360cb5","/mainchain/software/und_cmd/und_tx_ibc-transfer.html",{"title":""},["/mainchain/software/und_cmd/und_tx_ibc-transfer","/mainchain/software/und_cmd/und_tx_ibc-transfer.md"]],
  ["v-ad3f3d1a","/mainchain/software/und_cmd/und_tx_ibc-transfer_transfer.html",{"title":""},["/mainchain/software/und_cmd/und_tx_ibc-transfer_transfer","/mainchain/software/und_cmd/und_tx_ibc-transfer_transfer.md"]],
  ["v-6e9e3336","/mainchain/software/und_cmd/und_tx_ibc.html",{"title":""},["/mainchain/software/und_cmd/und_tx_ibc","/mainchain/software/und_cmd/und_tx_ibc.md"]],
  ["v-e9fd9dbe","/mainchain/software/und_cmd/und_tx_ibc_channel.html",{"title":""},["/mainchain/software/und_cmd/und_tx_ibc_channel","/mainchain/software/und_cmd/und_tx_ibc_channel.md"]],
  ["v-b5d8d1ba","/mainchain/software/und_cmd/und_tx_ibc_client.html",{"title":""},["/mainchain/software/und_cmd/und_tx_ibc_client","/mainchain/software/und_cmd/und_tx_ibc_client.md"]],
  ["v-4b591e14","/mainchain/software/und_cmd/und_tx_ibc_client_create.html",{"title":""},["/mainchain/software/und_cmd/und_tx_ibc_client_create","/mainchain/software/und_cmd/und_tx_ibc_client_create.md"]],
  ["v-09e5186c","/mainchain/software/und_cmd/und_tx_ibc_client_misbehaviour.html",{"title":""},["/mainchain/software/und_cmd/und_tx_ibc_client_misbehaviour","/mainchain/software/und_cmd/und_tx_ibc_client_misbehaviour.md"]],
  ["v-46965e67","/mainchain/software/und_cmd/und_tx_ibc_client_update.html",{"title":""},["/mainchain/software/und_cmd/und_tx_ibc_client_update","/mainchain/software/und_cmd/und_tx_ibc_client_update.md"]],
  ["v-9cb72334","/mainchain/software/und_cmd/und_tx_ibc_client_upgrade.html",{"title":""},["/mainchain/software/und_cmd/und_tx_ibc_client_upgrade","/mainchain/software/und_cmd/und_tx_ibc_client_upgrade.md"]],
  ["v-a8ff8368","/mainchain/software/und_cmd/und_tx_multisign-batch.html",{"title":""},["/mainchain/software/und_cmd/und_tx_multisign-batch","/mainchain/software/und_cmd/und_tx_multisign-batch.md"]],
  ["v-2bacd54e","/mainchain/software/und_cmd/und_tx_multisign.html",{"title":""},["/mainchain/software/und_cmd/und_tx_multisign","/mainchain/software/und_cmd/und_tx_multisign.md"]],
  ["v-ae833d0e","/mainchain/software/und_cmd/und_tx_sign-batch.html",{"title":""},["/mainchain/software/und_cmd/und_tx_sign-batch","/mainchain/software/und_cmd/und_tx_sign-batch.md"]],
  ["v-2cd8de46","/mainchain/software/und_cmd/und_tx_sign.html",{"title":""},["/mainchain/software/und_cmd/und_tx_sign","/mainchain/software/und_cmd/und_tx_sign.md"]],
  ["v-50c372be","/mainchain/software/und_cmd/und_tx_slashing.html",{"title":""},["/mainchain/software/und_cmd/und_tx_slashing","/mainchain/software/und_cmd/und_tx_slashing.md"]],
  ["v-7455327c","/mainchain/software/und_cmd/und_tx_slashing_unjail.html",{"title":""},["/mainchain/software/und_cmd/und_tx_slashing_unjail","/mainchain/software/und_cmd/und_tx_slashing_unjail.md"]],
  ["v-25b85f90","/mainchain/software/und_cmd/und_tx_staking.html",{"title":""},["/mainchain/software/und_cmd/und_tx_staking","/mainchain/software/und_cmd/und_tx_staking.md"]],
  ["v-7c12693a","/mainchain/software/und_cmd/und_tx_staking_create-validator.html",{"title":""},["/mainchain/software/und_cmd/und_tx_staking_create-validator","/mainchain/software/und_cmd/und_tx_staking_create-validator.md"]],
  ["v-86e1a814","/mainchain/software/und_cmd/und_tx_staking_delegate.html",{"title":""},["/mainchain/software/und_cmd/und_tx_staking_delegate","/mainchain/software/und_cmd/und_tx_staking_delegate.md"]],
  ["v-0c5c16ec","/mainchain/software/und_cmd/und_tx_staking_edit-validator.html",{"title":""},["/mainchain/software/und_cmd/und_tx_staking_edit-validator","/mainchain/software/und_cmd/und_tx_staking_edit-validator.md"]],
  ["v-4bf3b023","/mainchain/software/und_cmd/und_tx_staking_redelegate.html",{"title":""},["/mainchain/software/und_cmd/und_tx_staking_redelegate","/mainchain/software/und_cmd/und_tx_staking_redelegate.md"]],
  ["v-59d1a902","/mainchain/software/und_cmd/und_tx_staking_unbond.html",{"title":""},["/mainchain/software/und_cmd/und_tx_staking_unbond","/mainchain/software/und_cmd/und_tx_staking_unbond.md"]],
  ["v-0aa6ec06","/mainchain/software/und_cmd/und_tx_validate-signatures.html",{"title":""},["/mainchain/software/und_cmd/und_tx_validate-signatures","/mainchain/software/und_cmd/und_tx_validate-signatures.md"]],
  ["v-a337bb86","/mainchain/software/und_cmd/und_tx_vesting.html",{"title":""},["/mainchain/software/und_cmd/und_tx_vesting","/mainchain/software/und_cmd/und_tx_vesting.md"]],
  ["v-7ac34ab5","/mainchain/software/und_cmd/und_tx_vesting_create-vesting-account.html",{"title":""},["/mainchain/software/und_cmd/und_tx_vesting_create-vesting-account","/mainchain/software/und_cmd/und_tx_vesting_create-vesting-account.md"]],
  ["v-ec8a989c","/mainchain/software/und_cmd/und_tx_wrkchain.html",{"title":""},["/mainchain/software/und_cmd/und_tx_wrkchain","/mainchain/software/und_cmd/und_tx_wrkchain.md"]],
  ["v-24045d04","/mainchain/software/und_cmd/und_tx_wrkchain_purchase_storage.html",{"title":""},["/mainchain/software/und_cmd/und_tx_wrkchain_purchase_storage","/mainchain/software/und_cmd/und_tx_wrkchain_purchase_storage.md"]],
  ["v-40749470","/mainchain/software/und_cmd/und_tx_wrkchain_record.html",{"title":""},["/mainchain/software/und_cmd/und_tx_wrkchain_record","/mainchain/software/und_cmd/und_tx_wrkchain_record.md"]],
  ["v-0c7d435e","/mainchain/software/und_cmd/und_tx_wrkchain_register.html",{"title":""},["/mainchain/software/und_cmd/und_tx_wrkchain_register","/mainchain/software/und_cmd/und_tx_wrkchain_register.md"]],
  ["v-c67dcfba","/mainchain/software/und_cmd/und_validate-genesis.html",{"title":""},["/mainchain/software/und_cmd/und_validate-genesis","/mainchain/software/und_cmd/und_validate-genesis.md"]],
  ["v-102fb7f4","/mainchain/software/und_cmd/und_version.html",{"title":""},["/mainchain/software/und_cmd/und_version","/mainchain/software/und_cmd/und_version.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]
