<template><div><h1 id="aws-101" tabindex="-1"><a class="header-anchor" href="#aws-101" aria-hidden="true">#</a> AWS 101</h1>
<h4 id="contents" tabindex="-1"><a class="header-anchor" href="#contents" aria-hidden="true">#</a> Contents</h4>
<nav class="table-of-contents"><ul><li><router-link to="#introduction-to-installing-und-on-aws-ec2-instances">Introduction to installing und on AWS EC2 instances</router-link></li><li><router-link to="#part-1-create-an-ssh-key-pair">Part 1: Create an SSH key pair</router-link></li><li><router-link to="#part-2-create-a-vpc-network">Part 2: Create a VPC (Network)</router-link></li><li><router-link to="#part-3-create-and-launch-an-ec2-instance">Part 3: Create and launch an EC2 instance</router-link></li><li><router-link to="#part-4-log-in-and-configure-instance-via-ssh">Part 4: Log in and configure instance via SSH</router-link><ul><li><router-link to="#part-4-1-install-the-prerequisites">Part 4.1: Install the prerequisites</router-link></li><li><router-link to="#part-4-2-install-the-und-binary">Part 4.2: Install the und binary</router-link></li></ul></li><li><router-link to="#part-5-initialising-your-full-node">Part 5: Initialising your full node</router-link><ul><li><router-link to="#download-the-latest-genesis-file">Download the latest Genesis file.</router-link></li><li><router-link to="#get-seed-nodes">Get seed nodes</router-link></li><li><router-link to="#gas-prices">Gas Prices</router-link></li><li><router-link to="#syncing-the-node-with-statesync">Syncing the node with statesync</router-link></li></ul></li><li><router-link to="#part-6-running-und-as-a-daemon">Part 6: Running und as a daemon</router-link></li><li><router-link to="#part-7-become-a-validator">Part 7: Become a Validator</router-link></li><li><router-link to="#part-8-final-cleanup">Part 8: Final cleanup</router-link></li></ul></nav>
<h2 id="introduction-to-installing-und-on-aws-ec2-instances" tabindex="-1"><a class="header-anchor" href="#introduction-to-installing-und-on-aws-ec2-instances" aria-hidden="true">#</a> Introduction to installing <code v-pre>und</code> on AWS EC2 instances</h2>
<div class="custom-container danger"><p class="custom-container-title">DANGER</p>
<p>If you intend to become a <code v-pre>MainNet</code> Validator, it is <strong>HIGHLY</strong> recommended that you practice on <code v-pre>TestNet</code> first in
order to <em>fully familiarise</em> yourself with the process.</p>
</div>
<p>This guide introduces a <em>very simple</em> &quot;quick start&quot; single AWS EC2 instance, using a VPC with a single public subnet
to connect to a Mainchain Public network. Validator node operators are highly encouraged to explore more sophisticated
architecture configurations to increase the security, reliability and availability of their Validator node - for
example, multi layered network with both private/public subnets, one or more &quot;sentry&quot; full (non-validator) nodes placed
in front of your main (hidden in a private subnet) Validator node to handle and relay communication from the outside
world, and reverse proxy for any RPC access via the sentries etc. in addition to implementing hardware KMS solutions to
protect validator private keys.</p>
<div class="custom-container danger"><p class="custom-container-title">Important</p>
<p>This guide should not be considered the default, full, out of the box solution for a Validator node, but more an &quot;AWS
101&quot; guide to familiarise the reader with the core concepts involved in setting up the minimum AWS EC2 instance and
associated service requirements in order to operate a Validator node. It should be considered a starting point giving
you the initial building blocks from which to build a more sophisticated network/node architecture to support and
protect your Validator node.</p>
</div>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>any public IPs generated by AWS during this guide are not static - they will change if the EC2 instance is restarted. It
is recommended that the reader also investigates AWS's &quot;elastic IPs&quot; (static IPs) for their public-facing node(s).</p>
</div>
<p>Where the guide prompts users to open a terminal, Windows 10 users should use PowerShell.</p>
<p>This guide assumes the reader already has an AWS account.</p>
<h2 id="part-1-create-an-ssh-key-pair" tabindex="-1"><a class="header-anchor" href="#part-1-create-an-ssh-key-pair" aria-hidden="true">#</a> Part 1: Create an SSH key pair</h2>
<p>In order to configure your node(s) and install the necessary software, you will be connecting to the instance via SSH.
SSH connections to an EC2 instance must be authenticated using an SSH Key Pair - password authentication is (and should
be) disabled for security.</p>
<p>In the AWS Console, go to the EC2 dashboard and in the left menu, under &quot;Network &amp; Security&quot;, click &quot;Key Pairs&quot; followed
by the &quot;Create Key Pair&quot; button.</p>
<p>Enter a suitable name, for example <code v-pre>aws-ec2-und-validator-node</code>. Leave the file format as &quot;pem&quot;, and click the &quot;Crete
key pair&quot; button.</p>
<p>This will download a private key called <code v-pre>aws-ec2-und-validator-node.pem</code> (or whatever you called it) which will be used
to log into your EC2 instance via SSH.</p>
<div class="custom-container danger"><p class="custom-container-title">IMPORTANT</p>
<p>Do not lose this key - it is used to access your node's EC2 instance via SSH, and there is no way to recover it from the
AWS console if it's lost. Keep is safe, keep is secure, keep it secret!</p>
</div>
<p>Open a terminal on your local PC, and check if you have a <code v-pre>$HOME/.ssh</code> directory:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">ls</span> -la <span class="token environment constant">$HOME</span>/.ssh
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>If you do not have a <code v-pre>$HOME/.ssh</code> directory, create it:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>$ <span class="token function">mkdir</span> <span class="token environment constant">$HOME</span>/.ssh
$ <span class="token function">chmod</span> <span class="token number">700</span> <span class="token environment constant">$HOME</span>/.ssh
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Next, move the downloaded private key into the <code v-pre>$HOME/.ssh</code> directory, and tighten the file's permissions, replacing any
bold text appropriately:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>$ <span class="token function">mv</span> /path/to/aws-ec2-und-validator-node.pem <span class="token environment constant">$HOME</span>/.ssh
$ <span class="token builtin class-name">cd</span> <span class="token environment constant">$HOME</span>/.ssh
$ <span class="token function">chmod</span> <span class="token number">400</span> aws-ec2-und-validator-node.pem
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="part-2-create-a-vpc-network" tabindex="-1"><a class="header-anchor" href="#part-2-create-a-vpc-network" aria-hidden="true">#</a> Part 2: Create a VPC (Network)</h2>
<p>We need to create a network for our node. This will be a simple VPC with a single public subnet. Validator operators are
encouraged to explore more sophisticated configurations for their production node.</p>
<p>From the Services menu (top-left in the header) in AWS Console, scroll down to &quot;Networking &amp; Content Delivery&quot; and
click &quot;VPC&quot;, then click the &quot;Launch VPC Wizard&quot; button.</p>
<ol>
<li>Select the &quot;VPC with a single public subnet&quot; and click &quot;Select&quot;</li>
<li>Leave the defaults and choose a suitable name in the &quot;VPC Name&quot; section.</li>
<li>Choose a more descriptive name for the Subnet, then click the &quot;Create VPC&quot; button.</li>
</ol>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>The names you choose can be anything, but should make the VPC and subnet easily identifiable to you. These names will
not be public and only visible to you through the AWS console.</p>
</div>
<p>Next, we need to configure the VPC to automatically assign a public IP to instances in the network.</p>
<ol>
<li>In the left menu of the VPC Dashboard, click &quot;Subnets&quot;.</li>
<li>Select your new subnet from the list, and click the &quot;Actions&quot; dropdown, followed by &quot;Modify auto-assign IP settings&quot;.</li>
<li>Tick the &quot;Auto assign IPv4&quot; box, and click &quot;Save&quot;.</li>
</ol>
<h2 id="part-3-create-and-launch-an-ec2-instance" tabindex="-1"><a class="header-anchor" href="#part-3-create-and-launch-an-ec2-instance" aria-hidden="true">#</a> Part 3: Create and launch an EC2 instance</h2>
<p>The EC2 instance is the Virtual Machine where the node will be installed an run. We'll create and launch a single Linux
instance, and connect it to the network created in the previous part.</p>
<ol>
<li>From the Services menu in AWS Console, click &quot;EC2&quot; under &quot;Compute&quot;, followed by the &quot;Launch Instance&quot; button.</li>
<li>On the &quot;1. Choose AMI&quot; tab, use the search input to find the AMI ID &quot;ami-0f2b4fc905b0bd1f1&quot;. Click &quot;Community AMIs&quot;
in the results, find &quot;CentOS Linux 7 x86_64 HVM EBS ENA&quot; and click the &quot;Select&quot; button.</li>
<li>On the &quot;2. Choose Instance Type&quot; tab, tick <code v-pre>t2.small</code> or <code v-pre>t2.medium</code> and click &quot;Next: Configure Instance Details&quot;.</li>
<li>In the &quot;Network&quot; section, select the VPC created in the previous part. Leave the rest as the defaults, and click
the &quot;6. Configure Security Group&quot; tab at the top.</li>
<li>Give the security group a meaningful name and description - for example &quot;und-validator-node&quot;. You will be able to
find and edit this security group in the AWS EC2 console, under &quot;Network &amp; Security -&gt; Security Groups&quot; once it has
been created.</li>
</ol>
<p>Next, we need to configure some firewall rules for the instance. There is already a default rule for SSH (port 22)
access, but this needs tightening to restrict SSH access. We also need to add rules for P2P so the node can communicate
with other nodes, and RPC so that you can broadcast Txs to your own node.</p>
<ol>
<li>In the &quot;Source&quot; column, for the SSH rule, click the dropdown that currently says &quot;Custom&quot; and select &quot;My IP&quot;. This
will ensure only your computer's IP can log in via SSH. Keep in mind, you will need to update this value if you do
not have a static IP for your PC. This step is important, since the default value of <code v-pre>0.0.0.0/0</code> means that anyone,
anywhere can attempt to access your EC2 instance via SSH.</li>
</ol>
<div class="custom-container tip"><p class="custom-container-title">Note</p>
<p>if your IP changes, you will need to update this value.</p>
</div>
<ol start="2">
<li>Add a description, for example &quot;SSH for my PC&quot;</li>
</ol>
<p>Next, we need to create a rule for the <code v-pre>P2P</code> port:</p>
<ol>
<li>Click &quot;Add Rule&quot;</li>
<li>Leave the &quot;type&quot; as &quot;Custom TCP Rule&quot;</li>
<li>Leave the &quot;Protocol&quot; as &quot;TCP</li>
<li>Set the Port Range as <code v-pre>26656</code></li>
<li>Click the drop-down in the Source column and select &quot;Anywhere&quot;</li>
<li>Set the description as something like &quot;UND Node P2P&quot;</li>
</ol>
<p>Next, we need to create a rule for the <code v-pre>RPC</code> port:</p>
<ol>
<li>Click &quot;Add Rule&quot;</li>
<li>Leave the &quot;type&quot; as &quot;Custom TCP Rule&quot;</li>
<li>Leave the &quot;Protocol&quot; as &quot;TCP</li>
<li>Set the Port Range as 26657</li>
<li>Click the drop-down in the Source column and select &quot;My IP&quot; (you want to restrict sending Txs to the node to your own
IP)</li>
<li>Set the description as something like &quot;UND Node RPC&quot;</li>
</ol>
<div class="custom-container tip"><p class="custom-container-title">Note</p>
<p>port <code v-pre>26657</code> can be closed on your Validator node once you have registered your validator.</p>
</div>
<p><strong>Next</strong>, click on the <strong>&quot;4. Add Storage&quot;</strong> tab.</p>
<div class="custom-container tip"><p class="custom-container-title">Note</p>
<p>As the state DB grows, the disk size requirements will grow. Check in our <a href="https://discord.gg/SeB69w5" target="_blank" rel="noopener noreferrer">Discord<ExternalLinkIcon/></a>
for the latest values</p>
</div>
<ol>
<li>Change the size from 10 to <strong>100</strong> Gb.</li>
<li>Optionally, configure disk encryption.</li>
</ol>
<p>Click &quot;Review and Launch&quot;</p>
<p>Review the details are correct, then click &quot;Launch&quot;. This will prompt you to select a key pair to use on the instance.
Select the key you created in Part 1.</p>
<p>Once launched, make a note of the instance ID (top box titled &quot;Your instances are now launching&quot;), click your instance
ID link in the same box. This will take you to the Instances console, with your new instance already highlighted. Click
the pencil icon in the &quot;Name&quot; column, and give your instance a name.</p>
<p>Finally, make a note of the &quot;IPv4 Public IP&quot; value for your instance - you will need this to log in via SSH in the next
part.</p>
<h2 id="part-4-log-in-and-configure-instance-via-ssh" tabindex="-1"><a class="header-anchor" href="#part-4-log-in-and-configure-instance-via-ssh" aria-hidden="true">#</a> Part 4: Log in and configure instance via SSH</h2>
<p>We now need to log in to the EC2 instance, install the prerequisites, then install and configure the UND node software.
This will all be done via SSH.</p>
<div class="custom-container tip"><p class="custom-container-title">Note</p>
<p>any text in <code v-pre>[square_brackets]</code> (<em>including</em> the square brackets) in the following commands should be replaced with your
own values. For example, <code v-pre>[aws_private_key]</code> should be replaced with the name of the file downloaded
in <a href="#part-1-create-an-ssh-key-pair">Part 1</a>, and <code v-pre>[vm_ip]</code> with the public IP address of your EC2 instance.</p>
</div>
<p>The default username for our CentOS EC2 instance is <code v-pre>centos</code>.</p>
<p>Note for Windows users: Windows 10 should have an SSH client available in the PowerShell terminal. Older Windows
versions will require <a href="https://www.chiark.greenend.org.uk/~sgtatham/putty/" target="_blank" rel="noopener noreferrer">PuTTY<ExternalLinkIcon/></a>.</p>
<p>In a terminal on your local PC, run the following:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">ssh</span> -i <span class="token environment constant">$HOME</span>/.ssh/<span class="token punctuation">[</span>aws_private_key<span class="token punctuation">]</span> centos@<span class="token punctuation">[</span>vm_ip<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>This will log you in to the EC2 instance via SSH.</p>
<h3 id="part-4-1-install-the-prerequisites" tabindex="-1"><a class="header-anchor" href="#part-4-1-install-the-prerequisites" aria-hidden="true">#</a> Part 4.1: Install the prerequisites</h3>
<p>Once logged in to the VM via SSH, run:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> yum update -y
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Install EPEL:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> yum <span class="token function">install</span> epel-release -y
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Finally, install the following additional software:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> yum <span class="token function">install</span> <span class="token function">nano</span> jq <span class="token function">wget</span> -y
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="part-4-2-install-the-und-binary" tabindex="-1"><a class="header-anchor" href="#part-4-2-install-the-und-binary" aria-hidden="true">#</a> Part 4.2: Install the und binary</h3>
<p>The latest pre-compiled binaries are available for download from
<a href="https://github.com/unification-com/mainchain/releases" target="_blank" rel="noopener noreferrer">https://github.com/unification-com/mainchain/releases<ExternalLinkIcon/></a>.</p>
<ul>
<li>The <code v-pre>und</code> binary has been compiled for Linux, OSX and Windows.</li>
</ul>
<p>Download the latest version:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">wget</span> https://github.com/unification-com/mainchain/releases/download/1.5.1/und_v1.5.1_linux_x86_64.tar.gz
<span class="token function">wget</span> https://github.com/unification-com/mainchain/releases/download/1.5.1/checksums.txt
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Once downloaded, you can verify the SHA256 checksum against those listed in the release's <code v-pre>checksums.txt</code>, for example:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>$ openssl dgst -sha256 und_v1.5.1_linux_x86_64.tar.gz
SHA256<span class="token punctuation">(</span>und_v1.5.1_linux_x86_64.tar.gz<span class="token punctuation">)</span><span class="token operator">=</span> <span class="token punctuation">..</span>.12324abcd<span class="token punctuation">..</span>.
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Extract them and copy the binaries to a suitable location - preferably a location in your <code v-pre>$PATH</code> environment variable,
for example <code v-pre>/usr/local/bin</code>.</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">tar</span> -zxvf und_v1.5.1_linux_x86_64.tar.gz
<span class="token function">sudo</span> <span class="token function">mv</span> und /usr/local/bin/und
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Once installed, verify:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">which</span> und
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>should output:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>/usr/local/bin/und
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>and:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>und version --log_level<span class="token operator">=</span><span class="token string">""</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>The output should match the latest release version tag.</p>
<h2 id="part-5-initialising-your-full-node" tabindex="-1"><a class="header-anchor" href="#part-5-initialising-your-full-node" aria-hidden="true">#</a> Part 5: Initialising your full node</h2>
<p>We'll now initialise and configure the <code v-pre>und</code> node itself. As previously, any text in <code v-pre>[square_brackets]</code> in the
following commands should be replaced with your own values accordingly. If you are not currently logged in to the EC2
instance via SSH, do so.</p>
<p>Once logged in, run:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>und init <span class="token punctuation">[</span>your_node_tag<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><code v-pre>[your_node_tag]</code> can be any ID you like, but is limited to ASCII characters (alphanumeric characters, hyphens and
underscores)</p>
<h3 id="download-the-latest-genesis-file" tabindex="-1"><a class="header-anchor" href="#download-the-latest-genesis-file" aria-hidden="true">#</a> Download the latest Genesis file.</h3>
<div class="custom-container danger"><p class="custom-container-title">IMPORTANT</p>
<p>Please ensure you download the correct genesis for the network you would like to join! Remember to change the output
directory in the command below if you are using something other than the default <code v-pre>$HOME/.und_mainchain</code> directory!</p>
</div>
<p>To spin up your new node, download the latest <code v-pre>genesis.json</code> for the network you would like to join:</p>
<h4 id="testnet" tabindex="-1"><a class="header-anchor" href="#testnet" aria-hidden="true">#</a> TestNet</h4>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> https://raw.githubusercontent.com/unification-com/testnet/master/latest/genesis.json <span class="token operator">></span> <span class="token environment constant">$HOME</span>/.und_mainchain/config/genesis.json
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h4 id="mainnet" tabindex="-1"><a class="header-anchor" href="#mainnet" aria-hidden="true">#</a> MainNet</h4>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> https://raw.githubusercontent.com/unification-com/mainnet/master/latest/genesis.json <span class="token operator">></span> <span class="token environment constant">$HOME</span>/.und_mainchain/config/genesis.json
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Get the current chain ID from genesis. Make a note of the output, it'll be required in commands later in the guide.
Command is all on one line:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>$ jq --raw-output <span class="token string">'.chain_id'</span> <span class="token environment constant">$HOME</span>/.und_mainchain/config/genesis.json
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="get-seed-nodes" tabindex="-1"><a class="header-anchor" href="#get-seed-nodes" aria-hidden="true">#</a> Get seed nodes</h3>
<div class="custom-container danger"><p class="custom-container-title">IMPORTANT</p>
<p>Please ensure you get the correct seed node information for the network you would like to join! Remember to change the
directory if you are using something other than the default <code v-pre>$HOME/.und_mainchain</code> directory!
For this guide, we are using <code v-pre>/mnt/disks/data/.und_mainchain</code> for the node's home directory.</p>
</div>
<p>Your node will need to know at least one seed node in order to join the network
and begin P2P communication with other nodes in the network. The latest seed information will always be available at
each network's respective Github repo:</p>
<h4 id="testnet-https-github-com-unification-com-testnet-blob-master-latest-seed-nodes-md" tabindex="-1"><a class="header-anchor" href="#testnet-https-github-com-unification-com-testnet-blob-master-latest-seed-nodes-md" aria-hidden="true">#</a> TestNet: <a href="https://github.com/unification-com/testnet/blob/master/latest/seed_nodes.md" target="_blank" rel="noopener noreferrer">https://github.com/unification-com/testnet/blob/master/latest/seed_nodes.md<ExternalLinkIcon/></a></h4>
<h4 id="mainnet-https-github-com-unification-com-mainnet-blob-master-latest-seed-nodes-md" tabindex="-1"><a class="header-anchor" href="#mainnet-https-github-com-unification-com-mainnet-blob-master-latest-seed-nodes-md" aria-hidden="true">#</a> MainNet: <a href="https://github.com/unification-com/mainnet/blob/master/latest/seed_nodes.md" target="_blank" rel="noopener noreferrer">https://github.com/unification-com/mainnet/blob/master/latest/seed_nodes.md<ExternalLinkIcon/></a></h4>
<p>Go to the repo for the network you are connecting to and copy one or more of the seed nodes (you only need
the <code v-pre>id@address:port</code>)</p>
<p>Edit your node configuration file using nano:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">nano</span> /path/to/.und_mainchain/config/config.toml
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Hit <kbd>Ctrl</kbd>+<kbd>W</kbd>, type <code v-pre>[p2p]</code> (including the square brackets) and hit return - this will take you to
the <code v-pre>[p2p]</code> section of the config file, which begins with:</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>##### peer to peer configuration options #####
[p2p]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Find the <code v-pre>seeds = &quot;&quot;</code> variable about 12 lines below, and add the seed node information between the double quotes (comma
separated, no spaces if more than one). For example:</p>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">seeds</span> <span class="token punctuation">=</span> <span class="token string">"node_id@ip:port"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Next, hit <kbd>Ctrl</kbd>+<kbd>W</kbd>, type <code v-pre>[rpc]</code> (including the square brackets) and hit return - this will take you
to the <code v-pre>[rpc]</code> section of the config file, which begins with:</p>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token comment">##### rpc server configuration options #####</span>
<span class="token punctuation">[</span><span class="token table class-name">rpc</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>About 3 lines under this, find:</p>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">laddr</span> <span class="token punctuation">=</span> <span class="token string">"tcp://127.0.0.1:26657"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Change the value to:</p>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">laddr</span> <span class="token punctuation">=</span> <span class="token string">"tcp://0.0.0.0:26657"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Hit <kbd>Ctrl</kbd>+<kbd>X</kbd> followed by <code v-pre>y</code> and then return to save the file and exit nano.</p>
<div class="custom-container warning"><p class="custom-container-title">Note</p>
<p>you should revert the [rpc] configuration for port 26657 to:</p>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">laddr</span> <span class="token punctuation">=</span> <span class="token string">"tcp://127.0.0.1:26657"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>once you have run the <code v-pre>create-validator</code> command below. See <a href="#part-8-final-cleanup">Part 8: Final cleanup</a> for further
details.</p>
</div>
<h3 id="gas-prices" tabindex="-1"><a class="header-anchor" href="#gas-prices" aria-hidden="true">#</a> Gas Prices</h3>
<p>It is good practice to set the minimum-gas-prices value in <code v-pre>$HOME/.und_mainchain/config/app.toml</code>, in order to protect
your full node from spam transactions. This should be set as a decimal value in <code v-pre>nund</code>, and the recommended value is
currently <code v-pre>25.0nund</code>. This means your node will ignore any Txs with a gas price below this value. To do so, open
up <code v-pre>$HOME/.und_mainchain/config/app.toml</code> in a text editor, and set <code v-pre>minimum-gas-prices</code></p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">nano</span> <span class="token environment constant">$HOME</span>/.und_mainchain/config/app.toml
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Change:</p>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">minimum-gas-prices</span> <span class="token punctuation">=</span> <span class="token string">""</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>To, for example:</p>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">minimum-gas-prices</span> <span class="token punctuation">=</span> <span class="token string">"25.0nund"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Hit <kbd>Ctrl</kbd>+<kbd>X</kbd> followed by <code v-pre>y</code> and then return to save the file and exit nano.</p>
<h3 id="syncing-the-node-with-statesync" tabindex="-1"><a class="header-anchor" href="#syncing-the-node-with-statesync" aria-hidden="true">#</a> Syncing the node with <code v-pre>statesync</code></h3>
<p>Cosmos SDK &gt;= 0.42, which is used by the latest <code v-pre>und</code> software, can use State Syncing  from Snapshots to quickly
sync your node from a safe checkpoint. This potentially reduces the sync time to no more than an hour or so, and in
most cases mere minutes.</p>
<p>Setting this up requires a few more steps</p>
<ol>
<li>Run the following command to get the latest block hash and height. For <strong>TestNet</strong>:</li>
</ol>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> -s https://rest-testnet.unification.io/blocks/latest <span class="token operator">|</span> jq <span class="token string">'.|[.block_id.hash,.block.header.height]'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>For <strong>MainNet</strong>:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> -s https://rest.unification.io/blocks/latest <span class="token operator">|</span> jq <span class="token string">'.|[.block_id.hash,.block.header.height]'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Example output:</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code><span class="token punctuation">[</span>
  <span class="token string">"820275B5EE63EDA2923886A01C0B1196A7CE1D96A89FA0D774942999C6698AAC"</span><span class="token punctuation">,</span>
  <span class="token string">"1052423"</span>
<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="2">
<li>Using the output from the above command, configure <code v-pre>[statesync]</code> section in <code v-pre>.und_mainchain/config.toml</code>:</li>
</ol>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">enable</span> <span class="token punctuation">=</span> <span class="token boolean">true</span>
<span class="token key property">rpc_servers</span> <span class="token punctuation">=</span> <span class="token string">"TWO_RPC_NODES"</span>
<span class="token key property">trust_height</span> <span class="token punctuation">=</span> <span class="token number">1052423</span>
<span class="token key property">trust_hash</span> <span class="token punctuation">=</span> <span class="token string">"820275B5EE63EDA2923886A01C0B1196A7CE1D96A89FA0D774942999C6698AAC"</span>
<span class="token key property">trust_period</span> <span class="token punctuation">=</span> <span class="token string">"168h0m0s"</span>
<span class="token key property">discovery_time</span> <span class="token punctuation">=</span> <span class="token string">"30s"</span>
<span class="token key property">temp_dir</span> <span class="token punctuation">=</span> <span class="token string">""</span>
<span class="token key property">chunk_request_timeout</span> <span class="token punctuation">=</span> <span class="token string">"60s"</span>
<span class="token key property">chunk_fetchers</span> <span class="token punctuation">=</span> <span class="token string">"4"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>The <code v-pre>rpc_servers</code> requires two RPC nodes for verification.</p>
<p>For <strong>TestNet</strong>, replace <code v-pre>TWO_RPC_NODES</code> with:</p>
<p><code v-pre>sync1-testnet.unification.io:26657,sync2-testnet.unification.io:26657</code></p>
<p>For <strong>MainNet</strong>:</p>
<p><code v-pre>sync1.unification.io:26657,sync2.unification.io:26657</code></p>
<p>e.g.:</p>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">rpc_servers</span> <span class="token punctuation">=</span> <span class="token string">"sync1.unification.io:26657,sync2.unification.io:26657"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Or any RPC servers of your choice for the target network.</p>
<ol start="3">
<li>Start your node</li>
</ol>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>und start --home<span class="token operator">=</span>/path/to/.und_mainchain
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>you should start seeing the following:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token number">11</span>:53AM INF Discovered new snapshot <span class="token assign-left variable">format</span><span class="token operator">=</span><span class="token number">1</span> <span class="token assign-left variable">hash</span><span class="token operator">=</span><span class="token string">"V0���&amp;�U1�J0�yP4A%�/���GŽ@<span class="token entity" title="\x05">\x05</span>�&lt;�j"</span> <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1051600</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>statesync
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>After a few seconds (or at most, minutes), you should see your node start downloading the blocks:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token number">11</span>:56AM INF received proposal <span class="token assign-left variable">module</span><span class="token operator">=</span>consensus <span class="token assign-left variable">proposal</span><span class="token operator">=</span><span class="token punctuation">{</span><span class="token string">"Type"</span>:32,<span class="token string">"block_id"</span>:<span class="token punctuation">{</span><span class="token string">"hash"</span><span class="token builtin class-name">:</span><span class="token string">"632E122ADDF385954FB8598FEE7D89EB09D7E93746FB36D2F12DECFEB7F07D9E"</span>,<span class="token string">"parts"</span>:<span class="token punctuation">{</span><span class="token string">"hash"</span><span class="token builtin class-name">:</span><span class="token string">"E8246C504B9BC14275874A90C95E6AA035678302AD3BF9269B6F253B04C038BE"</span>,<span class="token string">"total"</span>:1<span class="token punctuation">}</span><span class="token punctuation">}</span>,<span class="token string">"height"</span>:1052494,<span class="token string">"pol_round"</span>:-1,<span class="token string">"round"</span>:0,<span class="token string">"signature"</span><span class="token builtin class-name">:</span><span class="token string">"HYJz0rV7o6bNm7za82sj1Az1rV25qVkLh9Y4s0K95nf86uVq+YmuDIf3LtIP7pDfFEYErxNVyeSplPGh7IVHDQ=="</span>,<span class="token string">"timestamp"</span><span class="token builtin class-name">:</span><span class="token string">"2022-05-19T10:56:03.273030584Z"</span><span class="token punctuation">}</span>
<span class="token number">11</span>:56AM INF received complete proposal block <span class="token assign-left variable">hash</span><span class="token operator">=</span>632E122ADDF385954FB8598FEE7D89EB09D7E93746FB36D2F12DECFEB7F07D9E <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1052494</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>consensus
<span class="token number">11</span>:56AM INF finalizing commit of block <span class="token assign-left variable">hash</span><span class="token operator">=</span>632E122ADDF385954FB8598FEE7D89EB09D7E93746FB36D2F12DECFEB7F07D9E <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1052494</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>consensus <span class="token assign-left variable">num_txs</span><span class="token operator">=</span><span class="token number">0</span> <span class="token assign-left variable">root</span><span class="token operator">=</span>7EC77102840743503BD71FD89F60FD0B912DD0DE27575408B6AD67990CE4A6B8
<span class="token number">11</span>:56AM INF executed block <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1052494</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>state <span class="token assign-left variable">num_invalid_txs</span><span class="token operator">=</span><span class="token number">0</span> <span class="token assign-left variable">num_valid_txs</span><span class="token operator">=</span><span class="token number">0</span>
<span class="token number">11</span>:56AM INF commit synced <span class="token assign-left variable">commit</span><span class="token operator">=</span>436F6D6D697449447B5B3234312031333020323235203834203837203234372031303220323820323435203234382032372032303920313432203133372031303620353920343520323220323020313737203135342032303320323338203136352030203231322034392031383620313638203433203839203233395D3A3130304634457D
<span class="token number">11</span>:56AM INF committed state <span class="token assign-left variable">app_hash</span><span class="token operator">=</span>F182E15457F7661CF5F81BD18E896A3B2D1614B19ACBEEA500D431BAA82B59EF <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1052494</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>state <span class="token assign-left variable">num_txs</span><span class="token operator">=</span><span class="token number">0</span>
<span class="token number">11</span>:56AM INF indexed block <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1052494</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>txindex
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Hit <kbd>Ctrl</kbd>+<kbd>C</kbd> to stop the node - it will be configured as a background service next.</p>
<div class="custom-container danger"><p class="custom-container-title">IMPORTANT</p>
<p>keep your <code v-pre>$HOME/.und_mainchain/config/node_key.json</code> and <code v-pre>$HOME/.und_mainchain/config/priv_validator_key.json</code> files
safe! These are required for your node to propose and sign blocks. If you ever migrate your node to a different host/VM
instance, you will need these.</p>
</div>
<h2 id="part-6-running-und-as-a-daemon" tabindex="-1"><a class="header-anchor" href="#part-6-running-und-as-a-daemon" aria-hidden="true">#</a> Part 6: Running und as a daemon</h2>
<p>Once you have initialised and tested the <code v-pre>und</code> node, it can be set up as a background daemon on the server
using <code v-pre>systemctl</code>. This means that you can easily start/stop/restart the service, and do not need to leave the SSH
session open while <code v-pre>und</code> is running.</p>
<p>If you're not logged in to your EC2 instance via SSH, log in. If you are still logged in, and have not stopped the <code v-pre>und</code>
node, hit <kbd>Ctrl</kbd>+<kbd>C</kbd> to stop the node.</p>
<p>We need to use the nano text editor to create the service configuration. Run:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> <span class="token function">nano</span> /etc/systemd/system/und.service
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>At a minimum, the service configuration should contain the following, replacing <code v-pre>USERNAME</code> and <code v-pre>FULL_PATH_TO</code>
with your own values:</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>[Unit]
Description=Unification Mainchain Validator Node

[Service]
User=USERNAME
Group=USERNAME
WorkingDirectory=/home/USERNAME
ExecStart=/usr/local/bin/und start --home /FULL_PATH_TO/.und_mainchain
LimitNOFILE=4096

[Install]
WantedBy=default.target
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>It is entirely possible to create a more sophisticated service definition should you desire.</p>
<div class="custom-container tip"><p class="custom-container-title">Note</p>
<p><strong>Also see</strong>: <RouterLink to="/mainchain/migrations/cosmovisor.html">Using Cosmovisor with und: Quick Start</RouterLink> for details on running <code v-pre>und</code> with
<code v-pre>cosmovisor</code>.</p>
</div>
<p>Next, inform <code v-pre>systemctl</code> of the new service:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> systemctl daemon-reload
<span class="token function">sudo</span> systemctl <span class="token builtin class-name">enable</span> und
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>The service can now be started:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> systemctl start und
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>and stopped:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> systemctl stop und
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>in the background.</p>
<p>Finally, you can monitor the log output for the service by running:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>$ <span class="token function">sudo</span> journalctl -u und --follow
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>and use <kbd>Ctrl</kbd>+<kbd>C</kbd> to exit the journalctl command. You can now log out of your SSH session and und
will continue running in the background.</p>
<h2 id="part-7-become-a-validator" tabindex="-1"><a class="header-anchor" href="#part-7-become-a-validator" aria-hidden="true">#</a> Part 7: Become a Validator</h2>
<p>Important: ensure your node has fully synced with the network before continuing.
If not already logged in, log in to your EC2 instance via SSH, and run:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> journalctl -u und --follow
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Once fully synced (check the downloaded height against the current clock in the block explorer), hit <kbd>Ctrl</kbd>
+<kbd>C</kbd> to quit <code v-pre>journalctl</code> ( <code v-pre>und</code> will continue to run in the background).</p>
<p>You will need your Validator node's Tendermint public key in order to register it on the Mainchain network as a
validator. Whilst still in the SSH session, run:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>und tendermint show-validator
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Make a note of the output, as you will need this in later commands, where it will be referred to
as <code v-pre>[you_validator_public_key]</code>.</p>
<p>You can now exit the SSH session - the rest of the commands will be run in a terminal on your local PC.</p>
<p>Go
to <a href="https://github.com/unification-com/mainchain/releases/latest" target="_blank" rel="noopener noreferrer">https://github.com/unification-com/mainchain/releases/latest<ExternalLinkIcon/></a>
and download the latest <code v-pre>und</code> archive for your OS - for example, <code v-pre>und_v1.5.1_windows_x86_64.tar.gz</code>.</p>
<p>Open a terminal/PowerShell, and <code v-pre>cd</code> into the directory where you extracted the <code v-pre>und</code> executable:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token builtin class-name">cd</span> path/to/extracted/und_directory
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>As previously, any text in <code v-pre>[square_brackets]</code> in the following commands should be replaced with your own values
accordingly.</p>
<p>If you do not already have a wallet/account, you can create one (on your local PC, not in the SSH session) by running:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>./und keys <span class="token function">add</span> account_name
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>If you already have a wallet, you can import the account using:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>./und keys <span class="token function">add</span> account_name --recover
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>in which case, you will be prompted for the mnemonic and a password to secure the wallet.</p>
<p>From here, it is assumed the reader has an account with sufficient FUND from which to self-delegate and create their
Validator node. The account you use to self-delegate will become the &quot;owner&quot; account of the Validator node.</p>
<p>On your local PC, run the following command, replacing any text in <code v-pre>[square_brackets]</code> accordingly with your own values:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>./und tx staking create-validator <span class="token punctuation">\</span>
--amount<span class="token operator">=</span><span class="token punctuation">[</span>stake_in_nund<span class="token punctuation">]</span> <span class="token punctuation">\</span>
--pubkey<span class="token operator">=</span><span class="token punctuation">[</span>your_validator_public_key<span class="token punctuation">]</span> <span class="token punctuation">\</span>
--moniker<span class="token operator">=</span><span class="token string">"[your_ev_moniker]"</span> <span class="token punctuation">\</span>
--website<span class="token operator">=</span><span class="token string">"[your_website]"</span> <span class="token punctuation">\</span>
--details<span class="token operator">=</span><span class="token string">"[description]"</span> <span class="token punctuation">\</span>
--security-contact<span class="token operator">=</span><span class="token string">"[security_email]"</span> <span class="token punctuation">\</span>
--chain-id<span class="token operator">=</span><span class="token punctuation">[</span>chain_id<span class="token punctuation">]</span> <span class="token punctuation">\</span>
--commission-rate<span class="token operator">=</span><span class="token string">"[0.10]"</span> <span class="token punctuation">\</span>
--commission-max-rate<span class="token operator">=</span><span class="token string">"[0.20]"</span> <span class="token punctuation">\</span>
--commission-max-change-rate<span class="token operator">=</span><span class="token string">"[0.01]"</span> <span class="token punctuation">\</span>
--min-self-delegation<span class="token operator">=</span><span class="token string">"1"</span> <span class="token punctuation">\</span>
--gas<span class="token operator">=</span><span class="token string">"auto"</span> <span class="token punctuation">\</span>
--gas-prices<span class="token operator">=</span><span class="token string">"25.0nund"</span> <span class="token punctuation">\</span>
--gas-adjustment<span class="token operator">=</span><span class="token number">1.5</span> <span class="token punctuation">\</span>
--from<span class="token operator">=</span>account_name <span class="token punctuation">\</span>
--node<span class="token operator">=</span>tcp://<span class="token punctuation">[</span>vm_ip<span class="token punctuation">]</span>:26657
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>[stake_in_nund]</code> = (required) the amount of FUND in <code v-pre>nund</code> you are self-delegating. You can use
the <code v-pre>und convert 1000 fund nund</code> command to convert FUND to nund. E.g. <code v-pre>1000000000000nund</code>.</p>
<div class="custom-container warning"><p class="custom-container-title">Note</p>
<p>do not enter more nund than you have in your wallet and ensure you have enough left over to pay for this and future Tx
fees!</p>
</div>
<p><code v-pre>[your_validator_public_key]</code> = (required) the public key output from the previous und tendermint show-validator
command.</p>
<p><code v-pre>[your_ev_moniker]</code> = (required) a publicly visible ID/tag for your Validator node.</p>
<p><code v-pre>[your_website]</code> = (optional) website promoting your node</p>
<p><code v-pre>[description]</code> = (optional) short description of your node</p>
<p><code v-pre>[security_email]</code> = (optional) security contact for your organisation</p>
<p><code v-pre>[chain_id]</code> = the network (e.g. <code v-pre>FUND-TestNet-2</code>, or <code v-pre>FUND-MainNet-2</code>) you are creating a
validator on - this was obtained earlier in the guide via the <code v-pre>jq</code> command</p>
<p><code v-pre>[account_name]</code> = the account self-delegating the FUND, previously created/imported with the <code v-pre>und keys add</code> command</p>
<p><code v-pre>[vm_ip]</code> = the IP address of your EC2 instance running the full node - you can get this from your AWS EC2 Instances
console.</p>
<h4 id="commission-rates" tabindex="-1"><a class="header-anchor" href="#commission-rates" aria-hidden="true">#</a> Commission Rates</h4>
<p>Your commission rates can be set using the <code v-pre>--commission-rate</code>
, <code v-pre>--commission-max-change-rate and</code> <code v-pre>--commission-max-rate</code> flags.</p>
<p><code v-pre>--commission-rate</code>: The % commission you will earn from delegators' rewards. Keeping this low can attract more
delegators to your node.</p>
<p><code v-pre>--commission-max-rate</code>: The maximum you will ever increase your commission rate to - you cannot raise commission above
this value. Again, keeping this low can attract more delegators.</p>
<p><code v-pre>--commission-max-change-rate</code>: The maximum you can increase the commission-rate by per day. For example, if your
maximum change rate is 0.01, you can only make changes in 0.01 increments, so from 0.10 (10%) to 0.11 (11%).</p>
<div class="custom-container warning"><p class="custom-container-title">WARNING</p>
<p>The values for <code v-pre>--commission-max-change-rate</code> and <code v-pre>--commission-max-rate</code> flags cannot be changed after the
create-validator command has been run.</p>
</div>
<p>Finally, the <code v-pre>--min-self-delegation</code> flag is the minimum amount of <code v-pre>nund</code> you are required to keep self-delegated to
your validtor, meaning you must always have at least this amount self-delegated to your node.</p>
<p>For example:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>./und tx staking create-validator <span class="token punctuation">\</span>
--amount<span class="token operator">=</span>1000000000000nund <span class="token punctuation">\</span>
--pubkey<span class="token operator">=</span>undvalconspub1zcjduepq6yq7drzefkavsrxhxk69cy63tj3r<span class="token punctuation">..</span>. <span class="token punctuation">\</span>
--moniker<span class="token operator">=</span><span class="token string">"MyAwesomeNode"</span> <span class="token punctuation">\</span>
--website<span class="token operator">=</span><span class="token string">"https://my-node-site.com"</span> <span class="token punctuation">\</span>
--details<span class="token operator">=</span><span class="token string">"My node is awesome"</span> <span class="token punctuation">\</span>
--security-contact<span class="token operator">=</span><span class="token string">"security@my-node-site.com"</span> <span class="token punctuation">\</span>
--chain-id<span class="token operator">=</span>FUND-TestNet-2 <span class="token punctuation">\</span>
--commission-rate<span class="token operator">=</span><span class="token string">"0.05"</span> <span class="token punctuation">\</span>
--commission-max-rate<span class="token operator">=</span><span class="token string">"0.10"</span> <span class="token punctuation">\</span>
--commission-max-change-rate<span class="token operator">=</span><span class="token string">"0.01"</span> <span class="token punctuation">\</span>
--min-self-delegation<span class="token operator">=</span><span class="token string">"1"</span> <span class="token punctuation">\</span>
--gas<span class="token operator">=</span><span class="token string">"auto"</span> <span class="token punctuation">\</span>
--gas-prices<span class="token operator">=</span><span class="token string">"25.0nund"</span> <span class="token punctuation">\</span>
--gas-adjustment<span class="token operator">=</span><span class="token number">1.5</span> <span class="token punctuation">\</span>
--from<span class="token operator">=</span>my_new_wallet <span class="token punctuation">\</span>
--node<span class="token operator">=</span>tcp://33.44.55.66:26657
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Your validator node should now be registered and contributing to the network. To verify, on you local PC, run the
following:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>./und query staking validator <span class="token punctuation">\</span>
<span class="token variable"><span class="token variable">$(</span>und keys show <span class="token punctuation">[</span>account_name<span class="token punctuation">]</span> --bech<span class="token operator">=</span>val -a<span class="token variable">)</span></span> <span class="token punctuation">\</span>
--chain-id<span class="token operator">=</span><span class="token punctuation">[</span>chain_id<span class="token punctuation">]</span> <span class="token punctuation">\</span>
--node<span class="token operator">=</span>tcp://<span class="token punctuation">[</span>vm_ip<span class="token punctuation">]</span>:26657
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Replacing <code v-pre>[account_name]</code>, <code v-pre>[chain_id]</code> and <code v-pre>[vm_ip]</code> accordingly. Assuming you are going through this guide
on <code v-pre>TestNet</code>, you should also see your node listed
in <a href="https://explorer-testnet.unification.io/validators" target="_blank" rel="noopener noreferrer">https://explorer-testnet.unification.io/validators<ExternalLinkIcon/></a></p>
<h2 id="part-8-final-cleanup" tabindex="-1"><a class="header-anchor" href="#part-8-final-cleanup" aria-hidden="true">#</a> Part 8: Final cleanup</h2>
<p>Finally, it's a good idea to close the <strong>RPC</strong> port (<code v-pre>26657</code>) on your validator node, leaving only the <strong>P2P</strong>
port (<code v-pre>26656</code>) open so that it can communicate with other nodes. This can be done by deleting the firewall rule for the
RPC port, and by reverting the RPC <code v-pre>laddr</code> configuration value in <code v-pre>config.toml</code> to the <code v-pre>127.0.0.1</code> IP address (which
will restrict the node's RPC access to <code v-pre>localhost</code>).</p>
<p>Further interaction with the network can be done by spinning up a separate non-validator full node (on your local PC for
example), and broadcasting transactions via that node instead.</p>
<div class="custom-container danger"><p class="custom-container-title">Important</p>
<p>Do not alter the <code v-pre>P2P</code> port (<code v-pre>26656</code>) firewall rules. If you do, your validator node will not be able to communicate
with its peers.</p>
</div>
<p>That's it - you should now have a full Validator node up and running on a very basic AWS EC2 instance. Once again -
Validator node operators are highly encouraged to explore more sophisticated architecture configurations to increase the
security, reliability and availability of their Validator node.</p>
</div></template>
