<template><div><h1 id="google-cloud-101" tabindex="-1"><a class="header-anchor" href="#google-cloud-101" aria-hidden="true">#</a> Google Cloud 101</h1>
<h4 id="contents" tabindex="-1"><a class="header-anchor" href="#contents" aria-hidden="true">#</a> Contents</h4>
<nav class="table-of-contents"><ul><li><router-link to="#introduction-to-installing-und-on-google-cloud-vms">Introduction to installing und on Google Cloud VMs</router-link></li><li><router-link to="#part-0-create-a-new-project-enable-apis">Part 0: Create a new Project &amp; Enable APIs</router-link></li><li><router-link to="#part-1-create-an-ssh-key-pair">Part 1: Create an SSH key pair</router-link></li><li><router-link to="#part-2-vpc-network-firewall-rules">Part 2: VPC Network &amp; Firewall rules</router-link><ul><li><router-link to="#_2-1-create-a-vpc">2.1: Create a VPC</router-link></li><li><router-link to="#_2-2-firewall-rules">2.2: Firewall Rules</router-link></li></ul></li><li><router-link to="#part-3-create-a-vm-instance">Part 3: Create a VM Instance</router-link></li><li><router-link to="#part-4-log-in-to-vm-and-configure-via-ssh">Part 4: Log in to VM and configure via SSH</router-link><ul><li><router-link to="#part-4-1-create-and-mount-the-data-drive">Part 4.1: Create and Mount the data drive</router-link></li><li><router-link to="#part-4-2-install-the-prerequisites">Part 4.2: Install the prerequisites</router-link></li><li><router-link to="#part-4-3-install-the-und-binary">Part 4.3: Install the und binary</router-link></li></ul></li><li><router-link to="#part-5-initialising-your-full-node">Part 5: Initialising your full node</router-link><ul><li><router-link to="#download-the-latest-genesis-file">Download the latest Genesis file.</router-link></li><li><router-link to="#get-seed-nodes">Get seed nodes</router-link></li><li><router-link to="#gas-prices">Gas Prices</router-link></li><li><router-link to="#syncing-the-node-with-statesync">Syncing the node with statesync</router-link></li></ul></li><li><router-link to="#part-6-running-und-as-a-daemon">Part 6: Running und as a daemon</router-link></li><li><router-link to="#part-7-become-a-validator">Part 7: Become a Validator</router-link></li><li><router-link to="#part-8-final-cleanup">Part 8: Final cleanup</router-link></li></ul></nav>
<h2 id="introduction-to-installing-und-on-google-cloud-vms" tabindex="-1"><a class="header-anchor" href="#introduction-to-installing-und-on-google-cloud-vms" aria-hidden="true">#</a> Introduction to installing <code v-pre>und</code> on Google Cloud VMs</h2>
<div class="custom-container danger"><p class="custom-container-title">DANGER</p>
<p>If you intend to become a <code v-pre>MainNet</code> Validator, it is <strong>HIGHLY</strong> recommended that you practice on <code v-pre>TestNet</code> first in
order to <em>fully familiarise</em> yourself with the process.</p>
</div>
<p>This guide introduces a <em>very simple</em> &quot;quick start&quot; single Google Cloud VM, using simple network infrastructure to
connect to a Mainchain Public network. Validator node operators are <strong>highly encouraged</strong> to explore more sophisticated
architecture configurations to increase the security, reliability and availability of their Validator node - for
example, multi layered network with both private/public subnets, one or more &quot;sentry&quot; full (non-validator) nodes placed
in front of your main (hidden in a private subnet) Validator node to handle and relay communication from the outside
world, and reverse proxy for any RPC access via the sentries etc. in addition to implementing hardware KMS solutions to
protect validator private keys.</p>
<div class="custom-container danger"><p class="custom-container-title">Important</p>
<p>This guide should not be considered the default, full, out of the box solution for a Validator node, but more an &quot;Google
Cloud 101&quot; guide to familiarise the reader with the core concepts involved in setting up the minimum GC VM and
associated service requirements in order to operate a Validator node. It should be considered a starting point giving
you the initial building blocks from which to build a more sophisticated network/node architecture to support and
protect your Validator node.</p>
</div>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>any public IPs generated by Google Cloud during this guide are not static - they will change if the VM instance is
restarted. It is recommended that the reader also investigates GC static IPs for their public-facing node(s).</p>
</div>
<p>Where the guide prompts users to open a terminal, Windows 10 users should use PowerShell.</p>
<p>This guide assumes the reader already has a Google Cloud account.</p>
<h2 id="part-0-create-a-new-project-enable-apis" tabindex="-1"><a class="header-anchor" href="#part-0-create-a-new-project-enable-apis" aria-hidden="true">#</a> Part 0: Create a new Project &amp; Enable APIs</h2>
<p>If you do not have an existing project for the node, you’ll need to create a new GC project. Click on the menu icon in
the top left of the GC console, and select &quot;Home&quot; followed by &quot;Create new project&quot;. Give the project a suitable name,
check it is in the correct organisation and click &quot;Create&quot;.
Once created, in the organisation/project drop-down (top-left of the console in the header), select your new project
name.</p>
<p>Next, go to &quot;Menu&quot; and click on &quot;APIs &amp; Services&quot;. Click the &quot;Enable APIs and Services&quot; button. From the filter menu on
the left, select &quot;Compute&quot;, then enable billing for &quot;Compute Engine API&quot;.</p>
<h2 id="part-1-create-an-ssh-key-pair" tabindex="-1"><a class="header-anchor" href="#part-1-create-an-ssh-key-pair" aria-hidden="true">#</a> Part 1: Create an SSH key pair</h2>
<p>An SSH key is required to log in to your GC VM - this can be created on your local PC, using the ssh-keygen command.</p>
<p>Open a terminal on your local PC, and check if you have a <code v-pre>$HOME/.ssh</code> directory:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">ls</span> -la <span class="token environment constant">$HOME</span>/.ssh
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>If you do not have a <code v-pre>$HOME/.ssh</code> directory, create it:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>$ <span class="token function">mkdir</span> <span class="token environment constant">$HOME</span>/.ssh
$ <span class="token function">chmod</span> <span class="token number">700</span> <span class="token environment constant">$HOME</span>/.ssh
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Run the following commands, replacing <strong><code v-pre>vmusername</code></strong> with something easily identifiable such as the admin username (
only letters, no spaces) you will choose later in the guide for the VM, and enter a password to encrypt the key when
prompted to do so:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>$ ssh-keygen -t rsa -b <span class="token number">4096</span> -f <span class="token environment constant">$HOME</span>/.ssh/gc_vmusername_id_rsa
$ <span class="token function">chmod</span> <span class="token number">400</span> <span class="token environment constant">$HOME</span>/.ssh/gc_vmusername_id_rsa
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Finally, the public key will be required later in the guide, so open it up in a text editor. The public key counterpart
has the <code v-pre>.pub</code> file extension, e.g. <code v-pre>$HOME/.ssh/gc_vmusername_id_rsa.pub</code></p>
<h2 id="part-2-vpc-network-firewall-rules" tabindex="-1"><a class="header-anchor" href="#part-2-vpc-network-firewall-rules" aria-hidden="true">#</a> Part 2: VPC Network &amp; Firewall rules</h2>
<p>We first need to create a VPC and define some firewall rules that will allow your node to communicate via P2P, and allow
you to broadcast transactions to your node. Validator operators are encouraged to explore more sophisticated
configurations for their production node, and not just rely on the defaults.</p>
<h3 id="_2-1-create-a-vpc" tabindex="-1"><a class="header-anchor" href="#_2-1-create-a-vpc" aria-hidden="true">#</a> 2.1: Create a VPC</h3>
<p>From the Google Cloud console menu, scroll down to &quot;VPC Network&quot; and click &quot;VPC Networks&quot;. Click the &quot;Create VPC
Network&quot; button.</p>
<ol>
<li>Enter a suitable name for the VPC, such as &quot;und-vpc&quot;, and a description.
For &quot;Subnets&quot;, select &quot;Automatic&quot;.</li>
<li>Don’t select any of the predefined firewall rules.</li>
<li>Leave the rest as defaults, and click the &quot;Create&quot; button.</li>
</ol>
<h3 id="_2-2-firewall-rules" tabindex="-1"><a class="header-anchor" href="#_2-2-firewall-rules" aria-hidden="true">#</a> 2.2: Firewall Rules</h3>
<p>First, we need a firewall rule that allows only your local PC’s IP address to connect via SSH. You can find your IP
address by running ifconfig in a terminal, or visiting <a href="https://www.whatismyip.com" target="_blank" rel="noopener noreferrer">https://www.whatismyip.com<ExternalLinkIcon/></a>.</p>
<div class="custom-container tip"><p class="custom-container-title">Note</p>
<p>if your PC’s IP changes, you will need to update this rule in order to connect to your VM.</p>
</div>
<ol>
<li>Click the Menu button in the top left of the GC console, scroll down to &quot;VPC Network&quot; and click &quot;Firewall Rules&quot;.
Click the &quot;Create Firewall Rule&quot; button.</li>
<li>Enter a name for the rule, such as <code v-pre>&quot;und-node-ssh</code>&quot;, and suitable description.
Change the value for &quot;Network&quot; from &quot;<code v-pre>default</code>&quot; to <code v-pre>&quot;und-vpc</code>&quot; (or whatever you called your VPC Network).</li>
<li>For &quot;direction of traffic&quot;, select &quot;Ingres&quot; and for &quot;Action on Match&quot;, select &quot;Allow&quot;</li>
<li>For &quot;Targets&quot;, select &quot;Specified Target Tag&quot;, and enter &quot;<code v-pre>und-node</code>&quot; under &quot;Target Tags&quot; (this will be used as the &quot;
network tag&quot; when creating the VM instance later).</li>
<li>For &quot;Source IP Ranges&quot;, enter <code v-pre>YOUR_IP/32</code>, for example <code v-pre>22.33.44.55/32</code>
Under &quot;Protocols and Ports&quot;, select &quot;specified protocols and ports&quot;, tick &quot;<code v-pre>tcp</code>&quot; and enter <code v-pre>22</code> as the port</li>
<li>Click &quot;Create&quot;</li>
</ol>
<p>Next, we need a firewall rule that allows the node to communicate via P2P.</p>
<ol>
<li>Click the &quot;Create Firewall Rule&quot; button.</li>
<li>Enter a name for the rule, such as &quot;<code v-pre>und-node-p2p</code>&quot;, and suitable description.</li>
<li>Leave logs &quot;off&quot;.</li>
<li>Change the value for &quot;Network&quot; from &quot;default&quot; to &quot;<code v-pre>und-vpc</code>&quot; (or whatever you called your VPC Network)</li>
<li>For &quot;direction of traffic&quot;, select &quot;Ingres&quot; and for &quot;Action on Match&quot;, select &quot;Allow&quot;</li>
<li>For &quot;Targets&quot;, select &quot;Specified Target Tag&quot;, and enter &quot;<code v-pre>und-node</code>&quot; under &quot;Target Tags&quot; (this will be used as the &quot;
network tag&quot; when creating the VM instance later).</li>
<li>For &quot;Source IP Ranges&quot;, enter <code v-pre>0.0.0.0/0</code></li>
<li>Under &quot;Protocols and Ports&quot;, select &quot;specified protocols and ports&quot;, tick &quot;tcp&quot; and enter <code v-pre>26656</code> as the port</li>
<li>Click &quot;Create&quot;.</li>
</ol>
<p>Next, we need to open the RPC port, so that we can broadcast Txs to the node. As with the SSH rule, we should restrict
access to our own IP.</p>
<p>Repeat the steps above. Use &quot;<code v-pre>und-node-rpc</code>&quot; as the name, and <code v-pre>YOUR_IP/32</code> (e.g. <code v-pre>22.33.44.55/32</code>) as the IP range.
Finally, tick &quot;<code v-pre>tcp</code>&quot; and enter <code v-pre>26657</code> as the port. As before, enter &quot;<code v-pre>und-node</code>&quot; under &quot;Target Tags&quot;, ensure you
select &quot;<code v-pre>und-vpc</code>&quot; as the network, and click &quot;Create&quot;.</p>
<div class="custom-container tip"><p class="custom-container-title">Note</p>
<p>port 26657 can be closed on your Validator node once you have registered your validator.</p>
</div>
<h2 id="part-3-create-a-vm-instance" tabindex="-1"><a class="header-anchor" href="#part-3-create-a-vm-instance" aria-hidden="true">#</a> Part 3: Create a VM Instance</h2>
<p>To begin, ensure that billing for Compute Engine API is enabled for the current project. You will also need the public
key for the SSH key created earlier.
We’ll now create a VM for the node.</p>
<p>Click the Navigation Menu icon in the top left of the GC console, and go to Compute -&gt; Compute Engine -&gt; VM Instances.
Click the &quot;Create&quot; button.
Give your VM instance a suitable name.</p>
<ol>
<li>Under &quot;Machine Configuration&quot;, leave &quot;General purpose&quot; selected, along with &quot;N1&quot; for Series.</li>
<li>For &quot;Machine Type&quot;, select &quot;<code v-pre>g1-small&quot;</code></li>
<li>In the &quot;Boot Disk&quot; section click the &quot;Change&quot; button</li>
<li>Select &quot;CentOS&quot; as the operating system, and &quot;CentOS 7&quot; as the version
Leave the disk size as default. Click the &quot;Select&quot; button.</li>
<li>Click the &quot;Management, security, disks, networking, sole-tenancy&quot; link (under &quot;Firewall&quot;).</li>
<li>Click the &quot;Security&quot; tab.</li>
<li>Copy your SSH public key into the input &quot;Enter public SSH key&quot;.</li>
</ol>
<div class="custom-container tip"><p class="custom-container-title">Note</p>
<p>your public key will be in the format: <code v-pre>ssh-rsa PUBLIC_KEY username@host</code>. The &quot;<code v-pre>username@host</code>&quot; part will be used to
define the <strong>admin username</strong> for the VM, e.g. <code v-pre>ssh-rsa PUBLIC_KEY vmusername@host</code></p>
</div>
<ol start="8">
<li>Click the &quot;Networking&quot; tab.</li>
<li>Enter &quot;<code v-pre>und-node</code>&quot; in the &quot;Network tags&quot; input (this is the tag we selected to apply our firewall rules to earlier).</li>
<li>Click the &quot;Network Interface&quot; option, and change the Network from &quot;<code v-pre>default</code>&quot; to &quot;<code v-pre>und-vpc</code>&quot; (or whatever you named
your VPC earlier).</li>
<li>Click in the &quot;Disks&quot; tab. Choose a suitable name, change the &quot;Type&quot; to &quot;SSD Persistant&quot;,
and set the size to 100Gb</li>
<li>Leave the rest of the options as their defaults, and click the &quot;Create&quot; button.</li>
</ol>
<h2 id="part-4-log-in-to-vm-and-configure-via-ssh" tabindex="-1"><a class="header-anchor" href="#part-4-log-in-to-vm-and-configure-via-ssh" aria-hidden="true">#</a> Part 4: Log in to VM and configure via SSH</h2>
<p>Once back on the Instances dashboard, you should see your new VM Instance listed. Find your instance, and make a note of
the public IP address.</p>
<div class="custom-container tip"><p class="custom-container-title">Note</p>
<p>any text in <code v-pre>[square_brackets]</code> (<em>including</em> the square brackets) in the following commands should be replaced with your
own values. For example, vmusername should be replaced with the administrator username entered when creating the VM
in <a href="#part-3-create-a-vm-instance">Part 3</a>.</p>
</div>
<p><strong>Note for Windows users</strong>: Windows 10 should have an SSH client available in the PowerShell terminal. Older Windows
versions will require <a href="https://www.chiark.greenend.org.uk/~sgtatham/putty/" target="_blank" rel="noopener noreferrer">PuTTY<ExternalLinkIcon/></a>.</p>
<p>Open a terminal on your PC, and run:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">ssh</span> -i <span class="token environment constant">$HOME</span>/.ssh/<span class="token punctuation">[</span>gc_vmusername_id_rsa<span class="token punctuation">]</span> <span class="token punctuation">[</span>vmusername<span class="token punctuation">]</span>@<span class="token punctuation">[</span>vm_ip<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="part-4-1-create-and-mount-the-data-drive" tabindex="-1"><a class="header-anchor" href="#part-4-1-create-and-mount-the-data-drive" aria-hidden="true">#</a> Part 4.1: Create and Mount the data drive</h3>
<p>The following commands will create a new partition and format it ready for the state db</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> mkfs.ext4 -m <span class="token number">0</span> -E <span class="token assign-left variable">lazy_itable_init</span><span class="token operator">=</span><span class="token number">0</span>,lazy_journal_init<span class="token operator">=</span><span class="token number">0</span>,discard /dev/sdb
<span class="token function">sudo</span> <span class="token function">mkdir</span> -p /mnt/disks/data
<span class="token function">sudo</span> <span class="token function">mount</span> -o discard,defaults /dev/sdb /mnt/disks/data
<span class="token function">sudo</span> <span class="token function">chmod</span> a+w /mnt/disks/data
<span class="token function">sudo</span> <span class="token function">cp</span> /etc/fstab /etc/fstab.backup
<span class="token builtin class-name">echo</span> <span class="token assign-left variable">UUID</span><span class="token operator">=</span><span class="token variable"><span class="token variable">`</span><span class="token function">sudo</span> blkid -s UUID -o value /dev/sdb<span class="token variable">`</span></span> /mnt/disks/data ext4 discard,defaults,nofail <span class="token number">0</span> <span class="token number">2</span> <span class="token operator">|</span> <span class="token function">sudo</span> <span class="token function">tee</span> -a /etc/fstab
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="part-4-2-install-the-prerequisites" tabindex="-1"><a class="header-anchor" href="#part-4-2-install-the-prerequisites" aria-hidden="true">#</a> Part 4.2: Install the prerequisites</h3>
<p>Update the installed packages:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> yum update -y
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Install the following additional software:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> yum <span class="token function">install</span> <span class="token function">nano</span> jq <span class="token function">wget</span> -y
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="part-4-3-install-the-und-binary" tabindex="-1"><a class="header-anchor" href="#part-4-3-install-the-und-binary" aria-hidden="true">#</a> Part 4.3: Install the <code v-pre>und</code> binary</h3>
<p>The latest pre-compiled binaries are available for download from
<a href="https://github.com/unification-com/mainchain/releases" target="_blank" rel="noopener noreferrer">https://github.com/unification-com/mainchain/releases<ExternalLinkIcon/></a>.</p>
<ul>
<li>The <code v-pre>und</code> binary has been compiled for Linux, OSX and Windows.</li>
</ul>
<p>Download the latest version:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">wget</span> https://github.com/unification-com/mainchain/releases/download/1.5.1/und_v1.5.1_linux_x86_64.tar.gz
<span class="token function">wget</span> https://github.com/unification-com/mainchain/releases/download/1.5.1/checksums.txt
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Once downloaded, you can verify the SHA256 checksum against those listed in the release's <code v-pre>checksums.txt</code>, for example:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>$ openssl dgst -sha256 und_v1.5.1_linux_x86_64.tar.gz
SHA256<span class="token punctuation">(</span>und_v1.5.1_linux_x86_64.tar.gz<span class="token punctuation">)</span><span class="token operator">=</span> <span class="token punctuation">..</span>.12324abcd<span class="token punctuation">..</span>.
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Extract them and copy the binaries to a suitable location - preferably a location in your <code v-pre>$PATH</code> environment variable,
for example <code v-pre>/usr/local/bin</code>.</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">tar</span> -zxvf und_v1.5.1_linux_x86_64.tar.gz
<span class="token function">sudo</span> <span class="token function">mv</span> und /usr/local/bin/und
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Once installed, verify:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">which</span> und
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>should output:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>/usr/local/bin/und
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>and:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>und version --log_level<span class="token operator">=</span><span class="token string">""</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>The output should match the latest release version tag.</p>
<h2 id="part-5-initialising-your-full-node" tabindex="-1"><a class="header-anchor" href="#part-5-initialising-your-full-node" aria-hidden="true">#</a> Part 5: Initialising your full node</h2>
<p>We’ll now initialise and configure the <code v-pre>und</code> node itself. As previously, any text in <code v-pre>[square_brackets]</code> (<em>including</em>
the square brackets) in the following commands should be replaced with your own values accordingly. If you are not
currently logged in to the VM instance via SSH, do so.</p>
<p>Once logged in, run:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>und init <span class="token punctuation">[</span>your_node_tag<span class="token punctuation">]</span> --home<span class="token operator">=</span>/mnt/disks/data/.und_mainchain
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><code v-pre>[your_node_tag]</code> can be any ID you like but is restricted to ASCII characters.</p>
<h3 id="download-the-latest-genesis-file" tabindex="-1"><a class="header-anchor" href="#download-the-latest-genesis-file" aria-hidden="true">#</a> Download the latest Genesis file.</h3>
<div class="custom-container danger"><p class="custom-container-title">IMPORTANT</p>
<p>Please ensure you download the correct genesis for the network you would like to join! Remember to change the output
directory in the command below if you are using something other than the default <code v-pre>$HOME/.und_mainchain</code> directory!</p>
</div>
<p>To spin up your new node, download the latest <code v-pre>genesis.json</code> for the network you would like to join:</p>
<h4 id="testnet" tabindex="-1"><a class="header-anchor" href="#testnet" aria-hidden="true">#</a> TestNet</h4>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> https://raw.githubusercontent.com/unification-com/testnet/master/latest/genesis.json <span class="token operator">></span> <span class="token environment constant">$HOME</span>/.und_mainchain/config/genesis.json
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h4 id="mainnet" tabindex="-1"><a class="header-anchor" href="#mainnet" aria-hidden="true">#</a> MainNet</h4>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> https://raw.githubusercontent.com/unification-com/mainnet/master/latest/genesis.json <span class="token operator">></span> <span class="token environment constant">$HOME</span>/.und_mainchain/config/genesis.json
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Get the current chain ID from genesis. Make a note of the output, it'll be required in commands later in the guide.
Command is all on one line:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>$ jq --raw-output <span class="token string">'.chain_id'</span> /mnt/disks/data/.und_mainchain/.und_mainchain/config/genesis.json
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="get-seed-nodes" tabindex="-1"><a class="header-anchor" href="#get-seed-nodes" aria-hidden="true">#</a> Get seed nodes</h3>
<div class="custom-container danger"><p class="custom-container-title">IMPORTANT</p>
<p>Please ensure you get the correct seed node information for the network you would like to join! Remember to change the
directory if you are using something other than the default <code v-pre>$HOME/.und_mainchain</code> directory!
For this guide, we are using <code v-pre>/mnt/disks/data/.und_mainchain</code> for the node's home directory.</p>
</div>
<p>Your node will need to know at least one seed node in order to join the network
and begin P2P communication with other nodes in the network. The latest seed information will always be available at
each network's respective Github repo:</p>
<h4 id="testnet-https-github-com-unification-com-testnet-blob-master-latest-seed-nodes-md" tabindex="-1"><a class="header-anchor" href="#testnet-https-github-com-unification-com-testnet-blob-master-latest-seed-nodes-md" aria-hidden="true">#</a> TestNet: <a href="https://github.com/unification-com/testnet/blob/master/latest/seed_nodes.md" target="_blank" rel="noopener noreferrer">https://github.com/unification-com/testnet/blob/master/latest/seed_nodes.md<ExternalLinkIcon/></a></h4>
<h4 id="mainnet-https-github-com-unification-com-mainnet-blob-master-latest-seed-nodes-md" tabindex="-1"><a class="header-anchor" href="#mainnet-https-github-com-unification-com-mainnet-blob-master-latest-seed-nodes-md" aria-hidden="true">#</a> MainNet: <a href="https://github.com/unification-com/mainnet/blob/master/latest/seed_nodes.md" target="_blank" rel="noopener noreferrer">https://github.com/unification-com/mainnet/blob/master/latest/seed_nodes.md<ExternalLinkIcon/></a></h4>
<p>Go to the repo for the network you are connecting to and copy one or more of the seed nodes (you only need
the <code v-pre>id@address:port</code>)</p>
<p>Edit your node configuration file using nano:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">nano</span> /path/to/.und_mainchain/config/config.toml
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Hit <kbd>Ctrl</kbd>+<kbd>W</kbd>, type <code v-pre>[p2p]</code> (including the square brackets) and hit return - this will take you to
the <code v-pre>[p2p]</code> section of the config file, which begins with:</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>##### peer to peer configuration options #####
[p2p]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Find the <code v-pre>seeds = &quot;&quot;</code> variable about 12 lines below, and add the seed node information between the double quotes (comma
separated, no spaces if more than one). For example:</p>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">seeds</span> <span class="token punctuation">=</span> <span class="token string">"node_id@ip:port"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Next, hit <kbd>Ctrl</kbd>+<kbd>W</kbd>, type <code v-pre>[rpc]</code> (including the square brackets) and hit return - this will take you
to the <code v-pre>[rpc]</code> section of the config file, which begins with:</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>##### rpc server configuration options #####
[rpc]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>About 3 lines under this, find:</p>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">laddr</span> <span class="token punctuation">=</span> <span class="token string">"tcp://127.0.0.1:26657"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Change the value to:</p>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">laddr</span> <span class="token punctuation">=</span> <span class="token string">"tcp://0.0.0.0:26657"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Hit <kbd>Ctrl</kbd>+<kbd>X</kbd> followed by <code v-pre>y</code> and then return to save the file and exit nano.</p>
<div class="custom-container tip"><p class="custom-container-title">Note</p>
<p>you can revert the <code v-pre>[rpc]</code> configuration for port <code v-pre>26657</code> to:</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>laddr = "tcp://127.0.0.1:26657"
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>once you have run the<code v-pre> create-validator</code> command. Broadcasting transactions can instead be done via a public RPC node,
or, more securely, via a full node running on your local PC. See <a href="#part-8-final-cleanup">Part 8: Final cleanup</a> for
further details.</p>
</div>
<h3 id="gas-prices" tabindex="-1"><a class="header-anchor" href="#gas-prices" aria-hidden="true">#</a> Gas Prices</h3>
<p>It is good practice to set the minimum-gas-prices value in <code v-pre>$HOME/.und_mainchain/config/app.toml</code>, in order to protect
your full node from spam transactions. This should be set as a decimal value in <code v-pre>nund</code>, and the recommended value is
currently <code v-pre>25.0nund</code>. This means your node will ignore any Txs with a gas price below this value. To do so, open
up <code v-pre>$HOME/.und_mainchain/config/app.toml</code> in a text editor, and set <code v-pre>minimum-gas-prices</code></p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">nano</span> <span class="token environment constant">$HOME</span>/.und_mainchain/config/app.toml
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Change:</p>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">minimum-gas-prices</span> <span class="token punctuation">=</span> <span class="token string">""</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>To, for example:</p>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">minimum-gas-prices</span> <span class="token punctuation">=</span> <span class="token string">"25.0nund"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Hit <kbd>Ctrl</kbd>+<kbd>X</kbd> followed by <code v-pre>y</code> and then return to save the file and exit nano.</p>
<h3 id="syncing-the-node-with-statesync" tabindex="-1"><a class="header-anchor" href="#syncing-the-node-with-statesync" aria-hidden="true">#</a> Syncing the node with <code v-pre>statesync</code></h3>
<p>Cosmos SDK &gt;= 0.42, which is used by the latest <code v-pre>und</code> software, can use State Syncing  from Snapshots to quickly
sync your node from a safe checkpoint. This potentially reduces the sync time to no more than an hour or so, and in
most cases mere minutes.</p>
<p>Setting this up requires a few more steps</p>
<ol>
<li>Run the following command to get the latest block hash and height. For <strong>TestNet</strong>:</li>
</ol>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> -s https://rest-testnet.unification.io/blocks/latest <span class="token operator">|</span> jq <span class="token string">'.|[.block_id.hash,.block.header.height]'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>For <strong>MainNet</strong>:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> -s https://rest.unification.io/blocks/latest <span class="token operator">|</span> jq <span class="token string">'.|[.block_id.hash,.block.header.height]'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Example output:</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code><span class="token punctuation">[</span>
  <span class="token string">"820275B5EE63EDA2923886A01C0B1196A7CE1D96A89FA0D774942999C6698AAC"</span><span class="token punctuation">,</span>
  <span class="token string">"1052423"</span>
<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="2">
<li>Using the output from the above command, configure <code v-pre>[statesync]</code> section in <code v-pre>.und_mainchain/config.toml</code>:</li>
</ol>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">enable</span> <span class="token punctuation">=</span> <span class="token boolean">true</span>
<span class="token key property">rpc_servers</span> <span class="token punctuation">=</span> <span class="token string">"TWO_RPC_NODES"</span>
<span class="token key property">trust_height</span> <span class="token punctuation">=</span> <span class="token number">1052423</span>
<span class="token key property">trust_hash</span> <span class="token punctuation">=</span> <span class="token string">"820275B5EE63EDA2923886A01C0B1196A7CE1D96A89FA0D774942999C6698AAC"</span>
<span class="token key property">trust_period</span> <span class="token punctuation">=</span> <span class="token string">"168h0m0s"</span>
<span class="token key property">discovery_time</span> <span class="token punctuation">=</span> <span class="token string">"30s"</span>
<span class="token key property">temp_dir</span> <span class="token punctuation">=</span> <span class="token string">""</span>
<span class="token key property">chunk_request_timeout</span> <span class="token punctuation">=</span> <span class="token string">"60s"</span>
<span class="token key property">chunk_fetchers</span> <span class="token punctuation">=</span> <span class="token string">"4"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>The <code v-pre>rpc_servers</code> requires two RPC nodes for verification.</p>
<p>For <strong>TestNet</strong>, replace <code v-pre>TWO_RPC_NODES</code> with:</p>
<p><code v-pre>sync1-testnet.unification.io:26657,sync2-testnet.unification.io:26657</code></p>
<p>For <strong>MainNet</strong>:</p>
<p><code v-pre>sync1.unification.io:26657,sync2.unification.io:26657</code></p>
<p>e.g.:</p>
<div class="language-toml ext-toml line-numbers-mode"><pre v-pre class="language-toml"><code><span class="token key property">rpc_servers</span> <span class="token punctuation">=</span> <span class="token string">"sync1.unification.io:26657,sync2.unification.io:26657"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Or any RPC servers of your choice for the target network.</p>
<ol start="3">
<li>Start your node</li>
</ol>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>und start --home<span class="token operator">=</span>/path/to/.und_mainchain
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>you should start seeing the following:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token number">11</span>:53AM INF Discovered new snapshot <span class="token assign-left variable">format</span><span class="token operator">=</span><span class="token number">1</span> <span class="token assign-left variable">hash</span><span class="token operator">=</span><span class="token string">"V0���&amp;�U1�J0�yP4A%�/���GŽ@<span class="token entity" title="\x05">\x05</span>�&lt;�j"</span> <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1051600</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>statesync
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>After a few seconds (or at most, minutes), you should see your node start downloading the blocks:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token number">11</span>:56AM INF received proposal <span class="token assign-left variable">module</span><span class="token operator">=</span>consensus <span class="token assign-left variable">proposal</span><span class="token operator">=</span><span class="token punctuation">{</span><span class="token string">"Type"</span>:32,<span class="token string">"block_id"</span>:<span class="token punctuation">{</span><span class="token string">"hash"</span><span class="token builtin class-name">:</span><span class="token string">"632E122ADDF385954FB8598FEE7D89EB09D7E93746FB36D2F12DECFEB7F07D9E"</span>,<span class="token string">"parts"</span>:<span class="token punctuation">{</span><span class="token string">"hash"</span><span class="token builtin class-name">:</span><span class="token string">"E8246C504B9BC14275874A90C95E6AA035678302AD3BF9269B6F253B04C038BE"</span>,<span class="token string">"total"</span>:1<span class="token punctuation">}</span><span class="token punctuation">}</span>,<span class="token string">"height"</span>:1052494,<span class="token string">"pol_round"</span>:-1,<span class="token string">"round"</span>:0,<span class="token string">"signature"</span><span class="token builtin class-name">:</span><span class="token string">"HYJz0rV7o6bNm7za82sj1Az1rV25qVkLh9Y4s0K95nf86uVq+YmuDIf3LtIP7pDfFEYErxNVyeSplPGh7IVHDQ=="</span>,<span class="token string">"timestamp"</span><span class="token builtin class-name">:</span><span class="token string">"2022-05-19T10:56:03.273030584Z"</span><span class="token punctuation">}</span>
<span class="token number">11</span>:56AM INF received complete proposal block <span class="token assign-left variable">hash</span><span class="token operator">=</span>632E122ADDF385954FB8598FEE7D89EB09D7E93746FB36D2F12DECFEB7F07D9E <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1052494</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>consensus
<span class="token number">11</span>:56AM INF finalizing commit of block <span class="token assign-left variable">hash</span><span class="token operator">=</span>632E122ADDF385954FB8598FEE7D89EB09D7E93746FB36D2F12DECFEB7F07D9E <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1052494</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>consensus <span class="token assign-left variable">num_txs</span><span class="token operator">=</span><span class="token number">0</span> <span class="token assign-left variable">root</span><span class="token operator">=</span>7EC77102840743503BD71FD89F60FD0B912DD0DE27575408B6AD67990CE4A6B8
<span class="token number">11</span>:56AM INF executed block <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1052494</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>state <span class="token assign-left variable">num_invalid_txs</span><span class="token operator">=</span><span class="token number">0</span> <span class="token assign-left variable">num_valid_txs</span><span class="token operator">=</span><span class="token number">0</span>
<span class="token number">11</span>:56AM INF commit synced <span class="token assign-left variable">commit</span><span class="token operator">=</span>436F6D6D697449447B5B3234312031333020323235203834203837203234372031303220323820323435203234382032372032303920313432203133372031303620353920343520323220323020313737203135342032303320323338203136352030203231322034392031383620313638203433203839203233395D3A3130304634457D
<span class="token number">11</span>:56AM INF committed state <span class="token assign-left variable">app_hash</span><span class="token operator">=</span>F182E15457F7661CF5F81BD18E896A3B2D1614B19ACBEEA500D431BAA82B59EF <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1052494</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>state <span class="token assign-left variable">num_txs</span><span class="token operator">=</span><span class="token number">0</span>
<span class="token number">11</span>:56AM INF indexed block <span class="token assign-left variable">height</span><span class="token operator">=</span><span class="token number">1052494</span> <span class="token assign-left variable">module</span><span class="token operator">=</span>txindex
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Hit <kbd>Ctrl</kbd>+<kbd>C</kbd> to stop the node - it will be configured as a background service next.</p>
<div class="custom-container danger"><p class="custom-container-title">IMPORTANT</p>
<p>keep your <code v-pre>/mnt/disks/data/.und_mainchain/config/node_key.json</code>
and <code v-pre>/mnt/disks/data/.und_mainchain/config/priv_validator_key.json</code> files safe! These are required for your node to
propose and sign blocks. If you ever migrate your node to a different host/VM instance, you will need these.</p>
</div>
<h2 id="part-6-running-und-as-a-daemon" tabindex="-1"><a class="header-anchor" href="#part-6-running-und-as-a-daemon" aria-hidden="true">#</a> Part 6: Running und as a daemon</h2>
<p>Once you have initialised and tested the <code v-pre>und</code> node, it can be set up as a background daemon on the server
using <code v-pre>systemctl</code>. This means that you can easily start/stop/restart the service, and do not need to leave the SSH
session open while und is running.</p>
<p>If you’re not logged in to your VM instance via SSH, log in. If you are still logged in, and have not stopped the und
node, hit <kbd>Ctrl</kbd>+<kbd>C</kbd> to stop the node.</p>
<p>We need to use the nano text editor to create the service configuration. Run:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> <span class="token function">nano</span> /etc/systemd/system/und.service
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>At a minimum, the service configuration should contain the following, replacing <code v-pre>USERNAME</code> and <code v-pre>FULL_PATH_TO</code>
with your own values:</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>[Unit]
Description=Unification Mainchain Validator Node

[Service]
User=USERNAME
Group=USERNAME
WorkingDirectory=/home/USERNAME
ExecStart=/usr/local/bin/und start --home /FULL_PATH_TO/.und_mainchain
LimitNOFILE=4096

[Install]
WantedBy=default.target
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>It is entirely possible to create a more sophisticated service definition should you desire.</p>
<div class="custom-container tip"><p class="custom-container-title">Note</p>
<p><strong>Also see</strong>: <RouterLink to="/mainchain/migrations/cosmovisor.html">Using Cosmovisor with und: Quick Start</RouterLink> for details on running <code v-pre>und</code> with
<code v-pre>cosmovisor</code>.</p>
</div>
<p>Next, inform <code v-pre>systemctl</code> of the new service:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> systemctl daemon-reload
<span class="token function">sudo</span> systemctl <span class="token builtin class-name">enable</span> und
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>The service can now be started:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> systemctl start und
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>and stopped:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> systemctl stop und
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>in the background.</p>
<p>Finally, you can monitor the log output for the service by running:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>$ <span class="token function">sudo</span> journalctl -u und --follow
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>and use <kbd>Ctrl</kbd>+<kbd>C</kbd> to exit the <code v-pre>journalctl</code> command. You can now log out of your SSH session and und
will continue running in the background.</p>
<h2 id="part-7-become-a-validator" tabindex="-1"><a class="header-anchor" href="#part-7-become-a-validator" aria-hidden="true">#</a> Part 7: Become a Validator</h2>
<div class="custom-container danger"><p class="custom-container-title">Important</p>
<p>ensure your node has fully synced with the network before continuing.</p>
</div>
<p>If not already logged in, log in to your VM instance via SSH, and run:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> journalctl -u und --follow
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Once fully synced (check the downloaded height against the current clock in the block explorer), hit <kbd>Ctrl</kbd>
+<kbd>C</kbd> to quit the journalctl command.</p>
<p>You will need your Validator node’s Tendermint public key in order to register it on the Mainchain network as a
validator. Whilst still in the SSH session connected to your VM, run:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>und tendermint show-validator --home<span class="token operator">=</span>/mnt/disks/data/.und_mainchain
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Make a note of the output, as you will need this in later commands, where it will be referred to
as <code v-pre>[your_validator_public_key]</code>.</p>
<p>You can now exit the SSH session - the rest of the commands will be run in a terminal on your local PC.</p>
<p>Go
to <a href="https://github.com/unification-com/mainchain/releases/latest" target="_blank" rel="noopener noreferrer">https://github.com/unification-com/mainchain/releases/latest<ExternalLinkIcon/></a>
and download the latest <code v-pre>und</code> archive for your OS - for example, <code v-pre>und_v1.5.1_windows_x86_64.tar.gz</code>.</p>
<p>Open a terminal/PowerShell, and <code v-pre>cd</code> into the directory where you extracted the <code v-pre>und</code> executable:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token builtin class-name">cd</span> path/to/extracted/und_directory
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>As previously, any text in <code v-pre>[square_brackets]</code> (<em>including</em> the square brackets) in the following commands should be
replaced with your own values accordingly.</p>
<p>If you do not already have a wallet/account, you can create one (on your local PC, not in the SSH session) by running:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>./und keys <span class="token function">add</span> account_name
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>If you already have a wallet, you can import the account using:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>./und keys <span class="token function">add</span> account_name --recover
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>in which case, you will be prompted for the mnemonic and a password to secure the wallet.</p>
<p>From here, it is assumed the reader has an account with sufficient FUND from which to self-delegate and create their
Validator node. The account you use to self-delegate will become the &quot;owner&quot; account of the Validator node.</p>
<p>On your local PC, run the following command, replacing any text in <code v-pre>[square_brackets]</code> accordingly with your own values:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>./und tx staking create-validator <span class="token punctuation">\</span>
--amount<span class="token operator">=</span><span class="token punctuation">[</span>stake_in_nund<span class="token punctuation">]</span> <span class="token punctuation">\</span>
--pubkey<span class="token operator">=</span><span class="token punctuation">[</span>your_validator_public_key<span class="token punctuation">]</span> <span class="token punctuation">\</span>
--moniker<span class="token operator">=</span><span class="token string">"[your_ev_moniker]"</span> <span class="token punctuation">\</span>
--website<span class="token operator">=</span><span class="token string">"[your_website]"</span> <span class="token punctuation">\</span>
--details<span class="token operator">=</span><span class="token string">"[description]"</span> <span class="token punctuation">\</span>
--security-contact<span class="token operator">=</span><span class="token string">"[security_email]"</span> <span class="token punctuation">\</span>
--chain-id<span class="token operator">=</span><span class="token punctuation">[</span>chain_id<span class="token punctuation">]</span> <span class="token punctuation">\</span>
--commission-rate<span class="token operator">=</span><span class="token string">"[0.10]"</span> <span class="token punctuation">\</span>
--commission-max-rate<span class="token operator">=</span><span class="token string">"[0.20]"</span> <span class="token punctuation">\</span>
--commission-max-change-rate<span class="token operator">=</span><span class="token string">"[0.01]"</span> <span class="token punctuation">\</span>
--min-self-delegation<span class="token operator">=</span><span class="token string">"1"</span> <span class="token punctuation">\</span>
--gas<span class="token operator">=</span><span class="token string">"auto"</span> <span class="token punctuation">\</span>
--gas-prices<span class="token operator">=</span><span class="token string">"25.0nund"</span> <span class="token punctuation">\</span>
--gas-adjustment<span class="token operator">=</span><span class="token number">1.5</span> <span class="token punctuation">\</span>
--from<span class="token operator">=</span>account_name <span class="token punctuation">\</span>
--node<span class="token operator">=</span>tcp://<span class="token punctuation">[</span>vm_ip<span class="token punctuation">]</span>:26657
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>[stake_in_nund]</code> = (required) the amount of FUND in <code v-pre>nund</code> you are self-delegating. You can use
the <code v-pre>und convert 1000 fund nund</code> command to convert FUND to nund. E.g. <code v-pre>1000000000000nund</code>.</p>
<div class="custom-container warning"><p class="custom-container-title">Note</p>
<p>do not enter more nund than you have in your wallet!</p>
</div>
<p><code v-pre>[your_validator_public_key]</code> = (required) the public key output from the previous und tendermint show-validator
command.</p>
<p><code v-pre>[your_ev_moniker]</code> = (required) a publicly visible ID/tag for your Validator node.</p>
<p><code v-pre>[your_website]</code> = (optional) website promoting your node</p>
<p><code v-pre>[description]</code> = (optional) short description of your node</p>
<p><code v-pre>[security_email]</code> = (optional) security contact for your organisation</p>
<p><code v-pre>[chain_id]</code> = the network (e.g. <code v-pre>FUND-TestNet-2</code>, or <code v-pre>FUND-MainNet-2</code>) you are creating a
validator on - this was obtained earlier in the guide via the <code v-pre>jq</code> command</p>
<p><code v-pre>[account_name]</code> = the account self-delegating the FUND, previously created/imported with the <code v-pre>und keys add</code> command</p>
<p><code v-pre>[vm_ip]</code> = the IP address of your EC2 instance running the full node - you can get this from your AWS EC2 Instances
console.</p>
<h4 id="commission-rates" tabindex="-1"><a class="header-anchor" href="#commission-rates" aria-hidden="true">#</a> Commission Rates</h4>
<p>Your commission rates can be set using the <code v-pre>--commission-rate</code>
, <code v-pre>--commission-max-change-rate and</code> <code v-pre>--commission-max-rate</code> flags.</p>
<p><code v-pre>--commission-rate</code>: The % commission you will earn from delegators' rewards. Keeping this low can attract more
delegators to your node.</p>
<p><code v-pre>--commission-max-rate</code>: The maximum you will ever increase your commission rate to - you cannot raise commission above
this value. Again, keeping this low can attract more delegators.</p>
<p><code v-pre>--commission-max-change-rate</code>: The maximum you can increase the commission-rate by per day. For example, if your
maximum change rate is 0.01, you can only make changes in 0.01 increments, so from 0.10 (10%) to 0.11 (11%).</p>
<div class="custom-container warning"><p class="custom-container-title">WARNING</p>
<p>The values for <code v-pre>--commission-max-change-rate</code> and <code v-pre>--commission-max-rate</code> flags cannot be changed after the
create-validator command has been run.</p>
</div>
<p>Finally, the <code v-pre>--min-self-delegation</code> flag is the minimum amount of <code v-pre>nund</code> you are required to keep self-delegated to
your validtor, meaning you must always have at least this amount self-delegated to your node.</p>
<p>For example:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>./und tx staking create-validator <span class="token punctuation">\</span>
--amount<span class="token operator">=</span>1000000000000nund <span class="token punctuation">\</span>
--pubkey<span class="token operator">=</span>undvalconspub1zcjduepq6yq7drzefkavsrxhxk69cy63tj3r<span class="token punctuation">..</span>. <span class="token punctuation">\</span>
--moniker<span class="token operator">=</span><span class="token string">"MyAwesomeNode"</span> <span class="token punctuation">\</span>
--website<span class="token operator">=</span><span class="token string">"https://my-node-site.com"</span> <span class="token punctuation">\</span>
--details<span class="token operator">=</span><span class="token string">"My node is awesome"</span> <span class="token punctuation">\</span>
--security-contact<span class="token operator">=</span><span class="token string">"security@my-node-site.com"</span> <span class="token punctuation">\</span>
--chain-id<span class="token operator">=</span>FUND-TestNet-2 <span class="token punctuation">\</span>
--commission-rate<span class="token operator">=</span><span class="token string">"0.05"</span> <span class="token punctuation">\</span>
--commission-max-rate<span class="token operator">=</span><span class="token string">"0.10"</span> <span class="token punctuation">\</span>
--commission-max-change-rate<span class="token operator">=</span><span class="token string">"0.01"</span> <span class="token punctuation">\</span>
--min-self-delegation<span class="token operator">=</span><span class="token string">"1"</span> <span class="token punctuation">\</span>
--gas<span class="token operator">=</span><span class="token string">"auto"</span> <span class="token punctuation">\</span>
--gas-prices<span class="token operator">=</span><span class="token string">"25.0nund"</span> <span class="token punctuation">\</span>
--gas-adjustment<span class="token operator">=</span><span class="token number">1.5</span> <span class="token punctuation">\</span>
--from<span class="token operator">=</span>my_new_wallet <span class="token punctuation">\</span>
--node<span class="token operator">=</span>tcp://33.44.55.66:26657
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Your validator node should now be registered and contributing to the network. To verify, on you local PC, run the
following:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>./und query staking validator <span class="token punctuation">\</span>
<span class="token variable"><span class="token variable">$(</span>und keys show <span class="token punctuation">[</span>account_name<span class="token punctuation">]</span> --bech<span class="token operator">=</span>val -a<span class="token variable">)</span></span> <span class="token punctuation">\</span>
--chain-id<span class="token operator">=</span><span class="token punctuation">[</span>chain_id<span class="token punctuation">]</span> <span class="token punctuation">\</span>
--node<span class="token operator">=</span>tcp://<span class="token punctuation">[</span>vm_ip<span class="token punctuation">]</span>:26657
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Replacing <code v-pre>[account_name]</code>, <code v-pre>[chain_id]</code> and <code v-pre>[vm_ip]</code> accordingly. Assuming you are going through this guide
on <code v-pre>TestNet</code>, you should also see your node listed
in <a href="https://explorer-testnet.unification.io/validators" target="_blank" rel="noopener noreferrer">https://explorer-testnet.unification.io/validators<ExternalLinkIcon/></a></p>
<h2 id="part-8-final-cleanup" tabindex="-1"><a class="header-anchor" href="#part-8-final-cleanup" aria-hidden="true">#</a> Part 8: Final cleanup</h2>
<p>Finally, it’s a good idea to close the <strong>RPC</strong> port (<code v-pre>26657</code>) on your validator node, leaving only the <strong>P2P</strong>
port (<code v-pre>26656</code>) open so that it can communicate with other nodes. This can be done by deleting the firewall rule for the
RPC port, and by reverting the RPC laddr configuration value in <code v-pre>config.toml</code> to the <code v-pre>127.0.0.1</code> IP address (which will
restrict the node’s RPC access to localhost). Further interaction with the network can be done by spinning up a separate
non-validator full node (on your local PC for example), and broadcasting transactions via that node instead.</p>
<div class="custom-container danger"><p class="custom-container-title">Important</p>
<p>Do not alter the <strong>P2P</strong> port (<code v-pre>26656</code>) configuration and firewall rules. If you do, your validator node will not be
able to communicate with its peers.</p>
</div>
<p>That’s it - you should now have a full Validator node up and running on a very basic Google Cloud Linux VM instance.
Once again - Validator node operators are highly encouraged to explore more sophisticated architecture configurations to
increase the security, reliability and availability of their Validator node.</p>
</div></template>
