<template><div><h1 id="vorrequestidbase" tabindex="-1"><a class="header-anchor" href="#vorrequestidbase" aria-hidden="true">#</a> VORRequestIDBase</h1>
<h2 id="functions" tabindex="-1"><a class="header-anchor" href="#functions" aria-hidden="true">#</a> Functions:</h2>
<ul>
<li><a href="#VORRequestIDBase-makeVORInputSeed-bytes32-uint256-address-uint256-"><code v-pre>makeVORInputSeed(bytes32 _keyHash, uint256 _userSeed, address _requester, uint256 _nonce) internal</code></a></li>
<li><a href="#VORRequestIDBase-makeRequestId-bytes32-uint256-"><code v-pre>makeRequestId(bytes32 _keyHash, uint256 _vORInputSeed) internal</code></a></li>
</ul>
<p><a name="VORRequestIDBase-makeVORInputSeed-bytes32-uint256-address-uint256-"></a></p>
<h3 id="function-makevorinputseed-bytes32-keyhash-uint256-userseed-address-requester-uint256-nonce-internal-uint256" tabindex="-1"><a class="header-anchor" href="#function-makevorinputseed-bytes32-keyhash-uint256-userseed-address-requester-uint256-nonce-internal-uint256" aria-hidden="true">#</a> Function <code v-pre>makeVORInputSeed(bytes32 _keyHash, uint256 _userSeed, address _requester, uint256 _nonce) internal  -&gt; uint256</code></h3>
<p>To prevent repetition of VOR output due to repetition of the
user-supplied seed, that seed is combined in a hash with the
user-specific nonce, and the address of the consuming contract. The
risk of repetition is mostly mitigated by inclusion of a blockhash in
the final seed, but the nonce does protect against repetition in
requests which are included in a single block.</p>
<h4 id="parameters" tabindex="-1"><a class="header-anchor" href="#parameters" aria-hidden="true">#</a> Parameters:</h4>
<ul>
<li>
<p><code v-pre>_userSeed</code>: VOR seed input provided by user</p>
</li>
<li>
<p><code v-pre>_requester</code>: Address of the requesting contract</p>
</li>
<li>
<p><code v-pre>_nonce</code>: User-specific nonce at the time of the request
<a name="VORRequestIDBase-makeRequestId-bytes32-uint256-"></a></p>
</li>
</ul>
<h3 id="function-makerequestid-bytes32-keyhash-uint256-vorinputseed-internal-bytes32" tabindex="-1"><a class="header-anchor" href="#function-makerequestid-bytes32-keyhash-uint256-vorinputseed-internal-bytes32" aria-hidden="true">#</a> Function <code v-pre>makeRequestId(bytes32 _keyHash, uint256 _vORInputSeed) internal  -&gt; bytes32</code></h3>
<p>Note that _vORInputSeed is not the seed passed by the consuming
contract, but the one generated by makeVORInputSeed</p>
<h4 id="parameters-1" tabindex="-1"><a class="header-anchor" href="#parameters-1" aria-hidden="true">#</a> Parameters:</h4>
<ul>
<li>
<p><code v-pre>_keyHash</code>: The serviceAgreement ID to be used for this request</p>
</li>
<li>
<p><code v-pre>_vORInputSeed</code>: The seed to be passed directly to the VOR</p>
</li>
</ul>
<h4 id="return-values" tabindex="-1"><a class="header-anchor" href="#return-values" aria-hidden="true">#</a> Return Values:</h4>
<ul>
<li>The id for this request</li>
</ul>
</div></template>
